#!/bin/bash

if [ "X$ANDROID_HOME" = "X" ]; then
   echo "ANDROID_HOME not set. if android skd is not installed, install it from android studio"
   return
else
   echo "ANDROID_HOME=$ANDROID_HOME"
fi

echo "adding to PATH android sdk tools
$ANDROID_HOME_TERM_SPECIFIC/cmdline-tools/latest/bin
$ANDROID_HOME_TERM_SPECIFIC/platform-tools
$ANDROID_HOME_TERM_SPECIFIC/emulator
"

PATH="$ANDROID_HOME_TERM_SPECIFIC/cmdline-tools/latest/bin:$ANDROID_HOME_TERM_SPECIFIC/platform-tools:$ANDROID_HOME_TERM_SPECIFIC/emulator:$PATH"

local BUILD_TOOLS
BUILD_TOOLS=`/bin/ls -d $ANDROID_HOME/build-tools/*|tail -1`

if [ "X$BUILD_TOOLS" != "X" ]; then
   PATH="$BUILD_TOOLS:$PATH"
fi

export PATH

reduce PATH

echo "to start android studio, type: androidstudio"

androidstudio () {
   if [ "X$ANDROID_STUDIO" = "X" ]; then
      echo "ANDROID_STUDIO is not defined. we don't know where android studio is installed"
      return
   fi

   "$ANDROID_STUDIO"
}

echo "to go to android sdk folder, type:  androidsdk"
androidsdk () { cd "$ANDROID_HOME"; }
