field_by_tag =  {'1': 'Account',
 '10': 'CheckSum',
 '100': 'ExDestination',
 '102': 'CxlRejReason',
 '103': 'OrdRejReason',
 '104': 'IOIQualifier',
 '105': 'WaveNo',
 '106': 'Issuer',
 '107': 'SecurityDesc',
 '108': 'HeartBtInt',
 '109': 'ClientID(replaced)',
 '11': 'ClOrdID',
 '110': 'MinQty',
 '111': 'MaxFloor',
 '112': 'TestReqID',
 '113': 'ReportToExch',
 '114': 'LocateReqd',
 '115': 'OnBehalfOfCompID',
 '116': 'OnBehalfOfSubID',
 '117': 'QuoteID',
 '118': 'NetMoney',
 '119': 'SettlCurrAmt',
 '12': 'Commission',
 '120': 'SettlCurrency',
 '121': 'ForexReq',
 '122': 'OrigSendingTime',
 '123': 'GapFillFlag',
 '124': 'NoExecs',
 '126': 'ExpireTime',
 '127': 'DKReason',
 '128': 'DeliverToCompID',
 '129': 'DeliverToSubID',
 '13': 'CommType',
 '130': 'IOINaturalFlag',
 '131': 'QuoteReqID',
 '132': 'BidPx',
 '133': 'OfferPx',
 '134': 'BidSize',
 '135': 'OfferSize',
 '136': 'NoMiscFees',
 '137': 'MiscFeeAmt',
 '138': 'MiscFeeCurr',
 '139': 'MiscFeeType',
 '14': 'CumQty',
 '140': 'PrevClosePx',
 '141': 'ResetSeqNumFlag',
 '142': 'SenderLocationID',
 '143': 'TargetLocationID',
 '144': 'OnBehalfOfLocationID',
 '145': 'DeliverToLocationID',
 '146': 'NoRelatedSym',
 '147': 'Subject',
 '148': 'Headline',
 '149': 'URLLink',
 '15': 'Currency',
 '150': 'ExecType',
 '151': 'LeavesQty',
 '152': 'CashOrderQty',
 '153': 'AllocAvgPx',
 '154': 'AllocNetMoney',
 '155': 'SettlCurrFxRate',
 '156': 'SettlCurrFxRateCalc',
 '157': 'NumDaysInterest',
 '158': 'AccruedInterestRate',
 '159': 'AccruedInterestAmt',
 '16': 'EndSeqNo',
 '160': 'SettlInstMode',
 '161': 'AllocText',
 '162': 'SettlInstID',
 '163': 'SettlInstTransType',
 '164': 'EmailThreadID',
 '165': 'SettlInstSource',
 '166': 'SettlLocation(replaced)',
 '167': 'SecurityType',
 '168': 'EffectiveTime',
 '169': 'StandInstDbType',
 '17': 'ExecID',
 '170': 'StandInstDbName',
 '171': 'StandInstDbID',
 '172': 'SettlDeliveryType',
 '173': 'SettlDepositoryCode',
 '174': 'SettlBrkrCode',
 '175': 'SettlInstCode',
 '176': 'SecuritySettlAgentName',
 '177': 'SecuritySettlAgentCode',
 '178': 'SecuritySettlAgentAcctNum',
 '179': 'SecuritySettlAgentAcctName',
 '18': 'ExecInst',
 '180': 'SecuritySettlAgentContactName',
 '181': 'SecuritySettlAgentContactPhone',
 '182': 'CashSettlAgentName',
 '183': 'CashSettlAgentCode',
 '184': 'CashSettlAgentAcctNum',
 '185': 'CashSettlAgentAcctName',
 '186': 'CashSettlAgentContactName',
 '187': 'CashSettlAgentContactPhone',
 '188': 'BidSpotRate',
 '189': 'BidForwardPoints',
 '19': 'ExecRefID',
 '190': 'OfferSpotRate',
 '191': 'OfferForwardPoints',
 '192': 'OrderQty2',
 '193': 'FutSettDate2',
 '194': 'LastSpotRate',
 '195': 'LastForwardPoints',
 '196': 'AllocLinkID',
 '197': 'AllocLinkType',
 '198': 'SecondaryOrderID',
 '199': 'NoIOIQualifiers',
 '2': 'AdvId',
 '20': 'ExecTransType(replaced)',
 '200': 'MaturityMonthYear',
 '201': 'PutOrCall(replaced)',
 '202': 'StrikePrice',
 '203': 'CoveredOrUncovered',
 '204': 'CustomerOrFirm(replaced)',
 '205': 'MaturityDay(replaced)',
 '206': 'OptAttribute',
 '207': 'SecurityExchange',
 '208': 'NotifyBrokerOfCredit',
 '209': 'AllocHandlInst',
 '21': 'HandlInst',
 '210': 'MaxShow',
 '211': 'PegDifference',
 '212': 'XmlDataLen',
 '213': 'XmlData',
 '214': 'SettlInstRefID',
 '215': 'NoRoutingIDs',
 '216': 'RoutingType',
 '217': 'RoutingID',
 '219': 'Benchmark(Deprecated)',
 '220': 'BenchmarkCurveCurrency',
 '221': 'BenchmarkCurveName',
 '222': 'BenchmarkCurvePoint',
 '223': 'CouponRate',
 '224': 'CouponPaymentDate',
 '225': 'IssueDate',
 '226': 'RepurchaseTerm',
 '227': 'RepurchaseRate',
 '228': 'Factor',
 '229': 'TradeOriginationDate',
 '23': 'IOIid',
 '230': 'ExDate',
 '231': 'ContractMultiplier',
 '232': 'NoStipulations',
 '233': 'StipulationType',
 '234': 'StipulationValue',
 '235': 'YieldType',
 '236': 'Yield',
 '237': 'TotalTakedown',
 '238': 'Concession',
 '239': 'RepoCollateralSecurityType',
 '240': 'RedemptionDate',
 '241': 'UnderlyingCouponPaymentDate',
 '242': 'UnderlyingIssueDate',
 '243': 'UnderlyingRepoCollateralSecurityType',
 '244': 'UnderlyingRepurchaseTerm',
 '245': 'UnderlyingRepurchaseRate',
 '246': 'UnderlyingFactor',
 '247': 'UnderlyingRedemptionDate',
 '248': 'LegCouponPaymentDate',
 '249': 'LegIssueDate',
 '25': 'IOIQltyInd',
 '250': 'LegRepoCollateralSecurityType',
 '251': 'LegRepurchaseTerm',
 '252': 'LegRepurchaseRate',
 '253': 'LegFactor',
 '254': 'LegRedemptionDate',
 '255': 'CreditRating',
 '256': 'UnderlyingCreditRating',
 '257': 'LegCreditRating',
 '258': 'TradedFlatSwitch',
 '259': 'BasisFeatureDate',
 '26': 'IOIRefID',
 '260': 'BasisFeaturePrice',
 '262': 'MDReqID',
 '263': 'SubscriptionRequestType',
 '264': 'MarketDepth',
 '265': 'MDUpdateType',
 '266': 'AggregatedBook',
 '267': 'NoMDEntryTypes',
 '268': 'NoMDEntries',
 '269': 'MDEntryType',
 '270': 'MDEntryPx',
 '271': 'MDEntrySize',
 '272': 'MDEntryDate',
 '273': 'MDEntryTime',
 '274': 'TickDirection',
 '275': 'MDMkt',
 '276': 'QuoteCondition',
 '277': 'TradeCondition',
 '278': 'MDEntryID',
 '279': 'MDUpdateAction',
 '28': 'IOITransType',
 '280': 'MDEntryRefID',
 '281': 'MDReqRejReason',
 '282': 'MDEntryOriginator',
 '283': 'LocationID',
 '284': 'DeskID',
 '285': 'DeleteReason',
 '286': 'OpenCloseSettleFlag',
 '287': 'SellerDays',
 '288': 'MDEntryBuyer',
 '289': 'MDEntrySeller',
 '29': 'LastCapacity',
 '290': 'MDEntryPositionNo',
 '291': 'FinancialStatus',
 '292': 'CorporateAction',
 '293': 'DefBidSize',
 '294': 'DefOfferSize',
 '295': 'NoQuoteEntries',
 '296': 'NoQuoteSets',
 '298': 'QuoteCancelType',
 '299': 'QuoteEntryID',
 '3': 'AdvRefID',
 '30': 'LastMkt',
 '300': 'QuoteRejectReason',
 '301': 'QuoteResponseLevel',
 '302': 'QuoteSetID',
 '303': 'QuoteRequestType',
 '304': 'TotQuoteEntries',
 '306': 'UnderlyingIssuer',
 '307': 'UnderlyingSecurityDesc',
 '308': 'UnderlyingSecurityExchange',
 '309': 'UnderlyingSecurityID',
 '31': 'LastPx',
 '310': 'UnderlyingSecurityType',
 '311': 'UnderlyingSymbol',
 '312': 'UnderlyingSymbolSfx',
 '313': 'UnderlyingMaturityMonthYear',
 '314': 'UnderlyingMaturityDay(replaced)',
 '315': 'UnderlyingPutOrCall(replaced)',
 '316': 'UnderlyingStrikePrice',
 '317': 'UnderlyingOptAttribute',
 '319': 'RatioQty',
 '320': 'SecurityReqID',
 '321': 'SecurityRequestType',
 '322': 'SecurityResponseID',
 '323': 'SecurityResponseType',
 '324': 'SecurityStatusReqID',
 '325': 'UnsolicitedIndicator',
 '326': 'SecurityTradingStatus',
 '327': 'HaltReason',
 '328': 'InViewOfCommon',
 '329': 'DueToRelated',
 '33': 'LinesOfText',
 '330': 'BuyVolume',
 '331': 'SellVolume',
 '332': 'HighPx',
 '333': 'LowPx',
 '334': 'Adjustment',
 '335': 'TradSesReqID',
 '336': 'TradingSessionID',
 '337': 'ContraTrader',
 '338': 'TradSesMethod',
 '339': 'TradSesMode',
 '34': 'MsgSeqNum',
 '340': 'TradSesStatus',
 '341': 'TradSesStartTime',
 '342': 'TradSesOpenTime',
 '343': 'TradSesPreCloseTime',
 '344': 'TradSesCloseTime',
 '345': 'TradSesEndTime',
 '346': 'NumberOfOrders',
 '347': 'MessageEncoding',
 '348': 'EncodedIssuerLen',
 '349': 'EncodedIssuer',
 '35': 'MsgType',
 '350': 'EncodedSecurityDescLen',
 '351': 'EncodedSecurityDesc',
 '352': 'EncodedListExecInstLen',
 '353': 'EncodedListExecInst',
 '354': 'EncodedTextLen',
 '355': 'EncodedText',
 '356': 'EncodedSubjectLen',
 '357': 'EncodedSubject',
 '358': 'EncodedHeadlineLen',
 '359': 'EncodedHeadline',
 '36': 'NewSeqNo',
 '360': 'EncodedAllocTextLen',
 '361': 'EncodedAllocText',
 '362': 'EncodedUnderlyingIssuerLen',
 '363': 'EncodedUnderlyingIssuer',
 '364': 'EncodedUnderlyingSecurityDescLen',
 '365': 'EncodedUnderlyingSecurityDesc',
 '366': 'AllocPrice',
 '367': 'QuoteSetValidUntilTime',
 '368': 'QuoteEntryRejectReason',
 '369': 'LastMsgSeqNumProcessed',
 '37': 'OrderID',
 '370': 'OnBehalfOfSendingTime(Deprecated)',
 '371': 'RefTagID',
 '372': 'RefMsgType',
 '373': 'SessionRejectReason',
 '374': 'BidRequestTransType',
 '375': 'ContraBroker',
 '376': 'ComplianceID',
 '377': 'SolicitedFlag',
 '378': 'ExecRestatementReason',
 '379': 'BusinessRejectRefID',
 '38': 'OrderQty',
 '380': 'BusinessRejectReason',
 '381': 'GrossTradeAmt',
 '382': 'NoContraBrokers',
 '383': 'MaxMessageSize',
 '384': 'NoMsgTypes',
 '385': 'MsgDirection',
 '386': 'NoTradingSessions',
 '387': 'TotalVolumeTraded',
 '388': 'DiscretionInst',
 '389': 'DiscretionOffset',
 '39': 'OrdStatus',
 '390': 'BidID',
 '391': 'ClientBidID',
 '392': 'ListName',
 '393': 'TotalNumSecurities',
 '394': 'BidType',
 '395': 'NumTickets',
 '396': 'SideValue1',
 '397': 'SideValue2',
 '398': 'NoBidDescriptors',
 '399': 'BidDescriptorType',
 '4': 'AdvSide',
 '40': 'OrdType',
 '400': 'BidDescriptor',
 '401': 'SideValueInd',
 '402': 'LiquidityPctLow',
 '403': 'LiquidityPctHigh',
 '404': 'LiquidityValue',
 '405': 'EFPTrackingError',
 '406': 'FairValue',
 '407': 'OutsideIndexPct',
 '408': 'ValueOfFutures',
 '409': 'LiquidityIndType',
 '41': 'OrigClOrdID',
 '410': 'WtAverageLiquidity',
 '411': 'ExchangeForPhysical',
 '412': 'OutMainCntryUIndex',
 '413': 'CrossPercent',
 '414': 'ProgRptReqs',
 '415': 'ProgPeriodInterval',
 '416': 'IncTaxInd',
 '417': 'NumBidders',
 '418': 'TradeType',
 '419': 'BasisPxType',
 '42': 'OrigTime',
 '420': 'NoBidComponents',
 '421': 'Country',
 '422': 'TotNoStrikes',
 '423': 'PriceType',
 '424': 'DayOrderQty',
 '425': 'DayCumQty',
 '426': 'DayAvgPx',
 '427': 'GTBookingInst',
 '428': 'NoStrikes',
 '429': 'ListStatusType',
 '43': 'PossDupFlag',
 '430': 'NetGrossInd',
 '431': 'ListOrderStatus',
 '432': 'ExpireDate',
 '433': 'ListExecInstType',
 '434': 'CxlRejResponseTo',
 '435': 'UnderlyingCouponRate',
 '436': 'UnderlyingContractMultiplier',
 '437': 'ContraTradeQty',
 '438': 'ContraTradeTime',
 '439': 'ClearingFirm(replaced)',
 '44': 'Price',
 '440': 'ClearingAccount(replaced)',
 '441': 'LiquidityNumSecurities',
 '442': 'MultiLegReportingType',
 '443': 'StrikeTime',
 '444': 'ListStatusText',
 '445': 'EncodedListStatusTextLen',
 '446': 'EncodedListStatusText',
 '447': 'PartyIDSource',
 '448': 'PartyID',
 '449': 'TotalVolumeTradedDate',
 '45': 'RefSeqNum',
 '451': 'NetChgPrevDay',
 '452': 'PartyRole',
 '453': 'NoPartyIDs',
 '454': 'NoSecurityAltID',
 '455': 'SecurityAltID',
 '456': 'SecurityAltIDSource',
 '457': 'NoUnderlyingSecurityAltID',
 '458': 'UnderlyingSecurityAltID',
 '459': 'UnderlyingSecurityAltIDSource',
 '460': 'Product',
 '461': 'CFICode',
 '462': 'UnderlyingProduct',
 '463': 'UnderlyingCFICode',
 '464': 'TestMessageIndicator',
 '465': 'QuantityType',
 '466': 'BookingRefID',
 '467': 'IndividualAllocID',
 '468': 'RoundingDirection',
 '469': 'RoundingModulus',
 '47': 'Rule80A(Deprecated)',
 '470': 'CountryOfIssue',
 '471': 'StateOrProvinceOfIssue',
 '472': 'LocaleOfIssue',
 '473': 'NoRegistDtls',
 '474': 'MailingDtls',
 '475': 'InvestorCountryOfResidence',
 '476': 'PaymentRef',
 '477': 'DistribPaymentMethod',
 '478': 'CashDistribCurr',
 '479': 'CommCurrency',
 '48': 'SecurityID',
 '480': 'CancellationRights',
 '481': 'MoneyLaunderingStatus',
 '482': 'MailingInst',
 '483': 'TransBkdTime',
 '484': 'ExecPriceType',
 '485': 'ExecPriceAdjustment',
 '486': 'DateOfBirth',
 '487': 'TradeReportTransType',
 '488': 'CardHolderName',
 '489': 'CardNumber',
 '49': 'SenderCompID',
 '490': 'CardExpDate',
 '491': 'CardIssNo',
 '492': 'PaymentMethod',
 '493': 'RegistAcctType',
 '494': 'Designation',
 '495': 'TaxAdvantageType',
 '496': 'RegistRejReasonText',
 '497': 'FundRenewWaiv',
 '498': 'CashDistribAgentName',
 '499': 'CashDistribAgentCode',
 '5': 'AdvTransType',
 '50': 'SenderSubID',
 '500': 'CashDistribAgentAcctNumber',
 '501': 'CashDistribPayRef',
 '502': 'CashDistribAgentAcctName',
 '503': 'CardStartDate',
 '504': 'PaymentDate',
 '505': 'PaymentRemitterID',
 '506': 'RegistStatus',
 '507': 'RegistRejReasonCode',
 '508': 'RegistRefID',
 '509': 'RegistDetls',
 '510': 'NoDistribInsts',
 '511': 'RegistEmail',
 '512': 'DistribPercentage',
 '513': 'RegistID',
 '514': 'RegistTransType',
 '515': 'ExecValuationPoint',
 '516': 'OrderPercent',
 '517': 'OwnershipType',
 '518': 'NoContAmts',
 '519': 'ContAmtType',
 '52': 'SendingTime',
 '520': 'ContAmtValue',
 '521': 'ContAmtCurr',
 '522': 'OwnerType',
 '523': 'PartySubID',
 '524': 'NestedPartyID',
 '525': 'NestedPartyIDSource',
 '526': 'SecondaryClOrdID',
 '527': 'SecondaryExecID',
 '528': 'OrderCapacity',
 '529': 'OrderRestrictions',
 '530': 'MassCancelRequestType',
 '531': 'MassCancelResponse',
 '532': 'MassCancelRejectReason',
 '533': 'TotalAffectedOrders',
 '534': 'NoAffectedOrders',
 '535': 'AffectedOrderID',
 '536': 'AffectedSecondaryOrderID',
 '537': 'QuoteType',
 '538': 'NestedPartyRole',
 '539': 'NoNestedPartyIDs',
 '54': 'Side',
 '540': 'TotalAccruedInterestAmt',
 '541': 'MaturityDate',
 '542': 'UnderlyingMaturityDate',
 '543': 'InstrRegistry',
 '544': 'CashMargin',
 '545': 'NestedPartySubID',
 '546': 'Scope',
 '547': 'MDImplicitDelete',
 '548': 'CrossID',
 '549': 'CrossType',
 '55': 'Symbol',
 '550': 'CrossPrioritization',
 '551': 'OrigCrossID',
 '552': 'NoSides',
 '553': 'Username',
 '554': 'Password',
 '555': 'NoLegs',
 '556': 'LegCurrency',
 '557': 'TotalNumSecurityTypes',
 '558': 'NoSecurityTypes',
 '559': 'SecurityListRequestType',
 '56': 'TargetCompID',
 '560': 'SecurityRequestResult',
 '561': 'RoundLot',
 '562': 'MinTradeVol',
 '563': 'MultiLegRptTypeReq',
 '564': 'LegPositionEffect',
 '565': 'LegCoveredOrUncovered',
 '566': 'LegPrice',
 '567': 'TradSesStatusRejReason',
 '568': 'TradeRequestID',
 '569': 'TradeRequestType',
 '57': 'TargetSubID',
 '570': 'PreviouslyReported',
 '571': 'TradeReportID',
 '572': 'TradeReportRefID',
 '573': 'MatchStatus',
 '574': 'MatchType',
 '575': 'OddLot',
 '576': 'NoClearingInstructions',
 '577': 'ClearingInstruction',
 '578': 'TradeInputSource',
 '579': 'TradeInputDevice',
 '58': 'Text',
 '580': 'NoDates',
 '581': 'AccountType',
 '582': 'CustOrderCapacity',
 '583': 'ClOrdLinkID',
 '584': 'MassStatusReqID',
 '585': 'MassStatusReqType',
 '586': 'OrigOrdModTime',
 '587': 'LegSettlmntTyp',
 '588': 'LegFutSettDate',
 '589': 'DayBookingInst',
 '59': 'TimeInForce',
 '590': 'BookingUnit',
 '591': 'PreallocMethod',
 '592': 'UnderlyingCountryOfIssue',
 '593': 'UnderlyingStateOrProvinceOfIssue',
 '594': 'UnderlyingLocaleOfIssue',
 '595': 'UnderlyingInstrRegistry',
 '596': 'LegCountryOfIssue',
 '597': 'LegStateOrProvinceOfIssue',
 '598': 'LegLocaleOfIssue',
 '599': 'LegInstrRegistry',
 '6': 'AvgPx',
 '60': 'TransactTime',
 '600': 'LegSymbol',
 '601': 'LegSymbolSfx',
 '602': 'LegSecurityID',
 '603': 'LegSecurityIDSource',
 '604': 'NoLegSecurityAltID',
 '605': 'LegSecurityAltID',
 '606': 'LegSecurityAltIDSource',
 '607': 'LegProduct',
 '608': 'LegCFICode',
 '609': 'LegSecurityType',
 '61': 'Urgency',
 '610': 'LegMaturityMonthYear',
 '611': 'LegMaturityDate',
 '612': 'LegStrikePrice',
 '613': 'LegOptAttribute',
 '614': 'LegContractMultiplier',
 '615': 'LegCouponRate',
 '616': 'LegSecurityExchange',
 '617': 'LegIssuer',
 '618': 'EncodedLegIssuerLen',
 '619': 'EncodedLegIssuer',
 '62': 'ValidUntilTime',
 '620': 'LegSecurityDesc',
 '621': 'EncodedLegSecurityDescLen',
 '622': 'EncodedLegSecurityDesc',
 '623': 'LegRatioQty',
 '624': 'LegSide',
 '625': 'TradingSessionSubID',
 '626': 'AllocType',
 '627': 'NoHops',
 '628': 'HopCompID',
 '629': 'HopSendingTime',
 '63': 'SettlmntTyp',
 '630': 'HopRefID',
 '631': 'MidPx',
 '632': 'BidYield',
 '633': 'MidYield',
 '634': 'OfferYield',
 '635': 'ClearingFeeIndicator',
 '636': 'WorkingIndicator',
 '637': 'LegLastPx',
 '638': 'PriorityIndicator',
 '639': 'PriceImprovement',
 '64': 'FutSettDate',
 '640': 'Price2',
 '641': 'LastForwardPoints2',
 '642': 'BidForwardPoints2',
 '643': 'OfferForwardPoints2',
 '644': 'RFQReqID',
 '645': 'MktBidPx',
 '646': 'MktOfferPx',
 '647': 'MinBidSize',
 '648': 'MinOfferSize',
 '649': 'QuoteStatusReqID',
 '65': 'SymbolSfx',
 '650': 'LegalConfirm',
 '651': 'UnderlyingLastPx',
 '652': 'UnderlyingLastQty',
 '653': 'SecDefStatus',
 '654': 'LegRefID',
 '655': 'ContraLegRefID',
 '656': 'SettlCurrBidFxRate',
 '657': 'SettlCurrOfferFxRate',
 '658': 'QuoteRequestRejectReason',
 '659': 'SideComplianceID',
 '66': 'ListID',
 '67': 'ListSeqNo',
 '69': 'ListExecInst',
 '7': 'BeginSeqNo',
 '70': 'AllocID',
 '71': 'AllocTransType',
 '72': 'RefAllocID',
 '73': 'NoOrders',
 '74': 'AvgPrxPrecision',
 '75': 'TradeDate',
 '76': 'ExecBroker(replaced)',
 '78': 'NoAllocs',
 '79': 'AllocAccount',
 '8': 'BeginString',
 '81': 'ProcessCode',
 '82': 'NoRpts',
 '83': 'RptSeq',
 '84': 'CxlQty',
 '87': 'AllocStatus',
 '88': 'AllocRejCode',
 '89': 'Signature',
 '9': 'BodyLength',
 '90': 'SecureDataLen',
 '91': 'SecureData',
 '92': 'BrokerOfCredit(replaced)',
 '93': 'SignatureLength',
 '94': 'EmailType',
 '95': 'RawDataLength',
 '96': 'RawData',
 '97': 'PossResend',
 '98': 'EncryptMethod',
 '99': 'StopPx'}
tag_by_field =  {'Account': '1',
 'AccountType': '581',
 'AccruedInterestAmt': '159',
 'AccruedInterestRate': '158',
 'Adjustment': '334',
 'AdvId': '2',
 'AdvRefID': '3',
 'AdvSide': '4',
 'AdvTransType': '5',
 'AffectedOrderID': '535',
 'AffectedSecondaryOrderID': '536',
 'AggregatedBook': '266',
 'AllocAccount': '79',
 'AllocAvgPx': '153',
 'AllocHandlInst': '209',
 'AllocID': '70',
 'AllocLinkID': '196',
 'AllocLinkType': '197',
 'AllocNetMoney': '154',
 'AllocPrice': '366',
 'AllocRejCode': '88',
 'AllocStatus': '87',
 'AllocText': '161',
 'AllocTransType': '71',
 'AllocType': '626',
 'AvgPrxPrecision': '74',
 'AvgPx': '6',
 'BasisFeatureDate': '259',
 'BasisFeaturePrice': '260',
 'BasisPxType': '419',
 'BeginSeqNo': '7',
 'BeginString': '8',
 'Benchmark(Deprecated)': '219',
 'BenchmarkCurveCurrency': '220',
 'BenchmarkCurveName': '221',
 'BenchmarkCurvePoint': '222',
 'BidDescriptor': '400',
 'BidDescriptorType': '399',
 'BidForwardPoints': '189',
 'BidForwardPoints2': '642',
 'BidID': '390',
 'BidPx': '132',
 'BidRequestTransType': '374',
 'BidSize': '134',
 'BidSpotRate': '188',
 'BidType': '394',
 'BidYield': '632',
 'BodyLength': '9',
 'BookingRefID': '466',
 'BookingUnit': '590',
 'BrokerOfCredit(replaced)': '92',
 'BusinessRejectReason': '380',
 'BusinessRejectRefID': '379',
 'BuyVolume': '330',
 'CFICode': '461',
 'CancellationRights': '480',
 'CardExpDate': '490',
 'CardHolderName': '488',
 'CardIssNo': '491',
 'CardNumber': '489',
 'CardStartDate': '503',
 'CashDistribAgentAcctName': '502',
 'CashDistribAgentAcctNumber': '500',
 'CashDistribAgentCode': '499',
 'CashDistribAgentName': '498',
 'CashDistribCurr': '478',
 'CashDistribPayRef': '501',
 'CashMargin': '544',
 'CashOrderQty': '152',
 'CashSettlAgentAcctName': '185',
 'CashSettlAgentAcctNum': '184',
 'CashSettlAgentCode': '183',
 'CashSettlAgentContactName': '186',
 'CashSettlAgentContactPhone': '187',
 'CashSettlAgentName': '182',
 'CheckSum': '10',
 'ClOrdID': '11',
 'ClOrdLinkID': '583',
 'ClearingAccount(replaced)': '440',
 'ClearingFeeIndicator': '635',
 'ClearingFirm(replaced)': '439',
 'ClearingInstruction': '577',
 'ClientBidID': '391',
 'ClientID(replaced)': '109',
 'CommCurrency': '479',
 'CommType': '13',
 'Commission': '12',
 'ComplianceID': '376',
 'Concession': '238',
 'ContAmtCurr': '521',
 'ContAmtType': '519',
 'ContAmtValue': '520',
 'ContraBroker': '375',
 'ContraLegRefID': '655',
 'ContraTradeQty': '437',
 'ContraTradeTime': '438',
 'ContraTrader': '337',
 'ContractMultiplier': '231',
 'CorporateAction': '292',
 'Country': '421',
 'CountryOfIssue': '470',
 'CouponPaymentDate': '224',
 'CouponRate': '223',
 'CoveredOrUncovered': '203',
 'CreditRating': '255',
 'CrossID': '548',
 'CrossPercent': '413',
 'CrossPrioritization': '550',
 'CrossType': '549',
 'CumQty': '14',
 'Currency': '15',
 'CustOrderCapacity': '582',
 'CustomerOrFirm(replaced)': '204',
 'CxlQty': '84',
 'CxlRejReason': '102',
 'CxlRejResponseTo': '434',
 'DKReason': '127',
 'DateOfBirth': '486',
 'DayAvgPx': '426',
 'DayBookingInst': '589',
 'DayCumQty': '425',
 'DayOrderQty': '424',
 'DefBidSize': '293',
 'DefOfferSize': '294',
 'DeleteReason': '285',
 'DeliverToCompID': '128',
 'DeliverToLocationID': '145',
 'DeliverToSubID': '129',
 'Designation': '494',
 'DeskID': '284',
 'DiscretionInst': '388',
 'DiscretionOffset': '389',
 'DistribPaymentMethod': '477',
 'DistribPercentage': '512',
 'DueToRelated': '329',
 'EFPTrackingError': '405',
 'EffectiveTime': '168',
 'EmailThreadID': '164',
 'EmailType': '94',
 'EncodedAllocText': '361',
 'EncodedAllocTextLen': '360',
 'EncodedHeadline': '359',
 'EncodedHeadlineLen': '358',
 'EncodedIssuer': '349',
 'EncodedIssuerLen': '348',
 'EncodedLegIssuer': '619',
 'EncodedLegIssuerLen': '618',
 'EncodedLegSecurityDesc': '622',
 'EncodedLegSecurityDescLen': '621',
 'EncodedListExecInst': '353',
 'EncodedListExecInstLen': '352',
 'EncodedListStatusText': '446',
 'EncodedListStatusTextLen': '445',
 'EncodedSecurityDesc': '351',
 'EncodedSecurityDescLen': '350',
 'EncodedSubject': '357',
 'EncodedSubjectLen': '356',
 'EncodedText': '355',
 'EncodedTextLen': '354',
 'EncodedUnderlyingIssuer': '363',
 'EncodedUnderlyingIssuerLen': '362',
 'EncodedUnderlyingSecurityDesc': '365',
 'EncodedUnderlyingSecurityDescLen': '364',
 'EncryptMethod': '98',
 'EndSeqNo': '16',
 'ExDate': '230',
 'ExDestination': '100',
 'ExchangeForPhysical': '411',
 'ExecBroker(replaced)': '76',
 'ExecID': '17',
 'ExecInst': '18',
 'ExecPriceAdjustment': '485',
 'ExecPriceType': '484',
 'ExecRefID': '19',
 'ExecRestatementReason': '378',
 'ExecTransType(replaced)': '20',
 'ExecType': '150',
 'ExecValuationPoint': '515',
 'ExpireDate': '432',
 'ExpireTime': '126',
 'Factor': '228',
 'FairValue': '406',
 'FinancialStatus': '291',
 'ForexReq': '121',
 'FundRenewWaiv': '497',
 'FutSettDate': '64',
 'FutSettDate2': '193',
 'GTBookingInst': '427',
 'GapFillFlag': '123',
 'GrossTradeAmt': '381',
 'HaltReason': '327',
 'HandlInst': '21',
 'Headline': '148',
 'HeartBtInt': '108',
 'HighPx': '332',
 'HopCompID': '628',
 'HopRefID': '630',
 'HopSendingTime': '629',
 'IOINaturalFlag': '130',
 'IOIQltyInd': '25',
 'IOIQualifier': '104',
 'IOIRefID': '26',
 'IOITransType': '28',
 'IOIid': '23',
 'InViewOfCommon': '328',
 'IncTaxInd': '416',
 'IndividualAllocID': '467',
 'InstrRegistry': '543',
 'InvestorCountryOfResidence': '475',
 'IssueDate': '225',
 'Issuer': '106',
 'LastCapacity': '29',
 'LastForwardPoints': '195',
 'LastForwardPoints2': '641',
 'LastMkt': '30',
 'LastMsgSeqNumProcessed': '369',
 'LastPx': '31',
 'LastSpotRate': '194',
 'LeavesQty': '151',
 'LegCFICode': '608',
 'LegContractMultiplier': '614',
 'LegCountryOfIssue': '596',
 'LegCouponPaymentDate': '248',
 'LegCouponRate': '615',
 'LegCoveredOrUncovered': '565',
 'LegCreditRating': '257',
 'LegCurrency': '556',
 'LegFactor': '253',
 'LegFutSettDate': '588',
 'LegInstrRegistry': '599',
 'LegIssueDate': '249',
 'LegIssuer': '617',
 'LegLastPx': '637',
 'LegLocaleOfIssue': '598',
 'LegMaturityDate': '611',
 'LegMaturityMonthYear': '610',
 'LegOptAttribute': '613',
 'LegPositionEffect': '564',
 'LegPrice': '566',
 'LegProduct': '607',
 'LegRatioQty': '623',
 'LegRedemptionDate': '254',
 'LegRefID': '654',
 'LegRepoCollateralSecurityType': '250',
 'LegRepurchaseRate': '252',
 'LegRepurchaseTerm': '251',
 'LegSecurityAltID': '605',
 'LegSecurityAltIDSource': '606',
 'LegSecurityDesc': '620',
 'LegSecurityExchange': '616',
 'LegSecurityID': '602',
 'LegSecurityIDSource': '603',
 'LegSecurityType': '609',
 'LegSettlmntTyp': '587',
 'LegSide': '624',
 'LegStateOrProvinceOfIssue': '597',
 'LegStrikePrice': '612',
 'LegSymbol': '600',
 'LegSymbolSfx': '601',
 'LegalConfirm': '650',
 'LinesOfText': '33',
 'LiquidityIndType': '409',
 'LiquidityNumSecurities': '441',
 'LiquidityPctHigh': '403',
 'LiquidityPctLow': '402',
 'LiquidityValue': '404',
 'ListExecInst': '69',
 'ListExecInstType': '433',
 'ListID': '66',
 'ListName': '392',
 'ListOrderStatus': '431',
 'ListSeqNo': '67',
 'ListStatusText': '444',
 'ListStatusType': '429',
 'LocaleOfIssue': '472',
 'LocateReqd': '114',
 'LocationID': '283',
 'LowPx': '333',
 'MDEntryBuyer': '288',
 'MDEntryDate': '272',
 'MDEntryID': '278',
 'MDEntryOriginator': '282',
 'MDEntryPositionNo': '290',
 'MDEntryPx': '270',
 'MDEntryRefID': '280',
 'MDEntrySeller': '289',
 'MDEntrySize': '271',
 'MDEntryTime': '273',
 'MDEntryType': '269',
 'MDImplicitDelete': '547',
 'MDMkt': '275',
 'MDReqID': '262',
 'MDReqRejReason': '281',
 'MDUpdateAction': '279',
 'MDUpdateType': '265',
 'MailingDtls': '474',
 'MailingInst': '482',
 'MarketDepth': '264',
 'MassCancelRejectReason': '532',
 'MassCancelRequestType': '530',
 'MassCancelResponse': '531',
 'MassStatusReqID': '584',
 'MassStatusReqType': '585',
 'MatchStatus': '573',
 'MatchType': '574',
 'MaturityDate': '541',
 'MaturityDay(replaced)': '205',
 'MaturityMonthYear': '200',
 'MaxFloor': '111',
 'MaxMessageSize': '383',
 'MaxShow': '210',
 'MessageEncoding': '347',
 'MidPx': '631',
 'MidYield': '633',
 'MinBidSize': '647',
 'MinOfferSize': '648',
 'MinQty': '110',
 'MinTradeVol': '562',
 'MiscFeeAmt': '137',
 'MiscFeeCurr': '138',
 'MiscFeeType': '139',
 'MktBidPx': '645',
 'MktOfferPx': '646',
 'MoneyLaunderingStatus': '481',
 'MsgDirection': '385',
 'MsgSeqNum': '34',
 'MsgType': '35',
 'MultiLegReportingType': '442',
 'MultiLegRptTypeReq': '563',
 'NestedPartyID': '524',
 'NestedPartyIDSource': '525',
 'NestedPartyRole': '538',
 'NestedPartySubID': '545',
 'NetChgPrevDay': '451',
 'NetGrossInd': '430',
 'NetMoney': '118',
 'NewSeqNo': '36',
 'NoAffectedOrders': '534',
 'NoAllocs': '78',
 'NoBidComponents': '420',
 'NoBidDescriptors': '398',
 'NoClearingInstructions': '576',
 'NoContAmts': '518',
 'NoContraBrokers': '382',
 'NoDates': '580',
 'NoDistribInsts': '510',
 'NoExecs': '124',
 'NoHops': '627',
 'NoIOIQualifiers': '199',
 'NoLegSecurityAltID': '604',
 'NoLegs': '555',
 'NoMDEntries': '268',
 'NoMDEntryTypes': '267',
 'NoMiscFees': '136',
 'NoMsgTypes': '384',
 'NoNestedPartyIDs': '539',
 'NoOrders': '73',
 'NoPartyIDs': '453',
 'NoQuoteEntries': '295',
 'NoQuoteSets': '296',
 'NoRegistDtls': '473',
 'NoRelatedSym': '146',
 'NoRoutingIDs': '215',
 'NoRpts': '82',
 'NoSecurityAltID': '454',
 'NoSecurityTypes': '558',
 'NoSides': '552',
 'NoStipulations': '232',
 'NoStrikes': '428',
 'NoTradingSessions': '386',
 'NoUnderlyingSecurityAltID': '457',
 'NotifyBrokerOfCredit': '208',
 'NumBidders': '417',
 'NumDaysInterest': '157',
 'NumTickets': '395',
 'NumberOfOrders': '346',
 'OddLot': '575',
 'OfferForwardPoints': '191',
 'OfferForwardPoints2': '643',
 'OfferPx': '133',
 'OfferSize': '135',
 'OfferSpotRate': '190',
 'OfferYield': '634',
 'OnBehalfOfCompID': '115',
 'OnBehalfOfLocationID': '144',
 'OnBehalfOfSendingTime(Deprecated)': '370',
 'OnBehalfOfSubID': '116',
 'OpenCloseSettleFlag': '286',
 'OptAttribute': '206',
 'OrdRejReason': '103',
 'OrdStatus': '39',
 'OrdType': '40',
 'OrderCapacity': '528',
 'OrderID': '37',
 'OrderPercent': '516',
 'OrderQty': '38',
 'OrderQty2': '192',
 'OrderRestrictions': '529',
 'OrigClOrdID': '41',
 'OrigCrossID': '551',
 'OrigOrdModTime': '586',
 'OrigSendingTime': '122',
 'OrigTime': '42',
 'OutMainCntryUIndex': '412',
 'OutsideIndexPct': '407',
 'OwnerType': '522',
 'OwnershipType': '517',
 'PartyID': '448',
 'PartyIDSource': '447',
 'PartyRole': '452',
 'PartySubID': '523',
 'Password': '554',
 'PaymentDate': '504',
 'PaymentMethod': '492',
 'PaymentRef': '476',
 'PaymentRemitterID': '505',
 'PegDifference': '211',
 'PossDupFlag': '43',
 'PossResend': '97',
 'PreallocMethod': '591',
 'PrevClosePx': '140',
 'PreviouslyReported': '570',
 'Price': '44',
 'Price2': '640',
 'PriceImprovement': '639',
 'PriceType': '423',
 'PriorityIndicator': '638',
 'ProcessCode': '81',
 'Product': '460',
 'ProgPeriodInterval': '415',
 'ProgRptReqs': '414',
 'PutOrCall(replaced)': '201',
 'QuantityType': '465',
 'QuoteCancelType': '298',
 'QuoteCondition': '276',
 'QuoteEntryID': '299',
 'QuoteEntryRejectReason': '368',
 'QuoteID': '117',
 'QuoteRejectReason': '300',
 'QuoteReqID': '131',
 'QuoteRequestRejectReason': '658',
 'QuoteRequestType': '303',
 'QuoteResponseLevel': '301',
 'QuoteSetID': '302',
 'QuoteSetValidUntilTime': '367',
 'QuoteStatusReqID': '649',
 'QuoteType': '537',
 'RFQReqID': '644',
 'RatioQty': '319',
 'RawData': '96',
 'RawDataLength': '95',
 'RedemptionDate': '240',
 'RefAllocID': '72',
 'RefMsgType': '372',
 'RefSeqNum': '45',
 'RefTagID': '371',
 'RegistAcctType': '493',
 'RegistDetls': '509',
 'RegistEmail': '511',
 'RegistID': '513',
 'RegistRefID': '508',
 'RegistRejReasonCode': '507',
 'RegistRejReasonText': '496',
 'RegistStatus': '506',
 'RegistTransType': '514',
 'RepoCollateralSecurityType': '239',
 'ReportToExch': '113',
 'RepurchaseRate': '227',
 'RepurchaseTerm': '226',
 'ResetSeqNumFlag': '141',
 'RoundLot': '561',
 'RoundingDirection': '468',
 'RoundingModulus': '469',
 'RoutingID': '217',
 'RoutingType': '216',
 'RptSeq': '83',
 'Rule80A(Deprecated)': '47',
 'Scope': '546',
 'SecDefStatus': '653',
 'SecondaryClOrdID': '526',
 'SecondaryExecID': '527',
 'SecondaryOrderID': '198',
 'SecureData': '91',
 'SecureDataLen': '90',
 'SecurityAltID': '455',
 'SecurityAltIDSource': '456',
 'SecurityDesc': '107',
 'SecurityExchange': '207',
 'SecurityID': '48',
 'SecurityListRequestType': '559',
 'SecurityReqID': '320',
 'SecurityRequestResult': '560',
 'SecurityRequestType': '321',
 'SecurityResponseID': '322',
 'SecurityResponseType': '323',
 'SecuritySettlAgentAcctName': '179',
 'SecuritySettlAgentAcctNum': '178',
 'SecuritySettlAgentCode': '177',
 'SecuritySettlAgentContactName': '180',
 'SecuritySettlAgentContactPhone': '181',
 'SecuritySettlAgentName': '176',
 'SecurityStatusReqID': '324',
 'SecurityTradingStatus': '326',
 'SecurityType': '167',
 'SellVolume': '331',
 'SellerDays': '287',
 'SenderCompID': '49',
 'SenderLocationID': '142',
 'SenderSubID': '50',
 'SendingTime': '52',
 'SessionRejectReason': '373',
 'SettlBrkrCode': '174',
 'SettlCurrAmt': '119',
 'SettlCurrBidFxRate': '656',
 'SettlCurrFxRate': '155',
 'SettlCurrFxRateCalc': '156',
 'SettlCurrOfferFxRate': '657',
 'SettlCurrency': '120',
 'SettlDeliveryType': '172',
 'SettlDepositoryCode': '173',
 'SettlInstCode': '175',
 'SettlInstID': '162',
 'SettlInstMode': '160',
 'SettlInstRefID': '214',
 'SettlInstSource': '165',
 'SettlInstTransType': '163',
 'SettlLocation(replaced)': '166',
 'SettlmntTyp': '63',
 'Side': '54',
 'SideComplianceID': '659',
 'SideValue1': '396',
 'SideValue2': '397',
 'SideValueInd': '401',
 'Signature': '89',
 'SignatureLength': '93',
 'SolicitedFlag': '377',
 'StandInstDbID': '171',
 'StandInstDbName': '170',
 'StandInstDbType': '169',
 'StateOrProvinceOfIssue': '471',
 'StipulationType': '233',
 'StipulationValue': '234',
 'StopPx': '99',
 'StrikePrice': '202',
 'StrikeTime': '443',
 'Subject': '147',
 'SubscriptionRequestType': '263',
 'Symbol': '55',
 'SymbolSfx': '65',
 'TargetCompID': '56',
 'TargetLocationID': '143',
 'TargetSubID': '57',
 'TaxAdvantageType': '495',
 'TestMessageIndicator': '464',
 'TestReqID': '112',
 'Text': '58',
 'TickDirection': '274',
 'TimeInForce': '59',
 'TotNoStrikes': '422',
 'TotQuoteEntries': '304',
 'TotalAccruedInterestAmt': '540',
 'TotalAffectedOrders': '533',
 'TotalNumSecurities': '393',
 'TotalNumSecurityTypes': '557',
 'TotalTakedown': '237',
 'TotalVolumeTraded': '387',
 'TotalVolumeTradedDate': '449',
 'TradSesCloseTime': '344',
 'TradSesEndTime': '345',
 'TradSesMethod': '338',
 'TradSesMode': '339',
 'TradSesOpenTime': '342',
 'TradSesPreCloseTime': '343',
 'TradSesReqID': '335',
 'TradSesStartTime': '341',
 'TradSesStatus': '340',
 'TradSesStatusRejReason': '567',
 'TradeCondition': '277',
 'TradeDate': '75',
 'TradeInputDevice': '579',
 'TradeInputSource': '578',
 'TradeOriginationDate': '229',
 'TradeReportID': '571',
 'TradeReportRefID': '572',
 'TradeReportTransType': '487',
 'TradeRequestID': '568',
 'TradeRequestType': '569',
 'TradeType': '418',
 'TradedFlatSwitch': '258',
 'TradingSessionID': '336',
 'TradingSessionSubID': '625',
 'TransBkdTime': '483',
 'TransactTime': '60',
 'URLLink': '149',
 'UnderlyingCFICode': '463',
 'UnderlyingContractMultiplier': '436',
 'UnderlyingCountryOfIssue': '592',
 'UnderlyingCouponPaymentDate': '241',
 'UnderlyingCouponRate': '435',
 'UnderlyingCreditRating': '256',
 'UnderlyingFactor': '246',
 'UnderlyingInstrRegistry': '595',
 'UnderlyingIssueDate': '242',
 'UnderlyingIssuer': '306',
 'UnderlyingLastPx': '651',
 'UnderlyingLastQty': '652',
 'UnderlyingLocaleOfIssue': '594',
 'UnderlyingMaturityDate': '542',
 'UnderlyingMaturityDay(replaced)': '314',
 'UnderlyingMaturityMonthYear': '313',
 'UnderlyingOptAttribute': '317',
 'UnderlyingProduct': '462',
 'UnderlyingPutOrCall(replaced)': '315',
 'UnderlyingRedemptionDate': '247',
 'UnderlyingRepoCollateralSecurityType': '243',
 'UnderlyingRepurchaseRate': '245',
 'UnderlyingRepurchaseTerm': '244',
 'UnderlyingSecurityAltID': '458',
 'UnderlyingSecurityAltIDSource': '459',
 'UnderlyingSecurityDesc': '307',
 'UnderlyingSecurityExchange': '308',
 'UnderlyingSecurityID': '309',
 'UnderlyingSecurityType': '310',
 'UnderlyingStateOrProvinceOfIssue': '593',
 'UnderlyingStrikePrice': '316',
 'UnderlyingSymbol': '311',
 'UnderlyingSymbolSfx': '312',
 'UnsolicitedIndicator': '325',
 'Urgency': '61',
 'Username': '553',
 'ValidUntilTime': '62',
 'ValueOfFutures': '408',
 'WaveNo': '105',
 'WorkingIndicator': '636',
 'WtAverageLiquidity': '410',
 'XmlData': '213',
 'XmlDataLen': '212',
 'Yield': '236',
 'YieldType': '235'}
desc_by_tag_value =  {'1': {},
 '10': {},
 '100': {},
 '102': {'0': 'Too late to cancel',
         '1': 'Unknown order',
         '2': 'Broker / Exchange Option',
         '3': 'Order already in Pending Cancel or Pending Replace status',
         '4': 'Unable to process ',
         '5': 'OrigOrdModTime <586>',
         '6': 'Duplicate '},
 '103': {'0': 'Broker / Exchange option',
         '1': 'Unknown symbol',
         '10': 'Invalid Investor ID',
         '11': 'Unsupported order characteristic',
         '12': 'Surveillence Option',
         '2': 'Exchange closed',
         '3': 'Order exceeds limit',
         '4': 'Too late to enter',
         '5': 'Unknown Order',
         '6': 'Duplicate Order (e.g. dupe ',
         '7': 'Duplicate of a verbally communicated order',
         '8': 'Stale Order',
         '9': 'Trade Along required'},
 '104': {'A': 'All or none',
         'B': 'Market On Close (MOC) (held to close)',
         'C': 'At the close (around/not held to close)',
         'D': 'VWAP (Volume Weighted Avg ',
         'I': 'In touch with',
         'L': 'Limit',
         'M': 'More behind',
         'O': 'At the open',
         'P': 'Taking a position',
         'Q': 'At the Market (previously called Current ',
         'R': 'Ready to trade',
         'S': 'Portfolio shown',
         'T': 'Through the day',
         'V': 'Versus',
         'W': 'Indication - Working away',
         'X': 'Crossing opportunity',
         'Y': 'At the Midpoint',
         'Z': 'Pre-open'},
 '105': {},
 '106': {},
 '107': {},
 '108': {},
 '109': {},
 '11': {},
 '110': {},
 '111': {},
 '112': {},
 '113': {'N': 'Indicates that party sending message will report trade',
         'Y': 'Indicates that party receiving message must report trade'},
 '114': {'N': 'Indicates the broker is not required to locate',
         'Y': 'Indicates the broker is responsible for locating the stock'},
 '115': {},
 '116': {},
 '117': {},
 '118': {},
 '119': {},
 '12': {},
 '120': {},
 '121': {'N': 'Do not execute Forex after security trade',
         'Y': 'Execute Forex after security trade'},
 '122': {},
 '123': {'N': 'Sequence Reset <4>', 'Y': 'Gap Fill message, '},
 '124': {},
 '126': {},
 '127': {'A': 'Unknown symbol',
         'B': 'Wrong side',
         'C': 'Quantity exceeds order',
         'D': 'No matching order',
         'E': 'Price <44>',
         'Z': 'Other'},
 '128': {},
 '129': {},
 '13': {'1': 'per share',
        '2': 'percentage',
        '3': 'absolute',
        '4': '(for CIV buy orders) percentage waived - cash discount',
        '5': '(for CIV buy orders) percentage waived - enhanced units',
        '6': 'per bond'},
 '130': {'N': 'Not natural', 'Y': 'Natural'},
 '131': {},
 '132': {},
 '133': {},
 '134': {},
 '135': {},
 '136': {},
 '137': {},
 '138': {},
 '139': {'1': 'Regulatory (e.g. SEC)',
         '2': 'Tax',
         '3': 'Local ',
         '4': 'Exchange Fees',
         '5': 'Stamp',
         '6': 'Levy',
         '7': 'Other',
         '8': 'Markup',
         '9': 'Consumption Tax'},
 '14': {},
 '140': {},
 '141': {'N': 'No', 'Y': 'Yes, reset sequence numbers'},
 '142': {},
 '143': {},
 '144': {},
 '145': {},
 '146': {},
 '147': {},
 '148': {},
 '149': {},
 '15': {},
 '150': {'0': 'New',
         '3': 'Done for day',
         '4': 'Canceled',
         '5': 'Replace',
         '6': 'Pending Cancel (e.g. result of ',
         '7': 'Stopped',
         '8': 'Rejected',
         '9': 'Suspended',
         'A': 'Pending New',
         'B': 'Calculated',
         'C': 'Expired',
         'D': 'Restated (ExecutionRpt sent unsolicited by sellside, with ',
         'E': 'Pending Replace (e.g. result of ',
         'F': 'Trade (partial fill or fill)',
         'G': 'Trade Correct (formerly an ',
         'H': 'Trade Cancel (formerly an ',
         'I': 'Order Status (formerly an '},
 '151': {},
 '152': {},
 '153': {},
 '154': {},
 '155': {},
 '156': {},
 '157': {},
 '158': {},
 '159': {},
 '16': {},
 '160': {'0': 'Default',
         '1': 'Standing Instructions Provided',
         '2': 'Specific ',
         '3': 'Specific ',
         '4': 'Specific Order for a single account (for CIV)'},
 '161': {},
 '162': {},
 '163': {'C': 'Cancel', 'N': 'New', 'R': 'Replace'},
 '164': {},
 '165': {'1': "Broker's Instructions",
         '2': "Institution's Instructions",
         '3': 'Investor (e.g. CIV use)'},
 '166': {'CED': 'CEDEL',
         'DTC': 'Depository Trust Company',
         'EUR': 'Euroclear',
         'FED': 'Federal Book Entry',
         'PTC': 'Participant Trust Company'},
 '167': {},
 '168': {},
 '169': {'0': 'Other',
         '1': 'DTC SID',
         '2': 'Thomson ALERT',
         '3': 'A Global Custodian ('},
 '17': {},
 '170': {},
 '171': {},
 '172': {},
 '173': {},
 '174': {},
 '175': {},
 '176': {},
 '177': {},
 '178': {},
 '179': {},
 '18': {},
 '180': {},
 '181': {},
 '182': {},
 '183': {},
 '184': {},
 '185': {},
 '186': {},
 '187': {},
 '188': {},
 '189': {},
 '19': {},
 '190': {},
 '191': {},
 '192': {},
 '193': {},
 '194': {},
 '195': {},
 '196': {},
 '197': {'0': 'F/X Netting', '1': 'F/X Swap'},
 '198': {},
 '199': {},
 '2': {},
 '20': {'0': 'New', '1': 'Cancel', '2': 'Correct', '3': 'Status'},
 '200': {},
 '201': {'0': 'Put', '1': 'Call'},
 '202': {},
 '203': {'0': 'Covered', '1': 'Uncovered'},
 '204': {'0': 'Customer', '1': 'Firm'},
 '205': {},
 '206': {},
 '207': {},
 '208': {'N': 'Details should not be communicated',
         'Y': 'Details should be communicated'},
 '209': {'1': 'Match', '2': 'Forward', '3': 'Forward and Match'},
 '21': {'1': 'Automated execution order, private, no Broker intervention',
        '2': 'Automated execution order, public, Broker intervention OK',
        '3': 'Manual order, best execution'},
 '210': {},
 '211': {},
 '212': {},
 '213': {},
 '214': {},
 '215': {},
 '216': {'1': 'Target Firm',
         '2': 'Target List',
         '3': 'Block Firm',
         '4': 'Block List'},
 '217': {},
 '219': {'1': 'CURVE',
         '2': '5-YR',
         '3': 'OLD-5',
         '4': '10-YR',
         '5': 'OLD-10',
         '6': '30-YR',
         '7': 'OLD-30',
         '8': '3-MO-LIBOR',
         '9': '6-MO-LIBOR'},
 '220': {},
 '221': {},
 '222': {},
 '223': {},
 '224': {},
 '225': {},
 '226': {},
 '227': {},
 '228': {},
 '229': {},
 '23': {},
 '230': {},
 '231': {},
 '232': {},
 '233': {},
 '234': {},
 '235': {'AFTERTAX': 'After Tax ',
         'ANNUAL': 'Annual ',
         'ATISSUE': 'Yield <236>',
         'AVGLIFE': 'Yield <236>',
         'AVGMATURITY': 'Yield <236>',
         'BOOK': 'Book ',
         'CALL': 'Yield <236>',
         'CHANGE': 'Yield <236>',
         'CLOSE': 'Closing ',
         'COMPOUND': 'Compound ',
         'CURRENT': 'Current ',
         'GOVTEQUIV': 'Government Equivalent ',
         'GROSS': 'True Gross ',
         'INFLATION': 'Yield <236>',
         'INVERSEFLOATER': 'Inverse Floater Bond ',
         'LASTCLOSE': 'Most Recent Closing ',
         'LASTMONTH': 'Closing ',
         'LASTQUARTER': 'Closing ',
         'LASTYEAR': 'Closing ',
         'LONGAVGLIFE': 'Yield <236>',
         'LONGEST': 'Yield <236>',
         'MARK': 'Mark To Market ',
         'MATURITY': 'Yield <236>',
         'NEXTREFUND': 'Yield <236>',
         'OPENAVG': 'Open Average ',
         'PREVCLOSE': 'Previous Close ',
         'PROCEEDS': 'Proceeds ',
         'PUT': 'Yield <236>',
         'SEMIANNUAL': 'Semi-annual ',
         'SHORTAVGLIFE': 'Yield <236>',
         'SHORTEST': 'Yield <236>',
         'SIMPLE': 'Simple ',
         'TAXEQUIV': 'Tax Equivalent ',
         'TENDER': 'Yield <236>',
         'TRUE': 'True ',
         'VALUE1/32': 'Yield <236>',
         'WORST': 'Yield <236>'},
 '236': {},
 '237': {},
 '238': {},
 '239': {},
 '240': {},
 '241': {},
 '242': {},
 '243': {},
 '244': {},
 '245': {},
 '246': {},
 '247': {},
 '248': {},
 '249': {},
 '25': {'H': 'High', 'L': 'Low', 'M': 'Medium'},
 '250': {},
 '251': {},
 '252': {},
 '253': {},
 '254': {},
 '255': {},
 '256': {},
 '257': {},
 '258': {'N': 'Not Traded Flat', 'Y': 'Traded Flat'},
 '259': {},
 '26': {},
 '260': {},
 '262': {},
 '263': {'0': 'Snapshot',
         '1': 'Snapshot + Updates (Subscribe)',
         '2': 'Disable previous Snapshot + Update Request (Unsubscribe)'},
 '264': {'0': 'Full Book',
         '1': 'Top of Book',
         'N>1': 'Report best N price tiers of data'},
 '265': {'0': 'Full Refresh', '1': 'Incremental Refresh'},
 '266': {'N': 'Multiple entries per side per price allowed',
         'Y': 'one book entry per side per price'},
 '267': {},
 '268': {},
 '269': {'0': 'Bid',
         '1': 'Offer',
         '2': 'Trade',
         '3': 'Index Value',
         '4': 'Opening ',
         '5': 'Closing ',
         '6': 'Settlement ',
         '7': 'Trading Session High ',
         '8': 'Trading Session Low ',
         '9': 'Trading Session VWAP ',
         'A': 'Imbalance'},
 '270': {},
 '271': {},
 '272': {},
 '273': {},
 '274': {'0': 'Plus Tick',
         '1': 'Zero-Plus Tick',
         '2': 'Minus Tick',
         '3': 'Zero-Minus Tick'},
 '275': {},
 '276': {'A': 'Open / Active',
         'B': 'Closed / Inactive',
         'C': 'Exchange Best',
         'D': 'Consolidated Best',
         'E': 'Locked',
         'F': 'Crossed',
         'G': 'Depth',
         'H': 'Fast Trading',
         'I': 'Non-Firm'},
 '277': {'A': 'Cash (only) Market',
         'B': 'Average ',
         'C': 'Cash Trade (same day clearing)',
         'D': 'Next Day (only) Market',
         'E': 'Opening / Reopening Trade Detail',
         'F': 'Intraday Trade Detail',
         'G': 'Rule 127 Trade (NYSE)',
         'H': 'Rule 155 Trade (Amex)',
         'I': 'Sold Last (late reporting)',
         'J': 'Next Day Trade (next day clearing)',
         'K': 'Opened (late report of opened trade)',
         'L': 'Seller',
         'M': 'Sold (out of sequence)',
         'N': 'Stopped Stock (guarantee of price but does not execute the '
              'order)',
         'P': 'Imbalance More Buyers (Cannot be used in combination with Q)',
         'Q': 'Imbalance More Sellers (Cannot be used in combination with P)',
         'R': 'Opening '},
 '278': {},
 '279': {'0': 'New', '1': 'Change', '2': 'Delete'},
 '28': {'C': 'Cancel', 'N': 'New', 'R': 'Replace'},
 '280': {},
 '281': {'0': 'Unknown symbol',
         '1': 'Duplicate ',
         '2': 'Insufficient Bandwidth',
         '3': 'Insufficient Permissions',
         '4': 'Unsupported ',
         '5': 'Unsupported ',
         '6': 'Unsupported ',
         '7': 'Unsupported ',
         '8': 'Unsupported ',
         '9': 'Unsupported ',
         'A': 'Unsupported ',
         'B': 'Unsupported ',
         'C': 'Unsupported '},
 '282': {},
 '283': {},
 '284': {},
 '285': {'0': 'Cancelation / Trade Bust', '1': 'Error'},
 '286': {'0': 'Daily Open / Close / Settlement price',
         '1': 'Session Open / Close / Settlement price',
         '2': 'Delivery Settlement price',
         '3': 'Expected price',
         '4': 'Price <44>'},
 '287': {},
 '288': {},
 '289': {},
 '29': {'1': 'Agent',
        '2': 'Cross as agent',
        '3': 'Cross as principal',
        '4': 'Principal'},
 '290': {},
 '291': {'1': 'Bankrupt', '2': 'Pending delisting'},
 '292': {'A': 'Ex-Dividend',
         'B': 'Ex-Distribution',
         'C': 'Ex-Rights',
         'D': 'New',
         'E': 'Ex-Interest'},
 '293': {},
 '294': {},
 '295': {},
 '296': {},
 '298': {'1': 'Cancel for ',
         '2': 'Cancel for Security Type(s)',
         '3': 'Cancel for Underlying ',
         '4': 'Cancel All Quotes'},
 '299': {},
 '3': {},
 '30': {},
 '300': {'1': 'Unknown symbol (Security)',
         '2': 'Exchange(Security) closed',
         '3': 'Quote <S>',
         '4': 'Too late to enter',
         '5': 'Unknown ',
         '6': 'Duplicate ',
         '7': 'Invalid bid/ask spread',
         '8': 'Invalid price',
         '9': 'Not authorized to quote security'},
 '301': {'0': 'No Acknowledgement (Default)',
         '1': 'Acknowledge only negative or erroneous quotes',
         '2': 'Acknowledge each '},
 '302': {},
 '303': {'1': 'Manual', '2': 'Automatic'},
 '304': {},
 '306': {},
 '307': {},
 '308': {},
 '309': {},
 '31': {},
 '310': {},
 '311': {},
 '312': {},
 '313': {},
 '314': {},
 '315': {},
 '316': {},
 '317': {},
 '319': {},
 '320': {},
 '321': {'0': 'Request Security identity and specifications',
         '1': 'Request Security identity for the specifications provided (Name '
              'of the security is not supplied)',
         '2': 'Request List ',
         '3': 'Request List Securities (Can be qualified with '},
 '322': {},
 '323': {'1': 'Accept security proposal as is',
         '2': 'Accept security proposal with revisions as indicated in the '
              'message',
         '3': 'List of security types returned per request',
         '4': 'List of securities returned per request',
         '5': 'Reject <3>',
         '6': 'Can not match selection criteria'},
 '324': {},
 '325': {'N': 'Message is being sent as a result of a prior request',
         'Y': 'Message is being sent unsolicited'},
 '326': {'1': 'Opening Delay',
         '10': 'Market On Close Imbalance Sell',
         '11': '(not assigned)',
         '12': 'No Market Imbalance',
         '13': 'No Market On Close Imbalance',
         '14': 'ITS Pre-Opening',
         '15': 'New ',
         '16': 'Trade Dissemination Time',
         '17': 'Ready to trade (start of session)',
         '18': 'Not Available for trading (end of session)',
         '19': 'Not Traded on this Market',
         '2': 'Trading Halt',
         '20': 'Unknown or Invalid',
         '21': 'Pre-Open',
         '22': 'Opening Rotation',
         '23': 'Fast Market',
         '3': 'Resume',
         '4': 'No Open/No Resume',
         '5': 'Price <44>',
         '6': 'Trading Range Indication',
         '7': 'Market Imbalance Buy',
         '8': 'Market Imbalance Sell',
         '9': 'Market On Close Imbalance Buy'},
 '327': {'D': 'News <B>',
         'E': 'Order Influx',
         'I': 'Order Imbalance',
         'M': 'Additional Information',
         'P': 'News <B>',
         'X': 'Equipment Changeover'},
 '328': {'N': 'Halt was not related to a halt of the common stock',
         'Y': 'Halt was due to common stock being halted'},
 '329': {'N': 'Halt was not related to a halt of the related security',
         'Y': 'Halt was due to related security being halted'},
 '33': {},
 '330': {},
 '331': {},
 '332': {},
 '333': {},
 '334': {'1': 'Cancel', '2': 'Error', '3': 'Correction'},
 '335': {},
 '336': {},
 '337': {},
 '338': {'1': 'Electronic', '2': 'Open Outcry', '3': 'Two Party'},
 '339': {'1': 'Testing', '2': 'Simulated', '3': 'Production'},
 '34': {},
 '340': {'0': 'Unknown',
         '1': 'Halted',
         '2': 'Open',
         '3': 'Closed',
         '4': 'Pre-Open',
         '5': 'Pre-Close',
         '6': 'Request Rejected'},
 '341': {},
 '342': {},
 '343': {},
 '344': {},
 '345': {},
 '346': {},
 '347': {},
 '348': {},
 '349': {},
 '35': {'0': 'Heartbeat <0>',
        '1': 'Test Request <1>',
        '2': 'Resend Request <2>',
        '3': 'Reject <3>',
        '4': 'Sequence Reset <4>',
        '5': 'Logout <5>',
        '6': 'Indication of Interest',
        '7': 'Advertisement <7>',
        '8': 'Execution Report <8>',
        '9': 'Order Cancel Reject <9>',
        'A': 'Logon <A>',
        'AA': 'Derivative Security List <AA>',
        'AB': 'New Order - Multileg <AB>',
        'AC': 'Multileg Order Cancel/Replace (a.k.a. Multileg Order '
              'Modification Request)',
        'AD': 'Trade Capture Report Request <AD>',
        'AE': 'Trade Capture Report <AE>',
        'AF': 'Order Mass Status Request <AF>',
        'AG': 'Quote Request Reject <AG>',
        'AH': 'RFQ Request <AH>',
        'AI': 'Quote Status Report <AI>',
        'B': 'News <B>',
        'C': 'Email <C>',
        'D': 'Order - Single',
        'E': 'Order - List',
        'F': 'Order Cancel Request <F>',
        'J': 'Allocation <J>',
        'K': 'List Cancel Request <K>',
        'L': 'List Execute <L>',
        'M': 'List Status Request <M>',
        'N': 'List Status <N>',
        'P': 'Allocation ACK <P>',
        'Q': "Don't Know Trade <Q>",
        'R': 'Quote Request <R>',
        'S': 'Quote <S>',
        'T': 'Settlement Instructions <T>',
        'V': 'Market Data Request <V>',
        'W': 'Market Data-Snapshot/Full Refresh',
        'X': 'Market Data-Incremental Refresh',
        'Y': 'Market Data Request Reject <Y>',
        'Z': 'Quote Cancel <Z>',
        'a': 'Quote Status Request <a>',
        'b': 'Mass Quote Acknowledgement <b>',
        'c': 'Security Definition Request <c>',
        'd': 'Security Definition <d>',
        'e': 'Security Status Request <e>',
        'f': 'Security Status <f>',
        'g': 'Trading Session Status Request <g>',
        'h': 'Trading Session Status <h>',
        'i': 'Mass Quote <i>',
        'j': 'Business Message Reject <j>',
        'k': 'Bid Request <k>',
        'l': 'Bid Response <l>',
        'm': 'List Strike ',
        'n': 'XML message (e.g. non-FIX ',
        'o': 'Registration Instructions <o>',
        'p': 'Registration Instructions Response <p>',
        'q': 'Order Mass Cancel Request <q>',
        'r': 'Order Mass Cancel Report <r>',
        's': 'New Order - Cross <s>',
        't': 'Cross Order Cancel/Replace Request <t>',
        'u': 'Cross Order Cancel Request <u>',
        'v': 'Security Type Request <v>',
        'w': 'Security Types <w>',
        'x': 'Security List Request <x>',
        'y': 'Security List <y>',
        'z': 'Derivative Security List Request <z>'},
 '350': {},
 '351': {},
 '352': {},
 '353': {},
 '354': {},
 '355': {},
 '356': {},
 '357': {},
 '358': {},
 '359': {},
 '36': {},
 '360': {},
 '361': {},
 '362': {},
 '363': {},
 '364': {},
 '365': {},
 '366': {},
 '367': {},
 '368': {'1': 'Unknown symbol (Security)',
         '2': 'Exchange(Security) closed',
         '3': 'Quote <S>',
         '4': 'Too late to enter',
         '5': 'Unknown ',
         '6': 'Duplicate ',
         '7': 'Invalid bid/ask spread',
         '8': 'Invalid price',
         '9': 'Not authorized to quote security'},
 '369': {},
 '37': {},
 '370': {},
 '371': {},
 '372': {},
 '373': {'0': 'Invalid tag number',
         '1': 'Required tag missing',
         '10': 'SendingTime <52>',
         '11': 'Invalid ',
         '12': 'XML Validation error',
         '13': 'Tag appears more than once',
         '14': 'Tag specified out of required order',
         '15': 'Repeating group fields out of order',
         '16': 'Incorrect NumInGroup count for repeating group',
         '17': 'Non "Data" value includes field delimiter (<SOH> character)',
         '2': 'Tag not defined for this message type',
         '3': 'Undefined Tag',
         '4': 'Tag specified without a value',
         '5': 'Value is incorrect (out of range) for this tag',
         '6': 'Incorrect data format for value',
         '7': 'Decryption problem',
         '8': 'Signature <89>',
         '9': 'CompID problem'},
 '374': {'C': 'Cancel', 'N': 'New'},
 '375': {},
 '376': {},
 '377': {'N': 'Was not solicited', 'Y': 'Was solcitied'},
 '378': {'0': 'GT Corporate action',
         '1': 'GT renewal / restatement (no corporate action)',
         '2': 'Verbal change',
         '3': 'Repricing of order',
         '4': 'Broker option',
         '5': 'Partial decline of ',
         '6': 'Cancel on Trading Halt',
         '7': 'Cancel on System Failure',
         '8': 'Market (Exchange) Option'},
 '379': {},
 '38': {},
 '380': {'0': 'Other',
         '1': 'Unkown ID',
         '2': 'Unknown Security',
         '3': 'Unsupported Message Type',
         '4': 'Application not available',
         '5': 'Conditionally Required Field Missing',
         '6': 'Not authorized',
         '7': 'DeliverTo firm not available at this time'},
 '381': {},
 '382': {},
 '383': {},
 '384': {},
 '385': {'R': 'Receive', 'S': 'Send'},
 '386': {},
 '387': {},
 '388': {'0': 'Related to displayed price',
         '1': 'Related to market price',
         '2': 'Related to primary price',
         '3': 'Related to local primary price',
         '4': 'Related to midpoint price',
         '5': 'Related to last trade price'},
 '389': {},
 '39': {'0': 'New',
        '1': 'Partially filled',
        '2': 'Filled',
        '3': 'Done for day',
        '4': 'Canceled',
        '5': 'Replaced (Removed/Replaced)',
        '6': 'Pending Cancel (e.g. result of ',
        '7': 'Stopped',
        '8': 'Rejected',
        '9': 'Suspended',
        'A': 'Pending New',
        'B': 'Calculated',
        'C': 'Expired',
        'D': 'Accepted for bidding',
        'E': 'Pending Replace (e.g. result of '},
 '390': {},
 '391': {},
 '392': {},
 '393': {},
 '394': {'1': '"Non Disclosed" Style (e.g. US/European)',
         '2': '"Disclosed" Style (e.g. Japanese)',
         '3': 'No Bidding Process'},
 '395': {},
 '396': {},
 '397': {},
 '398': {},
 '399': {'1': 'Sector', '2': 'Country <421>', '3': 'Index'},
 '4': {'B': 'Buy', 'S': 'Sell', 'T': 'Trade', 'X': 'Cross'},
 '40': {'1': 'Market',
        '2': 'Limit',
        '3': 'Stop',
        '4': 'Stop limit',
        '5': 'Market on close (Deprecated)',
        '6': 'With or without',
        '7': 'Limit or better',
        '8': 'Limit with or without',
        '9': 'On basis',
        'A': 'On close (Deprecated)',
        'B': 'Limit on close (Deprecated)',
        'C': 'Forex - Market (Deprecated)',
        'D': 'Previously quoted',
        'E': 'Previously indicated',
        'F': 'Forex - Limit (Deprecated)',
        'G': 'Forex - Swap',
        'H': 'Forex - Previously Quoted (Deprecated)',
        'I': 'Funari (Limit Day Order with unexecuted portion handled as '
             'Market On Close. e.g. Japan)',
        'J': 'Market If Touched (MIT)',
        'K': 'Market with Leftover as Limit (market order then unexecuted '
             'quantity becomes limit order at last price)',
        'L': 'Previous Fund Valuation Point (Historic pricing) (for CIV)',
        'M': 'Next Fund Valuation Point - (Forward pricing) (for CIV)',
        'P': 'Pegged'},
 '400': {},
 '401': {'1': 'SideValue1 <396>', '2': 'SideValue 2'},
 '402': {},
 '403': {},
 '404': {},
 '405': {},
 '406': {},
 '407': {},
 '408': {},
 '409': {'1': '5day moving average',
         '2': '20 day moving average',
         '3': 'Normal Market Size',
         '4': 'Other'},
 '41': {},
 '410': {},
 '411': {'N': 'False', 'Y': 'True'},
 '412': {},
 '413': {},
 '414': {'1': 'Buy',
         '2': 'Sell',
         '3': 'Real-time execution reports (to be discouraged)'},
 '415': {},
 '416': {'1': 'Net', '2': 'Gross'},
 '417': {},
 '418': {},
 '419': {'2': 'Closing ',
         '3': 'Closing ',
         '4': 'Current price',
         '5': 'SQ',
         '6': 'VWAP through a day',
         '7': 'VWAP through a morning session',
         '8': 'VWAP through an afternoon session',
         '9': 'VWAP through a day except "YORI" (an opening auction)',
         'A': 'VWAP through a morning session except "YORI" (an opening '
              'auction)',
         'B': 'VWAP through an afternoon session except "YORI" (an opening '
              'auction)',
         'C': 'Strike',
         'D': 'Open',
         'Z': 'Others'},
 '42': {},
 '420': {},
 '421': {},
 '422': {},
 '423': {'1': 'Percentage',
         '2': 'per share (e.g. cents per share)',
         '3': 'Fixed Amount (absolute value)',
         '4': 'discount - percentage points below par',
         '5': 'premium - percentage points over par',
         '6': 'basis points relative to benchmark',
         '7': 'TED price (see "Volume 1 - Glossary")',
         '8': 'TED yield (see "Volume 1 - Glossary")'},
 '424': {},
 '425': {},
 '426': {},
 '427': {'0': 'book out all trades on day of execution',
         '1': 'accumulate executions until order is filled or expires',
         '2': 'accumulate until verbally notified otherwise'},
 '428': {},
 '429': {'1': 'Ack',
         '2': 'Response',
         '3': 'Timed',
         '4': 'ExecStarted',
         '5': 'AllDone',
         '6': 'Alert'},
 '43': {'N': 'Original transmission', 'Y': 'Possible duplicate'},
 '430': {'1': 'Net', '2': 'Gross'},
 '431': {'1': 'InBiddingProcess',
         '2': 'ReceivedForExecution',
         '3': 'Executing',
         '4': 'Canceling',
         '5': 'Alert',
         '6': 'All Done',
         '7': 'Reject <3>'},
 '432': {},
 '433': {'1': 'Immediate',
         '2': 'Wait for Execute Instruction (e.g. a ',
         '3': 'Exchange/switch CIV order - Sell driven',
         '4': 'Exchange/switch CIV order - Buy driven, cash top-up (i.e. '
              'additional cash will be provided to fulfil the order)',
         '5': 'Exchange/switch CIV order - Buy driven, cash withdraw (i.e. '
              'additional cash will not be provided to fulfil the order)'},
 '434': {'1': 'Order Cancel Request <F>',
         '2': 'Order Cancel/Replace Request <G>'},
 '435': {},
 '436': {},
 '437': {},
 '438': {},
 '439': {},
 '44': {},
 '440': {},
 '441': {},
 '442': {'1': 'Single Security (default if not specified)',
         '2': 'Individual leg of a multi-leg security',
         '3': 'Multi-leg security'},
 '443': {},
 '444': {},
 '445': {},
 '446': {},
 '447': {'1': 'Korean Investor ID',
         '2': 'Taiwanese Qualified Foreign Investor ID QFII / FID',
         '3': 'Taiwanese Trading ',
         '4': 'Malaysian Central Depository (MCD) number',
         '5': 'Chinese B Share (Shezhen and Shanghai)',
         '6': 'UK National Insurance or Pension Number',
         '7': 'US Social Security Number',
         '8': 'US Employer Identification Number',
         '9': 'Australian Business Number',
         'A': 'Australian Tax File Number',
         'B': 'BIC (Bank Identification Code—Swift managed) code (ISO 9362 — '
              'See "',
         'C': 'Generally accepted market participant identifier (e.g. NASD '
              'mnemonic)',
         'D': 'Proprietary/Custom code',
         'E': 'ISO ',
         'F': 'Settlement Entity Location (note if Local Market Settlement use '
              '"E = ISO '},
 '448': {},
 '449': {},
 '45': {},
 '451': {},
 '452': {'1': 'Executing Firm (formerly FIX 4.2 ExecBroker)',
         '10': 'Settlement Location (formerly FIX 4.2 SettlLocation)',
         '11': 'Order Origination Trader (associated with Order Origination '
               'Firm - e.g. trader who initiates/submits the order)',
         '12': 'Executing Trader (associated with Executing Firm - actually '
               'executes)',
         '13': 'Order Origination Firm (e.g. buyside firm)',
         '14': 'Giveup Clearing Firm (firm to which trade is given up)',
         '15': 'Correspondant Clearing Firm',
         '16': 'Executing System',
         '17': 'Contra Firm',
         '18': 'Contra Clearing Firm',
         '19': 'Sponsoring Firm',
         '2': 'Broker of Credit (formerly FIX 4.2 BrokerOfCredit)',
         '20': 'Underlying Contra Firm',
         '3': 'Client ID (formerly FIX 4.2 ClientID)',
         '4': 'Clearing Firm (formerly FIX 4.2 ClearingFirm)',
         '5': 'Investor ID',
         '6': 'Introducing Firm',
         '7': 'Entering Firm',
         '8': 'Locate/Lending Firm (for short-sales)',
         '9': 'Fund manager Client ID (for CIV)'},
 '453': {},
 '454': {},
 '455': {},
 '456': {},
 '457': {},
 '458': {},
 '459': {},
 '460': {'1': 'AGENCY',
         '10': 'MORTGAGE',
         '11': 'MUNICIPAL',
         '12': 'OTHER',
         '2': 'COMMODITY',
         '3': 'CORPORATE',
         '4': 'CURRENCY',
         '5': 'EQUITY',
         '6': 'GOVERNMENT',
         '7': 'INDEX',
         '8': 'LOAN',
         '9': 'MONEYMARKET'},
 '461': {},
 '462': {},
 '463': {},
 '464': {'N': 'False (Production)', 'Y': 'True (Test)'},
 '465': {'1': 'SHARES',
         '2': 'BONDS',
         '3': 'CURRENTFACE',
         '4': 'ORIGINALFACE',
         '5': 'CURRENCY',
         '6': 'CONTRACTS',
         '7': 'OTHER',
         '8': 'PAR (see "Volume 1 - Glossary")'},
 '466': {},
 '467': {},
 '468': {},
 '469': {},
 '47': {'A': 'Agency single order',
        'B': 'Short exempt transaction (refer to A type)',
        'C': 'Program Order, non-index arb, for Member firm/org',
        'D': 'Program Order, index arb, for Member firm/org',
        'E': 'Short Exempt Transaction for Principal (was incorrectly '
             'identified in the FIX spec as "Registered Equity Market Maker\r',
        'F': 'Short exempt transaction (refer to W type)',
        'H': 'Short exempt transaction (refer to I type)',
        'I': 'Individual Investor, single order',
        'J': 'Program Order, index arb, for individual customer',
        'K': 'Program Order, non-index arb, for individual customer',
        'L': 'Short exempt transaction for member competing market-maker '
             'affiliated with the firm clearing the trade (refer to P and\r',
        'M': 'Program Order, index arb, for other member',
        'N': 'Program Order, non-index arb, for other member',
        'O': 'Proprietary transactions for competing market-maker that is '
             'affiliated with the clearing member (was incorrectly '
             'identified\r',
        'P': 'Principal',
        'R': 'Transactions for the account of a non-member competing market '
             'maker (was incorrectly identified in the FIX spec as '
             '"Competing\r',
        'S': 'Specialist trades',
        'T': "Transactions for the account of an unaffiliated member's "
             'competing market maker (was incorrectly identified in the FIX\r',
        'U': 'Program Order, index arb, for other agency',
        'W': 'All other orders as agent for other member',
        'X': 'Short exempt transaction for member competing market-maker not '
             'affiliated with the firm clearing the trade (refer to W\r',
        'Y': 'Program Order, non-index arb, for other agency',
        'Z': 'Short exempt transaction for non-member competing market-maker '
             '(refer to A and R types)'},
 '470': {},
 '471': {},
 '472': {},
 '473': {},
 '474': {},
 '475': {},
 '476': {},
 '477': {},
 '478': {},
 '479': {},
 '48': {},
 '480': {},
 '481': {'1': 'Exempt - Below The Limit',
         '2': 'Exempt - Client Money Type Exemption',
         '3': 'Exempt - Authorised Credit or Financial Institution.',
         'N': 'Not checked',
         'Y': 'Passed'},
 '482': {},
 '483': {},
 '484': {},
 '485': {},
 '486': {},
 '487': {'C': 'Cancel', 'N': 'New', 'R': 'Replace'},
 '488': {},
 '489': {},
 '49': {},
 '490': {},
 '491': {},
 '492': {},
 '493': {},
 '494': {},
 '495': {},
 '496': {},
 '497': {},
 '498': {},
 '499': {},
 '5': {'C': 'Cancel', 'N': 'New', 'R': 'Replace'},
 '50': {},
 '500': {},
 '501': {},
 '502': {},
 '503': {},
 '504': {},
 '505': {},
 '506': {},
 '507': {},
 '508': {},
 '509': {},
 '510': {},
 '511': {},
 '512': {},
 '513': {},
 '514': {},
 '515': {},
 '516': {},
 '517': {},
 '518': {},
 '519': {},
 '52': {},
 '520': {},
 '521': {},
 '522': {'1': 'Individual Investor',
         '10': 'Networking Sub-',
         '11': 'Non-Profit Organization',
         '12': 'Corporate Body',
         '2': 'Public Company',
         '3': 'Private Company',
         '4': 'Individual Trustee',
         '5': 'Company Trustee',
         '6': 'Pension Plan',
         '7': 'Custodian Under Gifts to Minors Act',
         '8': 'Trusts',
         '9': 'Fiduciaries'},
 '523': {},
 '524': {},
 '525': {},
 '526': {},
 '527': {},
 '528': {'A': 'Agency',
         'G': 'Proprietary',
         'I': 'Individual',
         'P': 'Principal (Note for CMS purposes, Principal includes '
              'Proprietary)',
         'R': 'Riskless Principal',
         'W': 'Agent for Other Member'},
 '529': {'1': 'Program Trade',
         '2': 'Index Arbitrage',
         '3': 'Non-Index Arbitrage',
         '4': 'Competing Market Maker',
         '5': 'Acting as Market Maker or Specialist in the security',
         '6': 'Acting as Market Maker or Specialist in the underlying security '
              'of a derivative security',
         '7': 'Foreign Entity (of foreign governmnet or regulatory '
              'jurisdiction)',
         '8': 'External Market Participant',
         '9': 'External Inter-connected Market Linkage',
         'A': 'Riskless Arbitrage'},
 '530': {'1': 'Cancel orders for a security',
         '2': 'Cancel orders for an Underlying security',
         '3': 'Cancel orders for a ',
         '4': 'Cancel orders for a ',
         '5': 'Cancel orders for a ',
         '6': 'Cancel orders for a trading session',
         '7': 'Cancel all orders'},
 '531': {'0': 'Cancel Request Rejected - See ',
         '1': 'Cancel orders for a security',
         '2': 'Cancel orders for an Underlying security',
         '3': 'Cancel orders for a ',
         '4': 'Cancel orders for a ',
         '5': 'Cancel orders for a ',
         '6': 'Cancel orders for a trading session',
         '7': 'Cancel all orders'},
 '532': {},
 '533': {},
 '534': {},
 '535': {},
 '536': {},
 '537': {'0': 'Indicative', '1': 'Tradeable', '2': 'Restricted Tradeable'},
 '538': {},
 '539': {},
 '54': {'1': 'Buy',
        '2': 'Sell',
        '3': 'Buy minus',
        '4': 'Sell plus',
        '5': 'Sell short',
        '6': 'Sell short exempt',
        '7': 'Undisclosed (valid for IOI and List Order messages only)',
        '8': 'Cross (orders where counterparty is an exchange, valid for all '
             'messages except IOIs)',
        '9': 'Cross short',
        'A': 'Cross short exempt',
        'B': '"As Defined" (for use with multileg instruments)',
        'C': '"Opposite" (for use with multileg instruments)'},
 '540': {},
 '541': {},
 '542': {},
 '543': {'"ZZ"': 'physical or bearer'},
 '544': {'1': 'Cash', '2': 'Margin Open', '3': 'Margin Close'},
 '545': {},
 '546': {'1': 'Local (Exchange, ECN, ATS)', '2': 'National', '3': 'Global'},
 '547': {'N': 'Server must send an explicit delete for bids or offers falling '
              'outside the requested ',
         'Y': 'Client has responsibility for implicitly deleting bids or '
              'offers falling outside the '},
 '548': {},
 '549': {'1': 'Cross Trade which is executed completely or not. Both sides are '
              'treated in the same manner. This is equivalent to an All\r',
         '2': 'Cross Trade which is executed partially and the rest is '
              'cancelled. One side is fully executed, the other side is '
              'partially\r',
         '3': 'Cross trade which is partially executed with the unfilled '
              'portions remaining active. One side of the cross is fully '
              'executed\r',
         '4': 'Cross trade is executed with existing orders with the same '
              'price. In the case other orders exist with the same price,\r'},
 '55': {},
 '550': {},
 '551': {},
 '552': {'1': 'one side', '2': 'both sides'},
 '553': {},
 '554': {},
 '555': {},
 '556': {},
 '557': {},
 '558': {},
 '559': {'0': 'Symbol <55>',
         '1': 'SecurityType <167>',
         '2': 'Product <460>',
         '3': 'TradingSessionID <336>',
         '4': 'All Securities'},
 '56': {},
 '560': {'0': 'Valid request',
         '1': 'Invalid or unsupported request',
         '2': 'No instruments found that match selection criteria',
         '3': 'Not authorized to retrieve instrument data',
         '4': '<Instrument>',
         '5': 'Request for instrument data not supported'},
 '561': {},
 '562': {},
 '563': {},
 '564': {},
 '565': {},
 '566': {},
 '567': {'1': 'Unknown or invalid '},
 '568': {},
 '569': {'0': 'All trades',
         '1': 'Matched trades matching Criteria provided on request (parties, '
              'order id, instrument, input source, etc.)',
         '2': 'Unmatched trades that match criteria',
         '3': 'Unreported trades that match criteria',
         '4': 'Advisories that match criteria'},
 '57': {},
 '570': {'N': 'not reported to counterparty',
         'Y': 'previously reported to counterparty'},
 '571': {},
 '572': {},
 '573': {'0': 'compared, matched or affirmed',
         '1': 'uncompared, unmatched, or unaffirmed',
         '2': 'advisory or alert'},
 '574': {'A1': 'Exact match on Trade Date, Stock ',
         'A2': 'Exact match on Trade Date, Stock ',
         'A3': 'Exact match on Trade Date, Stock ',
         'A4': 'Exact match on Trade Date, Stock ',
         'A5': 'Exact match on Trade Date, Stock ',
         'AQ': 'Compared records resulting from stamped advisories or '
               'specialist',
         'M1': 'ACT M1 Match',
         'M2': 'ACT M2 Match',
         'M3': 'ACT Accepted Trade',
         'M4': 'ACT Default Trade',
         'M5': 'ACT Default After M2',
         'M6': 'ACT M6 Match',
         'MT': 'Non-ACT'},
 '575': {},
 '576': {},
 '577': {'0': 'process normally',
         '1': 'exclude from all netting',
         '10': 'Automatic give-up mode (trade give-up to the give-up '
               'destination number specified)',
         '2': 'bilateral netting only',
         '3': 'ex clearing',
         '4': 'special trade',
         '5': 'multilateral netting',
         '6': 'clear against central counterparty',
         '7': 'exclude from central counterparty',
         '8': 'Manual mode (pre-posting and/or pre-giveup)',
         '9': 'Automatic posting mode (trade posting to the position account '
              'number specified)'},
 '578': {},
 '579': {},
 '58': {},
 '580': {},
 '581': {'1': 'Account <1>',
         '2': 'Account <1>',
         '3': 'House Trader',
         '4': 'Floor Trader',
         '6': 'Account <1>',
         '7': 'Account <1>',
         '8': 'Joint Backoffice '},
 '582': {},
 '583': {},
 '584': {},
 '585': {'1': 'Status for orders for a security',
         '2': 'Status for orders for an Underlying security',
         '3': 'Status for orders for a ',
         '4': 'Status for orders for a ',
         '5': 'Status for orders for a ',
         '6': 'Status for orders for a trading session',
         '7': 'Status for all orders',
         '8': 'Status for orders for a '},
 '586': {},
 '587': {},
 '588': {},
 '589': {},
 '59': {'0': 'Day',
        '1': 'Good Till Cancel (GTC)',
        '2': 'At the Opening (OPG)',
        '3': 'Immediate or Cancel (IOC)',
        '4': 'Fill or Kill (FOK)',
        '5': 'Good Till Crossing (GTX)',
        '6': 'Good Till Date',
        '7': 'At the Close'},
 '590': {},
 '591': {},
 '592': {},
 '593': {},
 '594': {},
 '595': {},
 '596': {},
 '597': {},
 '598': {},
 '599': {},
 '6': {},
 '60': {},
 '600': {},
 '601': {},
 '602': {},
 '603': {},
 '604': {},
 '605': {},
 '606': {},
 '607': {},
 '608': {},
 '609': {},
 '61': {'0': 'Normal', '1': 'Flash', '2': 'Background'},
 '610': {},
 '611': {},
 '612': {},
 '613': {},
 '614': {},
 '615': {},
 '616': {},
 '617': {},
 '618': {},
 '619': {},
 '62': {},
 '620': {},
 '621': {},
 '622': {},
 '623': {},
 '624': {'1': 'Buy',
         '2': 'Sell',
         '3': 'Buy minus',
         '4': 'Sell plus',
         '5': 'Sell short',
         '6': 'Sell short exempt',
         '7': 'Undisclosed (valid for IOI and List Order messages only)',
         '8': 'Cross (orders where counterparty is an exchange, valid for all '
              'messages except IOIs)',
         '9': 'Cross short',
         'A': 'Cross short exempt',
         'B': '"As Defined" (for use with multileg instruments)',
         'C': '"Opposite" (for use with multileg instruments)'},
 '625': {},
 '626': {'1': 'Buyside Calculated (includes MiscFees and ',
         '2': 'Buyside Preliminary (without MiscFees and ',
         '3': 'Sellside Calculated Using Preliminary (includes MiscFees and ',
         '4': 'Sellside Calculated Without Preliminary (sent unsolicited by '
              'sellside, includes MiscFees and ',
         '5': 'Buyside Ready-To-Book - Single Order',
         '6': 'Buyside Ready-To-Book - Combined Set of Orders'},
 '627': {},
 '628': {},
 '629': {},
 '63': {'0': 'Regular',
        '1': 'Cash',
        '2': 'Next Day',
        '3': 'T+2',
        '4': 'T+3',
        '5': 'T+4',
        '6': 'Future',
        '7': 'When And If Issued',
        '8': 'Sellers Option',
        '9': 'T+ 5',
        'A': 'T+1'},
 '630': {},
 '631': {},
 '632': {},
 '633': {},
 '634': {},
 '635': {},
 '636': {'N': 'Order has been accepted but not yet in a working state',
         'Y': 'Order is currently being worked'},
 '637': {},
 '638': {'0': 'Priority Unchanged',
         '1': 'Lost Priority as result of order change'},
 '639': {},
 '64': {},
 '640': {},
 '641': {},
 '642': {},
 '643': {},
 '644': {},
 '645': {},
 '646': {},
 '647': {},
 '648': {},
 '649': {},
 '65': {},
 '650': {'N': 'Does not constitute a legal confirm', 'Y': 'Legal confirm'},
 '651': {},
 '652': {},
 '653': {'0': 'Pending Approval',
         '1': 'Approved (Accepted)',
         '2': 'Rejected',
         '3': 'Unauthorized request',
         '4': 'Invalid definition request'},
 '654': {},
 '655': {},
 '656': {},
 '657': {},
 '658': {'1': 'Unknown symbol (Security)',
         '2': 'Exchange(Security) closed',
         '3': 'Quote Request <R>',
         '4': 'Too late to enter',
         '5': 'Invalid price',
         '6': 'Not authorized to request quote'},
 '659': {},
 '66': {},
 '67': {},
 '69': {},
 '7': {},
 '70': {},
 '71': {'0': 'New',
        '1': 'Replace',
        '2': 'Cancel',
        '3': 'Preliminary (without MiscFees and ',
        '4': 'Calculated (includes MiscFees and ',
        '5': 'Calculated without Preliminary (sent unsolicited by broker, '
             'includes MiscFees and '},
 '72': {},
 '73': {},
 '74': {},
 '75': {},
 '76': {},
 '78': {},
 '79': {},
 '8': {},
 '81': {'0': 'regular',
        '1': 'soft dollar',
        '2': 'step-in',
        '3': 'step-out',
        '4': 'soft-dollar step-in',
        '5': 'soft-dollar step-out',
        '6': 'plan sponsor'},
 '82': {},
 '83': {},
 '84': {},
 '87': {'0': 'accepted (successfully processed)',
        '1': 'rejected',
        '2': 'partial accept',
        '3': 'received (received, not yet processed)'},
 '88': {'0': 'unknown account(s)',
        '1': 'incorrect quantity',
        '2': 'incorrect average price',
        '3': 'unknown executing broker mnemonic',
        '4': 'commission difference',
        '5': 'unknown ',
        '6': 'unknown ',
        '7': 'other'},
 '89': {},
 '9': {},
 '90': {},
 '91': {},
 '92': {},
 '93': {},
 '94': {'0': 'New', '1': 'Reply', '2': 'Admin Reply'},
 '95': {},
 '96': {},
 '97': {},
 '98': {'0': 'None / other',
        '1': 'PKCS (proprietary)',
        '2': 'DES (ECB mode)',
        '3': 'PKCS/DES (proprietary)',
        '4': 'PGP/DES (defunct)',
        '5': 'PGP/DES-MD5 (see app note on FIX web site)',
        '6': 'PEM/DES-MD5 (see app note on FIX web site)'},
 '99': {}}
