field_by_tag =  {'1': 'Account',
 '10': 'CheckSum',
 '100': 'ExDestination',
 '102': 'CxlRejReason',
 '103': 'OrdRejReason',
 '104': 'IOIQualifier',
 '105': 'WaveNo',
 '106': 'Issuer',
 '107': 'SecurityDesc',
 '108': 'HeartBtInt',
 '109': 'ClientID',
 '11': 'ClOrdID',
 '110': 'MinQty',
 '111': 'MaxFloor',
 '112': 'TestReqID',
 '113': 'ReportToExch',
 '114': 'LocateReqd',
 '115': 'OnBehalfOfCompID',
 '116': 'OnBehalfOfSubID',
 '117': 'QuoteID',
 '118': 'NetMoney',
 '119': 'SettlCurrAmt',
 '12': 'Commission',
 '120': 'SettlCurrency',
 '121': 'ForexReq',
 '122': 'OrigSendingTime',
 '123': 'GapFillFlag',
 '124': 'NoExecs',
 '126': 'ExpireTime',
 '127': 'DKReason',
 '128': 'DeliverToCompID',
 '129': 'DeliverToSubID',
 '13': 'CommType',
 '130': 'IOINaturalFlag',
 '131': 'QuoteReqID',
 '132': 'BidPx',
 '133': 'OfferPx',
 '134': 'BidSize',
 '135': 'OfferSize',
 '136': 'NoMiscFees',
 '137': 'MiscFeeAmt',
 '138': 'MiscFeeCurr',
 '139': 'MiscFeeType',
 '14': 'CumQty',
 '140': 'PrevClosePx',
 '141': 'ResetSeqNumFlag',
 '142': 'SenderLocationID',
 '143': 'TargetLocationID',
 '144': 'OnBehalfOfLocationID',
 '145': 'DeliverToLocationID',
 '146': 'NoRelatedSym',
 '147': 'Subject',
 '148': 'Headline',
 '149': 'URLLink',
 '15': 'Currency',
 '150': 'ExecType',
 '151': 'LeavesQty',
 '152': 'CashOrderQty',
 '153': 'AllocAvgPx',
 '154': 'AllocNetMoney',
 '155': 'SettlCurrFxRate',
 '156': 'SettlCurrFxRateCalc',
 '157': 'NumDaysInterest',
 '158': 'AccruedInterestRate',
 '159': 'AccruedInterestAmt',
 '16': 'EndSeqNo',
 '160': 'SettlInstMode',
 '161': 'AllocText',
 '162': 'SettlInstID',
 '163': 'SettlInstTransType',
 '164': 'EmailThreadID',
 '165': 'SettlInstSource',
 '166': 'SettlLocation',
 '167': 'SecurityType',
 '168': 'EffectiveTime',
 '169': 'StandInstDbType',
 '17': 'ExecID',
 '170': 'StandInstDbName',
 '171': 'StandInstDbID',
 '172': 'SettlDeliveryType',
 '173': 'SettlDepositoryCode',
 '174': 'SettlBrkrCode',
 '175': 'SettlInstCode',
 '176': 'SecuritySettlAgentName',
 '177': 'SecuritySettlAgentCode',
 '178': 'SecuritySettlAgentAcctNum',
 '179': 'SecuritySettlAgentAcctName',
 '18': 'ExecInst',
 '180': 'SecuritySettlAgentContactName',
 '181': 'SecuritySettlAgentContactPhone',
 '182': 'CashSettlAgentName',
 '183': 'CashSettlAgentCode',
 '184': 'CashSettlAgentAcctNum',
 '185': 'CashSettlAgentAcctName',
 '186': 'CashSettlAgentContactName',
 '187': 'CashSettlAgentContactPhone',
 '188': 'BidSpotRate',
 '189': 'BidForwardPoints',
 '19': 'ExecRefID',
 '190': 'OfferSpotRate',
 '191': 'OfferForwardPoints',
 '192': 'OrderQty2',
 '193': 'FutSettDate2',
 '194': 'LastSpotRate',
 '195': 'LastForwardPoints',
 '196': 'AllocLinkID',
 '197': 'AllocLinkType',
 '198': 'SecondaryOrderID',
 '199': 'NoIOIQualifiers',
 '2': 'AdvId',
 '20': 'ExecTransType',
 '200': 'MaturityMonthYear',
 '201': 'PutOrCall',
 '202': 'StrikePrice',
 '203': 'CoveredOrUncovered',
 '204': 'CustomerOrFirm',
 '205': 'MaturityDay',
 '206': 'OptAttribute',
 '207': 'SecurityExchange',
 '208': 'NotifyBrokerOfCredit',
 '209': 'AllocHandlInst',
 '21': 'HandlInst',
 '210': 'MaxShow',
 '211': 'PegDifference',
 '212': 'XmlDataLen',
 '213': 'XmlData',
 '214': 'SettlInstRefID',
 '215': 'NoRoutingIDs',
 '216': 'RoutingType',
 '217': 'RoutingID',
 '218': 'SpreadToBenchmark',
 '219': 'Benchmark',
 '22': 'IDSource',
 '223': 'CouponRate',
 '23': 'IOIid',
 '231': 'ContractMultiplier',
 '25': 'IOIQltyInd',
 '26': 'IOIRefID',
 '262': 'MDReqID',
 '263': 'SubscriptionRequestType',
 '264': 'MarketDepth',
 '265': 'MDUpdateType',
 '266': 'AggregatedBook',
 '267': 'NoMDEntryTypes',
 '268': 'NoMDEntries',
 '269': 'MDEntryType',
 '27': 'IOIShares',
 '270': 'MDEntryPx',
 '271': 'MDEntrySize',
 '272': 'MDEntryDate',
 '273': 'MDEntryTime',
 '274': 'TickDirection',
 '275': 'MDMkt',
 '276': 'QuoteCondition',
 '277': 'TradeCondition',
 '278': 'MDEntryID',
 '279': 'MDUpdateAction',
 '28': 'IOITransType',
 '280': 'MDEntryRefID',
 '281': 'MDReqRejReason',
 '282': 'MDEntryOriginator',
 '283': 'LocationID',
 '284': 'DeskID',
 '285': 'DeleteReason',
 '286': 'OpenCloseSettleFlag',
 '287': 'SellerDays',
 '288': 'MDEntryBuyer',
 '289': 'MDEntrySeller',
 '29': 'LastCapacity',
 '290': 'MDEntryPositionNo',
 '291': 'FinancialStatus',
 '292': 'CorporateAction',
 '293': 'DefBidSize',
 '294': 'DefOfferSize',
 '295': 'NoQuoteEntries',
 '296': 'NoQuoteSets',
 '297': 'QuoteAckStatus',
 '298': 'QuoteCancelType',
 '299': 'QuoteEntryID',
 '3': 'AdvRefID',
 '30': 'LastMkt',
 '300': 'QuoteRejectReason',
 '301': 'QuoteResponseLevel',
 '302': 'QuoteSetID',
 '303': 'QuoteRequestType',
 '304': 'TotQuoteEntries',
 '305': 'UnderlyingIDSource',
 '306': 'UnderlyingIssuer',
 '307': 'UnderlyingSecurityDesc',
 '308': 'UnderlyingSecurityExchange',
 '309': 'UnderlyingSecurityID',
 '31': 'LastPx',
 '310': 'UnderlyingSecurityType',
 '311': 'UnderlyingSymbol',
 '312': 'UnderlyingSymbolSfx',
 '313': 'UnderlyingMaturityMonthYear',
 '314': 'UnderlyingMaturityDay',
 '315': 'UnderlyingPutOrCall',
 '316': 'UnderlyingStrikePrice',
 '317': 'UnderlyingOptAttribute',
 '319': 'RatioQty',
 '32': 'LastShares',
 '320': 'SecurityReqID',
 '321': 'SecurityRequestType',
 '322': 'SecurityResponseID',
 '323': 'SecurityResponseType',
 '324': 'SecurityStatusReqID',
 '325': 'UnsolicitedIndicator',
 '326': 'SecurityTradingStatus',
 '327': 'HaltReason',
 '328': 'InViewOfCommon',
 '329': 'DueToRelated',
 '33': 'LinesOfText',
 '330': 'BuyVolume',
 '331': 'SellVolume',
 '332': 'HighPx',
 '333': 'LowPx',
 '334': 'Adjustment',
 '335': 'TradSesReqID',
 '336': 'TradingSessionID',
 '337': 'ContraTrader',
 '338': 'TradSesMethod',
 '339': 'TradSesMode',
 '34': 'MsgSeqNum',
 '340': 'TradSesStatus',
 '341': 'TradSesStartTime',
 '342': 'TradSesOpenTime',
 '343': 'TradSesPreCloseTime',
 '344': 'TradSesCloseTime',
 '345': 'TradSesEndTime',
 '346': 'NumberOfOrders',
 '347': 'MessageEncoding',
 '348': 'EncodedIssuerLen',
 '349': 'EncodedIssuer',
 '35': 'MsgType',
 '350': 'EncodedSecurityDescLen',
 '351': 'EncodedSecurityDesc',
 '352': 'EncodedListExecInstLen',
 '353': 'EncodedListExecInst',
 '354': 'EncodedTextLen',
 '355': 'EncodedText',
 '356': 'EncodedSubjectLen',
 '357': 'EncodedSubject',
 '358': 'EncodedHeadlineLen',
 '359': 'EncodedHeadline',
 '36': 'NewSeqNo',
 '360': 'EncodedAllocTextLen',
 '361': 'EncodedAllocText',
 '362': 'EncodedUnderlyingIssuerLen',
 '363': 'EncodedUnderlyingIssuer',
 '364': 'EncodedUnderlyingSecurityDescLen',
 '365': 'EncodedUnderlyingSecurityDesc',
 '366': 'AllocPrice',
 '367': 'QuoteSetValidUntilTime',
 '368': 'QuoteEntryRejectReason',
 '369': 'LastMsgSeqNumProcessed',
 '37': 'OrderID',
 '370': 'OnBehalfOfSendingTime',
 '371': 'RefTagID',
 '372': 'RefMsgType',
 '373': 'SessionRejectReason',
 '374': 'BidRequestTransType',
 '375': 'ContraBroker',
 '376': 'ComplianceID',
 '377': 'SolicitedFlag',
 '378': 'ExecRestatementReason',
 '379': 'BusinessRejectRefID',
 '38': 'OrderQty',
 '380': 'BusinessRejectReason',
 '381': 'GrossTradeAmt',
 '382': 'NoContraBrokers',
 '383': 'MaxMessageSize',
 '384': 'NoMsgTypes',
 '385': 'MsgDirection',
 '386': 'NoTradingSessions',
 '387': 'TotalVolumeTraded',
 '388': 'DiscretionInst',
 '389': 'DiscretionOffset',
 '39': 'OrdStatus',
 '390': 'BidID',
 '391': 'ClientBidID',
 '392': 'ListName',
 '393': 'TotalNumSecurities',
 '394': 'BidType',
 '395': 'NumTickets',
 '396': 'SideValue1',
 '397': 'SideValue2',
 '398': 'NoBidDescriptors',
 '399': 'BidDescriptorType',
 '4': 'AdvSide',
 '40': 'OrdType',
 '400': 'BidDescriptor',
 '401': 'SideValueInd',
 '402': 'LiquidityPctLow',
 '403': 'LiquidityPctHigh',
 '404': 'LiquidityValue',
 '405': 'EFPTrackingError',
 '406': 'FairValue',
 '407': 'OutsideIndexPct',
 '408': 'ValueOfFutures',
 '409': 'LiquidityIndType',
 '41': 'OrigClOrdID',
 '410': 'WtAverageLiquidity',
 '411': 'ExchangeForPhysical',
 '412': 'OutMainCntryUIndex',
 '413': 'CrossPercent',
 '414': 'ProgRptReqs',
 '415': 'ProgPeriodInterval',
 '416': 'IncTaxInd',
 '417': 'NumBidders',
 '418': 'TradeType',
 '419': 'BasisPxType',
 '42': 'OrigTime',
 '420': 'NoBidComponents',
 '421': 'Country',
 '422': 'TotNoStrikes',
 '423': 'PriceType',
 '424': 'DayOrderQty',
 '425': 'DayCumQty',
 '426': 'DayAvgPx',
 '427': 'GTBookingInst',
 '428': 'NoStrikes',
 '429': 'ListStatusType',
 '43': 'PossDupFlag',
 '430': 'NetGrossInd',
 '431': 'ListOrderStatus',
 '432': 'ExpireDate',
 '433': 'ListExecInstType',
 '434': 'CxlRejResponseTo',
 '435': 'UnderlyingCouponRate',
 '436': 'UnderlyingContractMultiplier',
 '437': 'ContraTradeQty',
 '438': 'ContraTradeTime',
 '439': 'ClearingFirm',
 '44': 'Price',
 '440': 'ClearingAccount',
 '441': 'LiquidityNumSecurities',
 '442': 'MultiLegReportingType',
 '443': 'StrikeTime',
 '444': 'ListStatusText',
 '445': 'EncodedListStatusTextLen',
 '446': 'EncodedListStatusText',
 '45': 'RefSeqNum',
 '46': 'RelatdSym',
 '48': 'SecurityID',
 '49': 'SenderCompID',
 '5': 'AdvTransType',
 '50': 'SenderSubID',
 '52': 'SendingTime',
 '53': 'Shares',
 '54': 'Side',
 '55': 'Symbol',
 '56': 'TargetCompID',
 '57': 'TargetSubID',
 '58': 'Text',
 '59': 'TimeInForce',
 '6': 'AvgPx',
 '60': 'TransactTime',
 '61': 'Urgency',
 '62': 'ValidUntilTime',
 '63': 'SettlmntTyp',
 '64': 'FutSettDate',
 '65': 'SymbolSfx',
 '66': 'ListID',
 '67': 'ListSeqNo',
 '69': 'ListExecInst',
 '7': 'BeginSeqNo',
 '70': 'AllocID',
 '71': 'AllocTransType',
 '72': 'RefAllocID',
 '73': 'NoOrders',
 '74': 'AvgPrxPrecision',
 '75': 'TradeDate',
 '76': 'ExecBroker',
 '77': 'OpenClose',
 '78': 'NoAllocs',
 '79': 'AllocAccount',
 '8': 'BeginString',
 '80': 'AllocShares',
 '81': 'ProcessCode',
 '82': 'NoRpts',
 '83': 'RptSeq',
 '84': 'CxlQty',
 '87': 'AllocStatus',
 '88': 'AllocRejCode',
 '89': 'Signature',
 '9': 'BodyLength',
 '90': 'SecureDataLen',
 '91': 'SecureData',
 '92': 'BrokerOfCredit',
 '93': 'SignatureLength',
 '94': 'EmailType',
 '95': 'RawDataLength',
 '96': 'RawData',
 '97': 'PossResend',
 '98': 'EncryptMethod',
 '99': 'StopPx'}
tag_by_field =  {'Account': '1',
 'AccruedInterestAmt': '159',
 'AccruedInterestRate': '158',
 'Adjustment': '334',
 'AdvId': '2',
 'AdvRefID': '3',
 'AdvSide': '4',
 'AdvTransType': '5',
 'AggregatedBook': '266',
 'AllocAccount': '79',
 'AllocAvgPx': '153',
 'AllocHandlInst': '209',
 'AllocID': '70',
 'AllocLinkID': '196',
 'AllocLinkType': '197',
 'AllocNetMoney': '154',
 'AllocPrice': '366',
 'AllocRejCode': '88',
 'AllocShares': '80',
 'AllocStatus': '87',
 'AllocText': '161',
 'AllocTransType': '71',
 'AvgPrxPrecision': '74',
 'AvgPx': '6',
 'BasisPxType': '419',
 'BeginSeqNo': '7',
 'BeginString': '8',
 'Benchmark': '219',
 'BidDescriptor': '400',
 'BidDescriptorType': '399',
 'BidForwardPoints': '189',
 'BidID': '390',
 'BidPx': '132',
 'BidRequestTransType': '374',
 'BidSize': '134',
 'BidSpotRate': '188',
 'BidType': '394',
 'BodyLength': '9',
 'BrokerOfCredit': '92',
 'BusinessRejectReason': '380',
 'BusinessRejectRefID': '379',
 'BuyVolume': '330',
 'CashOrderQty': '152',
 'CashSettlAgentAcctName': '185',
 'CashSettlAgentAcctNum': '184',
 'CashSettlAgentCode': '183',
 'CashSettlAgentContactName': '186',
 'CashSettlAgentContactPhone': '187',
 'CashSettlAgentName': '182',
 'CheckSum': '10',
 'ClOrdID': '11',
 'ClearingAccount': '440',
 'ClearingFirm': '439',
 'ClientBidID': '391',
 'ClientID': '109',
 'CommType': '13',
 'Commission': '12',
 'ComplianceID': '376',
 'ContraBroker': '375',
 'ContraTradeQty': '437',
 'ContraTradeTime': '438',
 'ContraTrader': '337',
 'ContractMultiplier': '231',
 'CorporateAction': '292',
 'Country': '421',
 'CouponRate': '223',
 'CoveredOrUncovered': '203',
 'CrossPercent': '413',
 'CumQty': '14',
 'Currency': '15',
 'CustomerOrFirm': '204',
 'CxlQty': '84',
 'CxlRejReason': '102',
 'CxlRejResponseTo': '434',
 'DKReason': '127',
 'DayAvgPx': '426',
 'DayCumQty': '425',
 'DayOrderQty': '424',
 'DefBidSize': '293',
 'DefOfferSize': '294',
 'DeleteReason': '285',
 'DeliverToCompID': '128',
 'DeliverToLocationID': '145',
 'DeliverToSubID': '129',
 'DeskID': '284',
 'DiscretionInst': '388',
 'DiscretionOffset': '389',
 'DueToRelated': '329',
 'EFPTrackingError': '405',
 'EffectiveTime': '168',
 'EmailThreadID': '164',
 'EmailType': '94',
 'EncodedAllocText': '361',
 'EncodedAllocTextLen': '360',
 'EncodedHeadline': '359',
 'EncodedHeadlineLen': '358',
 'EncodedIssuer': '349',
 'EncodedIssuerLen': '348',
 'EncodedListExecInst': '353',
 'EncodedListExecInstLen': '352',
 'EncodedListStatusText': '446',
 'EncodedListStatusTextLen': '445',
 'EncodedSecurityDesc': '351',
 'EncodedSecurityDescLen': '350',
 'EncodedSubject': '357',
 'EncodedSubjectLen': '356',
 'EncodedText': '355',
 'EncodedTextLen': '354',
 'EncodedUnderlyingIssuer': '363',
 'EncodedUnderlyingIssuerLen': '362',
 'EncodedUnderlyingSecurityDesc': '365',
 'EncodedUnderlyingSecurityDescLen': '364',
 'EncryptMethod': '98',
 'EndSeqNo': '16',
 'ExDestination': '100',
 'ExchangeForPhysical': '411',
 'ExecBroker': '76',
 'ExecID': '17',
 'ExecInst': '18',
 'ExecRefID': '19',
 'ExecRestatementReason': '378',
 'ExecTransType': '20',
 'ExecType': '150',
 'ExpireDate': '432',
 'ExpireTime': '126',
 'FairValue': '406',
 'FinancialStatus': '291',
 'ForexReq': '121',
 'FutSettDate': '64',
 'FutSettDate2': '193',
 'GTBookingInst': '427',
 'GapFillFlag': '123',
 'GrossTradeAmt': '381',
 'HaltReason': '327',
 'HandlInst': '21',
 'Headline': '148',
 'HeartBtInt': '108',
 'HighPx': '332',
 'IDSource': '22',
 'IOINaturalFlag': '130',
 'IOIQltyInd': '25',
 'IOIQualifier': '104',
 'IOIRefID': '26',
 'IOIShares': '27',
 'IOITransType': '28',
 'IOIid': '23',
 'InViewOfCommon': '328',
 'IncTaxInd': '416',
 'Issuer': '106',
 'LastCapacity': '29',
 'LastForwardPoints': '195',
 'LastMkt': '30',
 'LastMsgSeqNumProcessed': '369',
 'LastPx': '31',
 'LastShares': '32',
 'LastSpotRate': '194',
 'LeavesQty': '151',
 'LinesOfText': '33',
 'LiquidityIndType': '409',
 'LiquidityNumSecurities': '441',
 'LiquidityPctHigh': '403',
 'LiquidityPctLow': '402',
 'LiquidityValue': '404',
 'ListExecInst': '69',
 'ListExecInstType': '433',
 'ListID': '66',
 'ListName': '392',
 'ListOrderStatus': '431',
 'ListSeqNo': '67',
 'ListStatusText': '444',
 'ListStatusType': '429',
 'LocateReqd': '114',
 'LocationID': '283',
 'LowPx': '333',
 'MDEntryBuyer': '288',
 'MDEntryDate': '272',
 'MDEntryID': '278',
 'MDEntryOriginator': '282',
 'MDEntryPositionNo': '290',
 'MDEntryPx': '270',
 'MDEntryRefID': '280',
 'MDEntrySeller': '289',
 'MDEntrySize': '271',
 'MDEntryTime': '273',
 'MDEntryType': '269',
 'MDMkt': '275',
 'MDReqID': '262',
 'MDReqRejReason': '281',
 'MDUpdateAction': '279',
 'MDUpdateType': '265',
 'MarketDepth': '264',
 'MaturityDay': '205',
 'MaturityMonthYear': '200',
 'MaxFloor': '111',
 'MaxMessageSize': '383',
 'MaxShow': '210',
 'MessageEncoding': '347',
 'MinQty': '110',
 'MiscFeeAmt': '137',
 'MiscFeeCurr': '138',
 'MiscFeeType': '139',
 'MsgDirection': '385',
 'MsgSeqNum': '34',
 'MsgType': '35',
 'MultiLegReportingType': '442',
 'NetGrossInd': '430',
 'NetMoney': '118',
 'NewSeqNo': '36',
 'NoAllocs': '78',
 'NoBidComponents': '420',
 'NoBidDescriptors': '398',
 'NoContraBrokers': '382',
 'NoExecs': '124',
 'NoIOIQualifiers': '199',
 'NoMDEntries': '268',
 'NoMDEntryTypes': '267',
 'NoMiscFees': '136',
 'NoMsgTypes': '384',
 'NoOrders': '73',
 'NoQuoteEntries': '295',
 'NoQuoteSets': '296',
 'NoRelatedSym': '146',
 'NoRoutingIDs': '215',
 'NoRpts': '82',
 'NoStrikes': '428',
 'NoTradingSessions': '386',
 'NotifyBrokerOfCredit': '208',
 'NumBidders': '417',
 'NumDaysInterest': '157',
 'NumTickets': '395',
 'NumberOfOrders': '346',
 'OfferForwardPoints': '191',
 'OfferPx': '133',
 'OfferSize': '135',
 'OfferSpotRate': '190',
 'OnBehalfOfCompID': '115',
 'OnBehalfOfLocationID': '144',
 'OnBehalfOfSendingTime': '370',
 'OnBehalfOfSubID': '116',
 'OpenClose': '77',
 'OpenCloseSettleFlag': '286',
 'OptAttribute': '206',
 'OrdRejReason': '103',
 'OrdStatus': '39',
 'OrdType': '40',
 'OrderID': '37',
 'OrderQty': '38',
 'OrderQty2': '192',
 'OrigClOrdID': '41',
 'OrigSendingTime': '122',
 'OrigTime': '42',
 'OutMainCntryUIndex': '412',
 'OutsideIndexPct': '407',
 'PegDifference': '211',
 'PossDupFlag': '43',
 'PossResend': '97',
 'PrevClosePx': '140',
 'Price': '44',
 'PriceType': '423',
 'ProcessCode': '81',
 'ProgPeriodInterval': '415',
 'ProgRptReqs': '414',
 'PutOrCall': '201',
 'QuoteAckStatus': '297',
 'QuoteCancelType': '298',
 'QuoteCondition': '276',
 'QuoteEntryID': '299',
 'QuoteEntryRejectReason': '368',
 'QuoteID': '117',
 'QuoteRejectReason': '300',
 'QuoteReqID': '131',
 'QuoteRequestType': '303',
 'QuoteResponseLevel': '301',
 'QuoteSetID': '302',
 'QuoteSetValidUntilTime': '367',
 'RatioQty': '319',
 'RawData': '96',
 'RawDataLength': '95',
 'RefAllocID': '72',
 'RefMsgType': '372',
 'RefSeqNum': '45',
 'RefTagID': '371',
 'RelatdSym': '46',
 'ReportToExch': '113',
 'ResetSeqNumFlag': '141',
 'RoutingID': '217',
 'RoutingType': '216',
 'RptSeq': '83',
 'SecondaryOrderID': '198',
 'SecureData': '91',
 'SecureDataLen': '90',
 'SecurityDesc': '107',
 'SecurityExchange': '207',
 'SecurityID': '48',
 'SecurityReqID': '320',
 'SecurityRequestType': '321',
 'SecurityResponseID': '322',
 'SecurityResponseType': '323',
 'SecuritySettlAgentAcctName': '179',
 'SecuritySettlAgentAcctNum': '178',
 'SecuritySettlAgentCode': '177',
 'SecuritySettlAgentContactName': '180',
 'SecuritySettlAgentContactPhone': '181',
 'SecuritySettlAgentName': '176',
 'SecurityStatusReqID': '324',
 'SecurityTradingStatus': '326',
 'SecurityType': '167',
 'SellVolume': '331',
 'SellerDays': '287',
 'SenderCompID': '49',
 'SenderLocationID': '142',
 'SenderSubID': '50',
 'SendingTime': '52',
 'SessionRejectReason': '373',
 'SettlBrkrCode': '174',
 'SettlCurrAmt': '119',
 'SettlCurrFxRate': '155',
 'SettlCurrFxRateCalc': '156',
 'SettlCurrency': '120',
 'SettlDeliveryType': '172',
 'SettlDepositoryCode': '173',
 'SettlInstCode': '175',
 'SettlInstID': '162',
 'SettlInstMode': '160',
 'SettlInstRefID': '214',
 'SettlInstSource': '165',
 'SettlInstTransType': '163',
 'SettlLocation': '166',
 'SettlmntTyp': '63',
 'Shares': '53',
 'Side': '54',
 'SideValue1': '396',
 'SideValue2': '397',
 'SideValueInd': '401',
 'Signature': '89',
 'SignatureLength': '93',
 'SolicitedFlag': '377',
 'SpreadToBenchmark': '218',
 'StandInstDbID': '171',
 'StandInstDbName': '170',
 'StandInstDbType': '169',
 'StopPx': '99',
 'StrikePrice': '202',
 'StrikeTime': '443',
 'Subject': '147',
 'SubscriptionRequestType': '263',
 'Symbol': '55',
 'SymbolSfx': '65',
 'TargetCompID': '56',
 'TargetLocationID': '143',
 'TargetSubID': '57',
 'TestReqID': '112',
 'Text': '58',
 'TickDirection': '274',
 'TimeInForce': '59',
 'TotNoStrikes': '422',
 'TotQuoteEntries': '304',
 'TotalNumSecurities': '393',
 'TotalVolumeTraded': '387',
 'TradSesCloseTime': '344',
 'TradSesEndTime': '345',
 'TradSesMethod': '338',
 'TradSesMode': '339',
 'TradSesOpenTime': '342',
 'TradSesPreCloseTime': '343',
 'TradSesReqID': '335',
 'TradSesStartTime': '341',
 'TradSesStatus': '340',
 'TradeCondition': '277',
 'TradeDate': '75',
 'TradeType': '418',
 'TradingSessionID': '336',
 'TransactTime': '60',
 'URLLink': '149',
 'UnderlyingContractMultiplier': '436',
 'UnderlyingCouponRate': '435',
 'UnderlyingIDSource': '305',
 'UnderlyingIssuer': '306',
 'UnderlyingMaturityDay': '314',
 'UnderlyingMaturityMonthYear': '313',
 'UnderlyingOptAttribute': '317',
 'UnderlyingPutOrCall': '315',
 'UnderlyingSecurityDesc': '307',
 'UnderlyingSecurityExchange': '308',
 'UnderlyingSecurityID': '309',
 'UnderlyingSecurityType': '310',
 'UnderlyingStrikePrice': '316',
 'UnderlyingSymbol': '311',
 'UnderlyingSymbolSfx': '312',
 'UnsolicitedIndicator': '325',
 'Urgency': '61',
 'ValidUntilTime': '62',
 'ValueOfFutures': '408',
 'WaveNo': '105',
 'WtAverageLiquidity': '410',
 'XmlData': '213',
 'XmlDataLen': '212'}
desc_by_tag_value =  {'1': {},
 '10': {},
 '100': {},
 '102': {'0': 'Too late to cancel',
         '1': 'Unknown order',
         '2': 'Broker Option',
         '3': 'Order already in Pending Cancel or Pending Replace status'},
 '103': {'0': 'Broker option',
         '1': 'Unknown symbol',
         '2': 'Exchange closed',
         '3': 'Order exceeds limit',
         '4': 'Too late to enter',
         '5': 'Unknown Order',
         '6': 'Duplicate Order (e.g. dupe ',
         '7': 'Duplicate of a verbally communicated order',
         '8': 'Stale Order'},
 '104': {'A': 'All or none',
         'C': 'At the close',
         'I': 'In touch with',
         'L': 'Limit',
         'M': 'More behind',
         'O': 'At the open',
         'P': 'Taking a position',
         'Q': 'At the Market (previously called Current ',
         'R': 'Ready to trade',
         'S': 'Portfolio show-n',
         'T': 'Through the day',
         'V': 'Versus',
         'W': 'Indication - Working away',
         'X': 'Crossing opportunity',
         'Y': 'At the Midpoint',
         'Z': 'Pre-open'},
 '105': {},
 '106': {},
 '107': {},
 '108': {},
 '109': {},
 '11': {},
 '110': {},
 '111': {},
 '112': {},
 '113': {'N': 'Indicates that party sending message will report trade',
         'Y': 'Indicates that party receiving message must report trade'},
 '114': {'N': 'Indicates the broker is not required to locate',
         'Y': 'Indicates the broker is responsible for locating the stock'},
 '115': {},
 '116': {},
 '117': {},
 '118': {},
 '119': {},
 '12': {},
 '120': {},
 '121': {'N': 'Do not execute Forex after security trade',
         'Y': 'Execute Forex after security trade'},
 '122': {},
 '123': {'N': 'Sequence Reset <4>', 'Y': 'Gap Fill message, '},
 '124': {},
 '126': {},
 '127': {'A': 'Unknown symbol',
         'B': 'Wrong side',
         'C': 'Quantity exceeds order',
         'D': 'No matching order',
         'E': 'Price <44>',
         'Z': 'Other'},
 '128': {},
 '129': {},
 '13': {'1': 'per share', '2': 'percentage', '3': 'absolute'},
 '130': {'N': 'Not natural', 'Y': 'Natural'},
 '131': {},
 '132': {},
 '133': {},
 '134': {},
 '135': {},
 '136': {},
 '137': {},
 '138': {},
 '139': {'1': 'Regulatory (e.g. SEC)',
         '2': 'Tax',
         '3': 'Local ',
         '4': 'Exchange Fees',
         '5': 'Stamp',
         '6': 'Levy',
         '7': 'Other',
         '8': 'Markup',
         '9': 'Consumption Tax'},
 '14': {},
 '140': {},
 '141': {'N': 'No', 'Y': 'Yes, reset sequence numbers'},
 '142': {},
 '143': {},
 '144': {},
 '145': {},
 '146': {},
 '147': {},
 '148': {},
 '149': {},
 '15': {},
 '150': {'0': 'New',
         '1': 'Partial fill',
         '2': 'Fill',
         '3': 'Done for day',
         '4': 'Canceled',
         '5': 'Replace',
         '6': 'Pending Cancel (e.g. result of ',
         '7': 'Stopped',
         '8': 'Rejected',
         '9': 'Suspended',
         'A': 'Pending New',
         'B': 'Calculated',
         'C': 'Expired',
         'D': 'Restated (ExecutionRpt sent unsolicited by sellside, with ',
         'E': 'Pending Replace (e.g. result of '},
 '151': {},
 '152': {},
 '153': {},
 '154': {},
 '155': {},
 '156': {},
 '157': {},
 '158': {},
 '159': {},
 '16': {},
 '160': {'0': 'Default',
         '1': 'Standing Instructions Provided',
         '2': 'Specific ',
         '3': 'Specific '},
 '161': {},
 '162': {},
 '163': {'C': 'Cancel', 'N': 'New', 'R': 'Replace'},
 '164': {},
 '165': {'1': "Broker's Instructions", '2': "Institution's Instructions"},
 '166': {'CED': 'CEDEL',
         'DTC': 'Depository Trust Company',
         'EUR': 'Euroclear',
         'FED': 'Federal Book Entry',
         'PTC': 'Participant Trust Company'},
 '167': {'?': "'Wildcard' entry (used on ",
         'BA': 'Bankers Acceptance',
         'CB': 'Convertible Bond (Note not part of ISITC spec)',
         'CD': 'Certificate Of Deposit',
         'CMO': 'Collateralize Mortgage Obligation',
         'CORP': 'Corporate Bond',
         'CP': 'Commercial Paper',
         'CPP': 'Corporate Private Placement',
         'CS': 'Common Stock',
         'FHA': 'Federal Housing Authority',
         'FHL': 'Federal Home Loan',
         'FN': 'Federal National Mortgage Association',
         'FOR': 'Foreign Exchange Contract',
         'FUT': 'Future',
         'GN': 'Government National Mortgage Association',
         'GOVT': 'Treasuries + Agency Debenture',
         'MF': 'Mutual Fund',
         'MIO': 'Mortgage Interest Only',
         'MPO': 'Mortgage Principal Only',
         'MPP': 'Mortgage Private Placement',
         'MPT': 'Miscellaneous Pass-Thru',
         'MUNI': 'Municipal Bond',
         'NONE': 'No ISITC Security Type',
         'OPT': 'Option',
         'PS': 'Preferred Stock',
         'RP': 'Repurchase Agreement',
         'RVRP': 'Reverse Repurchase Agreement',
         'SL': 'Student Loan Marketing Association',
         'TD': 'Time Deposit',
         'USTB': 'US Treasury Bill',
         'WAR': 'Warrant',
         'ZOO': 'Cats, Tigers & Lions (a real code: US Treasury Receipts)'},
 '168': {},
 '169': {'0': 'Other',
         '1': 'DTC SID',
         '2': 'Thomson ALERT',
         '3': 'A Global Custodian ('},
 '17': {},
 '170': {},
 '171': {},
 '172': {},
 '173': {},
 '174': {},
 '175': {},
 '176': {},
 '177': {},
 '178': {},
 '179': {},
 '18': {'0': 'Stay on offerside',
        '1': 'Not held',
        '2': 'Work',
        '3': 'Go along',
        '4': 'Over the day',
        '5': 'Held',
        '6': "Participate don't initiate",
        '7': 'Strict scale',
        '8': 'Try to scale',
        '9': 'Stay on bidside',
        'A': 'No cross (cross is forbidden)',
        'B': 'OK to cross',
        'C': 'Call first',
        'D': "Percent of volume '(indicates that the sender does not want to "
             "be all of the volume on the floor vs. a specific percentage)'",
        'E': 'Do not increase - DNI',
        'F': 'Do not reduce - DNR',
        'G': 'All or none - AON',
        'I': 'Institutions only',
        'L': 'Last peg (last sale)',
        'M': 'Mid-price peg (midprice of inside quote)',
        'N': 'Non-negotiable',
        'O': 'Opening peg',
        'P': 'Market peg',
        'R': 'Primary peg (primary market - buy at bid/sell at offer)',
        'S': 'Suspend',
        'T': 'Fixed Peg to Local best bid or offer at time of order',
        'U': 'Customer Display Instruction (Rule11Ac1-1/4)',
        'V': 'Netting (for Forex)',
        'W': 'Peg to VWAP'},
 '180': {},
 '181': {},
 '182': {},
 '183': {},
 '184': {},
 '185': {},
 '186': {},
 '187': {},
 '188': {},
 '189': {},
 '19': {},
 '190': {},
 '191': {},
 '192': {},
 '193': {},
 '194': {},
 '195': {},
 '196': {},
 '197': {'0': 'F/X Netting', '1': 'F/X Swap'},
 '198': {},
 '199': {},
 '2': {},
 '20': {'0': 'New', '1': 'Cancel', '2': 'Correct', '3': 'Status'},
 '200': {},
 '201': {'0': 'Put', '1': 'Call'},
 '202': {},
 '203': {'0': 'Covered', '1': 'Uncovered'},
 '204': {'0': 'Customer', '1': 'Firm'},
 '205': {},
 '206': {},
 '207': {},
 '208': {'N': 'Details should not be communicated',
         'Y': 'Details should be communicated'},
 '209': {'1': 'Match', '2': 'Forward', '3': 'Forward and Match'},
 '21': {'1': 'Automated execution order, private, no Broker intervention',
        '2': 'Automated execution order, public, Broker intervention OK',
        '3': 'Manual order, best execution'},
 '210': {},
 '211': {},
 '212': {},
 '213': {},
 '214': {},
 '215': {},
 '216': {'1': 'Target Firm',
         '2': 'Target List',
         '3': 'Block Firm',
         '4': 'Block List'},
 '217': {},
 '218': {},
 '219': {'1': 'CURVE',
         '2': '5-YR',
         '3': 'OLD-5',
         '4': '10-YR',
         '5': 'OLD-10',
         '6': '30-YR',
         '7': 'OLD-30',
         '8': '3-MO-LIBOR',
         '9': '6-MO-LIBOR'},
 '22': {'1': 'CUSIP',
        '2': 'SEDOL',
        '3': 'QUIK',
        '4': 'ISIN number',
        '5': 'RIC code',
        '6': 'ISO ',
        '7': 'ISO ',
        '8': 'Exchange ',
        '9': 'Consolidated Tape Association (CTA) '},
 '223': {},
 '23': {},
 '231': {},
 '25': {'H': 'High', 'L': 'Low', 'M': 'Medium'},
 '26': {},
 '262': {},
 '263': {'0': 'Snapshot',
         '1': 'Snapshot + Updates (Subscribe)',
         '2': 'Disable previous Snapshot + Update Request (Unsubscribe)'},
 '264': {'0': 'Full Book',
         '1': 'Top of Book',
         'N>1': 'Report best N price tiers of data'},
 '265': {'0': 'Full Refresh', '1': 'Incremental Refresh'},
 '266': {'N': 'Multiple entries per side per price allowed',
         'Y': 'one book entry per side per price'},
 '267': {},
 '268': {},
 '269': {'0': 'Bid',
         '1': 'Offer',
         '2': 'Trade',
         '3': 'Index Value',
         '4': 'Opening ',
         '5': 'Closing ',
         '6': 'Settlement ',
         '7': 'Trading Session High ',
         '8': 'Trading Session Low ',
         '9': 'Trading Session VWAP '},
 '27': {'L': 'Large', 'M': 'Medium', 'S': 'Small'},
 '270': {},
 '271': {},
 '272': {},
 '273': {},
 '274': {'0': 'Plus Tick',
         '1': 'Zero-Plus Tick',
         '2': 'Minus Tick',
         '3': 'Zero-Minus Tick'},
 '275': {},
 '276': {'A': 'Open / Active',
         'B': 'Closed / Inactive',
         'C': 'Exchange Best',
         'D': 'Consolidated Best',
         'E': 'Locked',
         'F': 'Crossed',
         'G': 'Depth',
         'H': 'Fast Trading',
         'I': 'Non-Firm'},
 '277': {'A': 'Cash (only) Market',
         'B': 'Average ',
         'C': 'Cash Trade (same day clearing)',
         'D': 'Next Day (only) Market',
         'E': 'Opening / Reopening Trade Detail',
         'F': 'Intraday Trade Detail',
         'G': 'Rule 127 Trade (NYSE)',
         'H': 'Rule 155 Trade (Amex)',
         'I': 'Sold Last (late reporting)',
         'J': 'Next Day Trade (next day clearing)',
         'K': 'Opened (late report of opened trade)',
         'L': 'Seller',
         'M': 'Sold (out of sequence)',
         'N': 'Stopped Stock (guarantee of price but does not execute the '
              'order)'},
 '278': {},
 '279': {'0': 'New', '1': 'Change', '2': 'Delete'},
 '28': {'C': 'Cancel', 'N': 'New', 'R': 'Replace'},
 '280': {},
 '281': {'0': 'Unknown symbol',
         '1': 'Duplicate ',
         '2': 'Insufficient Bandwidth',
         '3': 'Insufficient Permissions',
         '4': 'Unsupported ',
         '5': 'Unsupported ',
         '6': 'Unsupported ',
         '7': 'Unsupported ',
         '8': 'Unsupported '},
 '282': {},
 '283': {},
 '284': {},
 '285': {'0': 'Cancelation / Trade Bust', '1': 'Error'},
 '286': {'0': 'Daily Open / Close / Settlement price',
         '1': 'Session Open / Close / Settlement price',
         '2': 'Delivery Settlement price'},
 '287': {},
 '288': {},
 '289': {},
 '29': {'1': 'Agent',
        '2': 'Cross as agent',
        '3': 'Cross as principal',
        '4': 'Principal'},
 '290': {},
 '291': {'1': 'Bankrupt'},
 '292': {'A': 'Ex-Dividend',
         'B': 'Ex-Distribution',
         'C': 'Ex-Rights',
         'D': 'New',
         'E': 'Ex-Interest'},
 '293': {},
 '294': {},
 '295': {},
 '296': {},
 '297': {},
 '298': {},
 '299': {},
 '3': {},
 '30': {},
 '300': {'1': 'Unknown symbol (Security)',
         '2': 'Exchange(Security) closed',
         '3': 'Quote <S>',
         '4': 'Too late to enter',
         '5': 'Unknown ',
         '6': 'Duplicate ',
         '7': 'Invalid bid/ask spread',
         '8': 'Invalid price',
         '9': 'Not authorized to quote security'},
 '301': {},
 '302': {},
 '303': {},
 '304': {},
 '305': {},
 '306': {},
 '307': {},
 '308': {},
 '309': {},
 '31': {},
 '310': {},
 '311': {},
 '312': {},
 '313': {},
 '314': {},
 '315': {},
 '316': {},
 '317': {},
 '319': {},
 '32': {},
 '320': {},
 '321': {'0': 'Request Security identity and specifications',
         '1': 'Request Security identity for the specifications provided (Name '
              'of the security is not supplied)',
         '2': 'Request List Security Types',
         '3': 'Request List Securities (Can be qualified with '},
 '322': {},
 '323': {'1': 'Accept security proposal as is',
         '2': 'Accept security proposal with revisions as indicated in the '
              'message',
         '3': 'List of security types returned per request',
         '4': 'List of securities returned per request',
         '5': 'Reject <3>',
         '6': 'Can not match selection criteria'},
 '324': {},
 '325': {'N': 'Message is being sent as a result of a prior request',
         'Y': 'Message is being sent unsolicited'},
 '326': {'1': 'Opening Delay',
         '10': 'Market On Close Imbalance Sell',
         '11': '(not assigned)',
         '12': 'No Market Imbalance',
         '13': 'No Market On Close Imbalance',
         '14': 'ITS Pre-Opening',
         '15': 'New ',
         '16': 'Trade Dissemination Time',
         '17': 'Ready to trade (start of session)',
         '18': 'Not Available for trading (end of session)',
         '19': 'Not Traded on this Market',
         '2': 'Trading Halt',
         '20': 'Unknown or Invalid',
         '3': 'Resume',
         '4': 'No Open/No Resume',
         '5': 'Price <44>',
         '6': 'Trading Range Indication',
         '7': 'Market Imbalance Buy',
         '8': 'Market Imbalance Sell',
         '9': 'Market On Close Imbalance Buy'},
 '327': {'D': 'News <B>',
         'E': 'Order Influx',
         'I': 'Order Imbalance',
         'M': 'Additional Information',
         'P': 'News <B>',
         'X': 'Equipment Changeover'},
 '328': {'N': 'Halt was not related to a halt of the common stock',
         'Y': 'Halt was due to common stock being halted'},
 '329': {'N': 'Halt was not related to a halt of the related security',
         'Y': 'Halt was due to related security being halted'},
 '33': {},
 '330': {},
 '331': {},
 '332': {},
 '333': {},
 '334': {'1': 'Cancel', '2': 'Error', '3': 'Correction'},
 '335': {},
 '336': {},
 '337': {},
 '338': {'1': 'Electronic', '2': 'Open Outcry', '3': 'Two Party'},
 '339': {'1': 'Testing', '2': 'Simulated', '3': 'Production'},
 '34': {},
 '340': {'1': 'Halted',
         '2': 'Open',
         '3': 'Closed',
         '4': 'Pre-Open',
         '5': 'Pre-Close'},
 '341': {},
 '342': {},
 '343': {},
 '344': {},
 '345': {},
 '346': {},
 '347': {},
 '348': {},
 '349': {},
 '35': {'0': 'Heartbeat <0>',
        '1': 'Test Request <1>',
        '2': 'Resend Request <2>',
        '3': 'Reject <3>',
        '4': 'Sequence Reset <4>',
        '5': 'Logout <5>',
        '6': 'Indication of Interest <6>',
        '7': 'Advertisement <7>',
        '8': 'Execution Report <8>',
        '9': 'Order Cancel Reject <9>',
        'A': 'Logon <A>',
        'B': 'News <B>',
        'C': 'Email <C>',
        'D': 'Order - Single <D>',
        'E': 'Order - List <E>',
        'F': 'Order Cancel Request <F>',
        'J': 'Allocation <J>',
        'K': 'List Cancel Request <K>',
        'L': 'List Execute <L>',
        'M': 'List Status Request <M>',
        'N': 'List Status <N>',
        'P': 'Allocation ACK <P>',
        'Q': "Don't Know Trade <Q>",
        'R': 'Quote Request <R>',
        'S': 'Quote <S>',
        'T': 'Settlement Instructions <T>',
        'V': 'Market Data Request <V>',
        'W': 'Market Data-Snapshot/Full Refresh',
        'X': 'Market Data-Incremental Refresh',
        'Y': 'Market Data Request Reject <Y>',
        'Z': 'Quote Cancel <Z>',
        'a': 'Quote Status Request <a>',
        'b': 'Quote Acknowledgement <b>',
        'c': 'Security Definition Request <c>',
        'd': 'Security Definition <d>',
        'e': 'Security Status Request <e>',
        'f': 'Security Status <f>',
        'g': 'Trading Session Status Request <g>',
        'h': 'Trading Session Status <h>',
        'i': 'Mass Quote <i>',
        'j': 'Business Message Reject <j>',
        'k': 'Bid Request <k>',
        'l': 'Bid Response <l>',
        'm': 'List Strike '},
 '350': {},
 '351': {},
 '352': {},
 '353': {},
 '354': {},
 '355': {},
 '356': {},
 '357': {},
 '358': {},
 '359': {},
 '36': {},
 '360': {},
 '361': {},
 '362': {},
 '363': {},
 '364': {},
 '365': {},
 '366': {},
 '367': {},
 '368': {'1': 'Unknown symbol (Security)',
         '2': 'Exchange(Security) closed',
         '3': 'Quote <S>',
         '4': 'Too late to enter',
         '5': 'Unknown ',
         '6': 'Duplicate ',
         '7': 'Invalid bid/ask spread',
         '8': 'Invalid price',
         '9': 'Not authorized to quote security'},
 '369': {},
 '37': {},
 '370': {},
 '371': {},
 '372': {},
 '373': {'0': 'Invalid tag number',
         '1': 'Required tag missing',
         '10': 'SendingTime <52>',
         '11': 'Invalid ',
         '2': 'Tag not defined for this message type',
         '3': 'Undefined Tag',
         '4': 'Tag specified without a value',
         '5': 'Value is incorrect (out of range) for this tag',
         '6': 'Incorrect data format for value',
         '7': 'Decryption problem',
         '8': 'Signature <89>',
         '9': 'CompID problem'},
 '374': {'C': 'Cancel', 'N': 'New'},
 '375': {},
 '376': {},
 '377': {'N': 'Was not solicited', 'Y': 'Was solcitied'},
 '378': {'0': 'GT Corporate action',
         '1': 'GT renewal / restatement (no corporate action)',
         '2': 'Verbal change',
         '3': 'Repricing of order',
         '4': 'Broker option',
         '5': 'Partial decline of '},
 '379': {},
 '38': {},
 '380': {'0': 'Other',
         '1': 'Unkown ID',
         '2': 'Unknown Security',
         '3': 'Unsupported Message Type',
         '4': 'Application not available',
         '5': 'Conditionally Required Field Missing'},
 '381': {},
 '382': {},
 '383': {},
 '384': {},
 '385': {'R': 'Receive', 'S': 'Send'},
 '386': {},
 '387': {},
 '388': {'0': 'Related to displayed price',
         '1': 'Related to market price',
         '2': 'Related to primary price',
         '3': 'Related to local primary price',
         '4': 'Related to midpoint price',
         '5': 'Related to last trade price'},
 '389': {},
 '39': {'0': 'New',
        '1': 'Partially filled',
        '2': 'Filled',
        '3': 'Done for day',
        '4': 'Canceled',
        '5': 'Replaced',
        '6': 'Pending Cancel (e.g. result of ',
        '7': 'Stopped',
        '8': 'Rejected',
        '9': 'Suspended',
        'A': 'Pending New',
        'B': 'Calculated',
        'C': 'Expired',
        'D': 'Accepted for bidding',
        'E': 'Pending Replace (e.g. result of '},
 '390': {},
 '391': {},
 '392': {},
 '393': {},
 '394': {},
 '395': {},
 '396': {},
 '397': {},
 '398': {},
 '399': {},
 '4': {'B': 'Buy', 'S': 'Sell', 'T': 'Trade', 'X': 'Cross'},
 '40': {'1': 'Market',
        '2': 'Limit',
        '3': 'Stop',
        '4': 'Stop limit',
        '5': 'Market on close',
        '6': 'With or without',
        '7': 'Limit or better',
        '8': 'Limit with or without',
        '9': 'On basis',
        'A': 'On close',
        'B': 'Limit on close',
        'D': 'Previously quoted',
        'E': 'Previously indicated',
        'F': 'Forex - Limit',
        'G': 'Forex - Swap',
        'H': 'Forex - Previously Quoted',
        'I': 'Funari (Limit Day Order with unexecuted portion handled as '
             'Market On Close. e.g. Japan)',
        'P': 'Pegged'},
 '400': {},
 '401': {},
 '402': {},
 '403': {},
 '404': {},
 '405': {},
 '406': {},
 '407': {},
 '408': {},
 '409': {},
 '41': {},
 '410': {},
 '411': {'N': 'False', 'Y': 'True'},
 '412': {},
 '413': {},
 '414': {},
 '415': {},
 '416': {},
 '417': {},
 '418': {},
 '419': {},
 '42': {},
 '420': {},
 '421': {},
 '422': {},
 '423': {},
 '424': {},
 '425': {},
 '426': {},
 '427': {'0': 'book out all trades on day of execution',
         '1': 'accumulate executions until order is filled or expires',
         '2': 'accumulate until verbally notified otherwise'},
 '428': {},
 '429': {},
 '43': {'N': 'Original transmission', 'Y': 'Possible duplicate'},
 '430': {},
 '431': {},
 '432': {},
 '433': {},
 '434': {},
 '435': {},
 '436': {},
 '437': {},
 '438': {},
 '439': {},
 '44': {},
 '440': {},
 '441': {},
 '442': {},
 '443': {},
 '444': {},
 '445': {},
 '446': {},
 '45': {},
 '46': {},
 '48': {},
 '49': {},
 '5': {'C': 'Cancel', 'N': 'New', 'R': 'Replace'},
 '50': {},
 '52': {},
 '53': {},
 '54': {'1': 'Buy',
        '2': 'Sell',
        '3': 'Buy minus',
        '4': 'Sell plus',
        '5': 'Sell short',
        '6': 'Sell short exempt',
        '7': 'Undisclosed (valid for IOI and List Order messages only)',
        '8': 'Cross (orders where counterparty is an exchange, valid for all '
             'messages except IOIs)',
        '9': 'Cross short'},
 '55': {},
 '56': {},
 '564': {},
 '57': {},
 '58': {},
 '59': {'0': 'Day',
        '1': 'Good Till Cancel (GTC)',
        '2': 'At the Opening (OPG)',
        '3': 'Immediate or Cancel (IOC)',
        '4': 'Fill or Kill (FOK)',
        '5': 'Good Till Crossing (GTX)',
        '6': 'Good Till Date'},
 '6': {},
 '60': {},
 '61': {'0': 'Normal', '1': 'Flash', '2': 'Background'},
 '62': {},
 '624': {'1': 'Buy',
         '2': 'Sell',
         '3': 'Buy minus',
         '4': 'Sell plus',
         '5': 'Sell short',
         '6': 'Sell short exempt',
         '7': 'Undisclosed (valid for IOI and List Order messages only)',
         '8': 'Cross (orders where counterparty is an exchange, valid for all '
              'messages except IOIs)',
         '9': 'Cross short'},
 '63': {'0': 'Regular',
        '1': 'Cash',
        '2': 'Next Day',
        '3': 'T+2',
        '4': 'T+3',
        '5': 'T+4',
        '6': 'Future',
        '7': 'When Issued',
        '8': 'Sellers Option',
        '9': 'T+ 5'},
 '64': {},
 '65': {},
 '66': {},
 '67': {},
 '69': {},
 '7': {},
 '70': {},
 '71': {'0': 'New',
        '1': 'Replace',
        '2': 'Cancel',
        '3': 'Preliminary (without MiscFees and ',
        '4': 'Calculated (includes MiscFees and ',
        '5': 'Calculated without Preliminary (sent unsolicited by broker, '
             'includes MiscFees and '},
 '72': {},
 '73': {},
 '74': {},
 '75': {},
 '76': {},
 '77': {},
 '78': {},
 '79': {},
 '8': {},
 '80': {},
 '81': {'0': 'regular',
        '1': 'soft dollar',
        '2': 'step-in',
        '3': 'step-out',
        '4': 'soft-dollar step-in',
        '5': 'soft-dollar step-out',
        '6': 'plan sponsor'},
 '82': {},
 '83': {},
 '84': {},
 '87': {'0': 'accepted (successfully processed)',
        '1': 'rejected',
        '2': 'partial accept',
        '3': 'received (received, not yet processed)'},
 '88': {'0': 'unknown account(s)',
        '1': 'incorrect quantity',
        '2': 'incorrect average price',
        '3': 'unknown executing broker mnemonic',
        '4': 'commission difference',
        '5': 'unknown ',
        '6': 'unknown ',
        '7': 'other'},
 '89': {},
 '9': {},
 '90': {},
 '91': {},
 '92': {},
 '93': {},
 '94': {'0': 'New', '1': 'Reply', '2': 'Admin Reply'},
 '95': {},
 '96': {},
 '97': {},
 '98': {'0': 'None / other',
        '1': 'PKCS (proprietary)',
        '2': 'DES (ECB mode)',
        '3': 'PKCS/DES (proprietary)',
        '4': 'PGP/DES (defunct)',
        '5': 'PGP/DES-MD5 (see app note on FIX web site)',
        '6': 'PEM/DES-MD5 (see app note on FIX web site)'},
 '99': {}}
