field_by_tag =  {'1': 'Account',
 '10': 'CheckSum',
 '100': 'ExDestination',
 '102': 'CxlRejReason',
 '103': 'OrdRejReason',
 '104': 'IOIQualifier',
 '105': 'WaveNo',
 '106': 'Issuer',
 '107': 'SecurityDesc',
 '108': 'HeartBtInt',
 '109': 'ClientID',
 '11': 'ClOrdID',
 '110': 'MinQty',
 '111': 'MaxFloor',
 '112': 'TestReqID',
 '113': 'ReportToExch',
 '114': 'LocateReqd',
 '115': 'OnBehalfOfCompID',
 '116': 'OnBehalfOfSubID',
 '117': 'QuoteID',
 '118': 'NetMoney',
 '119': 'SettlCurrAmt',
 '12': 'Commission',
 '120': 'SettlCurrency',
 '121': 'ForexReq',
 '122': 'OrigSendingTime',
 '123': 'GapFillFlag',
 '124': 'NoExecs',
 '125': 'CxlType',
 '126': 'ExpireTime',
 '127': 'DKReason',
 '128': 'DeliverToCompID',
 '129': 'DeliverToSubID',
 '13': 'CommType',
 '130': 'IOINaturalFlag',
 '131': 'QuoteReqID',
 '132': 'BidPx',
 '133': 'OfferPx',
 '134': 'BidSize',
 '135': 'OfferSize',
 '136': 'NoMiscFees',
 '137': 'MiscFeeAmt',
 '138': 'MiscFeeCurr',
 '139': 'MiscFeeType',
 '14': 'CumQty',
 '140': 'PrevClosePx',
 '15': 'Currency',
 '16': 'EndSeqNo',
 '17': 'ExecID',
 '18': 'ExecInst',
 '19': 'ExecRefID',
 '2': 'AdvId',
 '20': 'ExecTransType',
 '21': 'HandlInst',
 '22': 'IDSource',
 '23': 'IOIid',
 '24': 'IOIOthSvc',
 '25': 'IOIQltyInd',
 '26': 'IOIRefID',
 '27': 'IOIShares',
 '28': 'IOITransType',
 '29': 'LastCapacity',
 '3': 'AdvRefID',
 '30': 'LastMkt',
 '31': 'LastPx',
 '32': 'LastShares',
 '33': 'LinesOfText',
 '34': 'MsgSeqNum',
 '35': 'MsgType',
 '36': 'NewSeqNo',
 '37': 'OrderID',
 '38': 'OrderQty',
 '39': 'OrdStatus',
 '4': 'AdvSide',
 '40': 'OrdType',
 '41': 'OrigClOrdID',
 '42': 'OrigTime',
 '43': 'PossDupFlag',
 '44': 'Price',
 '45': 'RefSeqNum',
 '46': 'RelatdSym',
 '47': 'Rule80A',
 '48': 'SecurityID',
 '49': 'SenderCompID',
 '5': 'AdvTransType',
 '50': 'SenderSubID',
 '52': 'SendingTime',
 '53': 'Shares',
 '54': 'Side',
 '55': 'Symbol',
 '56': 'TargetCompID',
 '57': 'TargetSubID',
 '58': 'Text',
 '59': 'TimeInForce',
 '6': 'AvgPx',
 '60': 'TransactTime',
 '61': 'Urgency',
 '62': 'ValidUntilTime',
 '63': 'SettlmntTyp',
 '64': 'FutSettDate',
 '65': 'SymbolSfx',
 '66': 'ListID',
 '67': 'ListSeqNo',
 '68': 'ListNoOrds',
 '69': 'ListExecInst',
 '7': 'BeginSeqNo',
 '70': 'AllocID',
 '71': 'AllocTransType',
 '72': 'RefAllocID',
 '73': 'NoOrders',
 '74': 'AvgPrxPrecision',
 '75': 'TradeDate',
 '76': 'ExecBroker',
 '77': 'OpenClose',
 '78': 'NoAllocs',
 '79': 'AllocAccount',
 '8': 'BeginString',
 '80': 'AllocShares',
 '81': 'ProcessCode',
 '82': 'NoRpts',
 '83': 'RptSeq',
 '84': 'CxlQty',
 '85': 'NoDlvyInst',
 '86': 'DlvyInst',
 '87': 'AllocStatus',
 '88': 'AllocRejCode',
 '89': 'Signature',
 '9': 'BodyLength',
 '90': 'SecureDataLen',
 '91': 'SecureData',
 '92': 'BrokerOfCredit',
 '93': 'SignatureLength',
 '94': 'EmailType',
 '95': 'RawDataLength',
 '96': 'RawData',
 '97': 'PossResend',
 '98': 'EncryptMethod',
 '99': 'StopPx'}
tag_by_field =  {'Account': '1',
 'AdvId': '2',
 'AdvRefID': '3',
 'AdvSide': '4',
 'AdvTransType': '5',
 'AllocAccount': '79',
 'AllocID': '70',
 'AllocRejCode': '88',
 'AllocShares': '80',
 'AllocStatus': '87',
 'AllocTransType': '71',
 'AvgPrxPrecision': '74',
 'AvgPx': '6',
 'BeginSeqNo': '7',
 'BeginString': '8',
 'BidPx': '132',
 'BidSize': '134',
 'BodyLength': '9',
 'BrokerOfCredit': '92',
 'CheckSum': '10',
 'ClOrdID': '11',
 'ClientID': '109',
 'CommType': '13',
 'Commission': '12',
 'CumQty': '14',
 'Currency': '15',
 'CxlQty': '84',
 'CxlRejReason': '102',
 'CxlType': '125',
 'DKReason': '127',
 'DeliverToCompID': '128',
 'DeliverToSubID': '129',
 'DlvyInst': '86',
 'EmailType': '94',
 'EncryptMethod': '98',
 'EndSeqNo': '16',
 'ExDestination': '100',
 'ExecBroker': '76',
 'ExecID': '17',
 'ExecInst': '18',
 'ExecRefID': '19',
 'ExecTransType': '20',
 'ExpireTime': '126',
 'ForexReq': '121',
 'FutSettDate': '64',
 'GapFillFlag': '123',
 'HandlInst': '21',
 'HeartBtInt': '108',
 'IDSource': '22',
 'IOINaturalFlag': '130',
 'IOIOthSvc': '24',
 'IOIQltyInd': '25',
 'IOIQualifier': '104',
 'IOIRefID': '26',
 'IOIShares': '27',
 'IOITransType': '28',
 'IOIid': '23',
 'Issuer': '106',
 'LastCapacity': '29',
 'LastMkt': '30',
 'LastPx': '31',
 'LastShares': '32',
 'LinesOfText': '33',
 'ListExecInst': '69',
 'ListID': '66',
 'ListNoOrds': '68',
 'ListSeqNo': '67',
 'LocateReqd': '114',
 'MaxFloor': '111',
 'MinQty': '110',
 'MiscFeeAmt': '137',
 'MiscFeeCurr': '138',
 'MiscFeeType': '139',
 'MsgSeqNum': '34',
 'MsgType': '35',
 'NetMoney': '118',
 'NewSeqNo': '36',
 'NoAllocs': '78',
 'NoDlvyInst': '85',
 'NoExecs': '124',
 'NoMiscFees': '136',
 'NoOrders': '73',
 'NoRpts': '82',
 'OfferPx': '133',
 'OfferSize': '135',
 'OnBehalfOfCompID': '115',
 'OnBehalfOfSubID': '116',
 'OpenClose': '77',
 'OrdRejReason': '103',
 'OrdStatus': '39',
 'OrdType': '40',
 'OrderID': '37',
 'OrderQty': '38',
 'OrigClOrdID': '41',
 'OrigSendingTime': '122',
 'OrigTime': '42',
 'PossDupFlag': '43',
 'PossResend': '97',
 'PrevClosePx': '140',
 'Price': '44',
 'ProcessCode': '81',
 'QuoteID': '117',
 'QuoteReqID': '131',
 'RawData': '96',
 'RawDataLength': '95',
 'RefAllocID': '72',
 'RefSeqNum': '45',
 'RelatdSym': '46',
 'ReportToExch': '113',
 'RptSeq': '83',
 'Rule80A': '47',
 'SecureData': '91',
 'SecureDataLen': '90',
 'SecurityDesc': '107',
 'SecurityID': '48',
 'SenderCompID': '49',
 'SenderSubID': '50',
 'SendingTime': '52',
 'SettlCurrAmt': '119',
 'SettlCurrency': '120',
 'SettlmntTyp': '63',
 'Shares': '53',
 'Side': '54',
 'Signature': '89',
 'SignatureLength': '93',
 'StopPx': '99',
 'Symbol': '55',
 'SymbolSfx': '65',
 'TargetCompID': '56',
 'TargetSubID': '57',
 'TestReqID': '112',
 'Text': '58',
 'TimeInForce': '59',
 'TradeDate': '75',
 'TransactTime': '60',
 'Urgency': '61',
 'ValidUntilTime': '62',
 'WaveNo': '105'}
desc_by_tag_value =  {'1': {},
 '10': {},
 '100': {'0': 'none', '4': 'POSIT'},
 '102': {'0': 'Too late to cancel', '1': 'Unknown order'},
 '103': {'0': 'Broker option',
         '1': 'Unknown symbol',
         '2': 'Exchange closed',
         '3': 'Order exceeds limit',
         '4': 'Too late to enter'},
 '104': {'A': 'All or none',
         'C': 'At the close',
         'I': 'In touch with',
         'L': 'Limit',
         'M': 'More behind',
         'O': 'At the open',
         'P': 'Taking a position',
         'Q': 'Current quote',
         'S': 'Portfolio show-n',
         'T': 'Through the day',
         'V': 'Versus',
         'W': 'Indication - Working away',
         'X': 'Crossing opportunity'},
 '105': {},
 '106': {},
 '107': {},
 '108': {},
 '109': {},
 '11': {},
 '110': {},
 '111': {},
 '112': {},
 '113': {'N': 'Indicates that party sending message will report trade',
         'Y': 'Indicates that party receiving message must report trade'},
 '114': {'N': 'Indicates the broker is not required to locate',
         'Y': 'Indicates the broker is responsible for locating the stock'},
 '115': {},
 '116': {},
 '117': {},
 '118': {},
 '119': {},
 '12': {},
 '120': {},
 '121': {'N': 'Do not execute Forex after security trade',
         'Y': 'Execute Forex after security trade'},
 '122': {},
 '123': {'N': 'Sequence Reset <4>', 'Y': 'Gap Fill message, '},
 '124': {},
 '125': {'F': 'full remaining quantity',
         'P': 'partial cancel (reduce quantity)'},
 '126': {},
 '127': {'A': 'Unknown symbol',
         'B': 'Wrong side',
         'C': 'Quantity exceeds order',
         'D': 'No matching order',
         'E': 'Price <44>',
         'Z': 'Other'},
 '128': {},
 '129': {},
 '13': {'1': 'per share', '2': 'percentage', '3': 'absolute'},
 '130': {'N': 'Not natural', 'Y': 'Natural'},
 '131': {},
 '132': {},
 '133': {},
 '134': {},
 '135': {},
 '136': {},
 '137': {},
 '138': {},
 '139': {'1': 'Regulatory (e.g. SEC)',
         '2': 'Tax',
         '3': 'Local ',
         '4': 'Exchange Fees',
         '5': 'Stamp',
         '6': 'Levy',
         '7': 'Other'},
 '14': {},
 '140': {},
 '15': {},
 '16': {},
 '17': {},
 '18': {'0': 'Stay on offerside',
        '1': 'Not held',
        '2': 'Work',
        '3': 'Go along',
        '4': 'Over the day',
        '5': 'Held',
        '6': "Participate don't initiate",
        '7': 'Strict scale',
        '8': 'Try to scale',
        '9': 'Stay on bidside',
        'A': 'No cross',
        'B': 'OK to cross',
        'C': 'Call first',
        'D': 'Percent of volume',
        'E': 'Do not increase - DNI',
        'F': 'Do not reduce - DNR',
        'G': 'All or none - AON',
        'I': 'Institutions only',
        'L': 'Last peg (last sale)',
        'M': 'Mid-price peg (midprice of inside quote)',
        'N': 'Non-negotiable',
        'O': 'Opening peg',
        'P': 'Market peg',
        'R': 'Primary peg (primary market - buy at bid/sell at offer)',
        'S': 'Suspend'},
 '19': {},
 '2': {},
 '20': {'0': 'New', '1': 'Cancel', '2': 'Correct', '3': 'Status'},
 '21': {'1': 'Automated execution order, private, no Broker intervention',
        '2': 'Automated execution order, public, Broker intervention OK',
        '3': 'Manual order, best execution'},
 '22': {'1': 'CUSIP',
        '2': 'SEDOL',
        '3': 'QUIK',
        '4': 'ISIN number',
        '5': 'RIC code'},
 '23': {},
 '24': {'A': 'Autex', 'B': 'Bridge'},
 '25': {'H': 'High', 'L': 'Low', 'M': 'Medium'},
 '26': {},
 '27': {'L': 'Large', 'M': 'Medium', 'S': 'Small'},
 '28': {'C': 'Cancel', 'N': 'New', 'R': 'Replace'},
 '29': {'1': 'Agent',
        '2': 'Cross as agent',
        '3': 'Cross as principal',
        '4': 'Principal'},
 '3': {},
 '30': {},
 '31': {},
 '32': {},
 '33': {},
 '34': {},
 '35': {'0': 'Heartbeat <0>',
        '1': 'Test Request <1>',
        '2': 'Resend Request <2>',
        '3': 'Reject <3>',
        '4': 'Sequence Reset <4>',
        '5': 'Logout <5>',
        '6': 'Indication of Interest <6>',
        '7': 'Advertisement <7>',
        '8': 'Execution Report <8>',
        '9': 'Order Cancel Reject <9>',
        'A': 'Logon <A>',
        'B': 'News <B>',
        'C': 'Email <C>',
        'D': 'Order - Single <D>',
        'E': 'Order - List <E>',
        'F': 'Order Cancel Request <F>',
        'J': 'Allocation <J>',
        'K': 'List Cancel Request <K>',
        'L': 'List Execute <L>',
        'M': 'List Status Request <M>',
        'N': 'List Status <N>',
        'P': 'Allocation ACK <P>',
        'Q': "Don't Know Trade <Q>",
        'R': 'Quote Request <R>',
        'S': 'Quote <S>'},
 '36': {},
 '37': {},
 '38': {},
 '39': {'0': 'New',
        '1': 'Partially filled',
        '2': 'Filled',
        '3': 'Done for day',
        '4': 'Canceled',
        '5': 'Replaced',
        '6': 'Pending Cancel/Replace',
        '7': 'Stopped',
        '8': 'Rejected',
        '9': 'Suspended',
        'A': 'Pending New',
        'B': 'Calculated',
        'C': 'Expired'},
 '4': {'B': 'Buy', 'S': 'Sell', 'T': 'Trade', 'X': 'Cross'},
 '40': {'1': 'Market',
        '2': 'Limit',
        '3': 'Stop',
        '4': 'Stop limit',
        '5': 'Market on close',
        '6': 'With or without',
        '7': 'Limit or better',
        '8': 'Limit with or without',
        '9': 'On basis',
        'A': 'On close',
        'B': 'Limit on close',
        'C': 'Forex',
        'D': 'Previously quoted',
        'E': 'Previously indicated',
        'P': 'Pegged (requires '},
 '41': {},
 '42': {},
 '43': {'N': 'Original transmission', 'Y': 'Possible duplicate'},
 '44': {},
 '45': {},
 '46': {},
 '47': {'A': 'Agency single order',
        'C': 'Program Order, non-index arb, for Member firm/org',
        'D': 'Program Order, index arb, for Member firm/org',
        'I': 'Individual Investor, single order',
        'J': 'Program Order, index arb, for individual customer',
        'K': 'Program Order, non-index arb, for individual customer',
        'M': 'Program Order, index arb, for other member',
        'N': 'Program Order, non-index arb, for other member',
        'U': 'Program Order, index arb, for other agency',
        'W': 'All other orders as agent for other member',
        'Y': 'Program Order, non-index arb, for other agency'},
 '48': {},
 '49': {},
 '5': {'C': 'Cancel', 'N': 'New', 'R': 'Replace'},
 '50': {},
 '52': {},
 '53': {},
 '54': {'1': 'Buy',
        '2': 'Sell',
        '3': 'Buy minus',
        '4': 'Sell plus',
        '5': 'Sell short',
        '6': 'Sell short exempt'},
 '55': {},
 '56': {},
 '564': {},
 '57': {},
 '58': {},
 '59': {'0': 'Day',
        '1': 'Good Till Cancel (GTC)',
        '2': 'At the Opening (OPG)',
        '3': 'Immediate or Cancel (OC)',
        '4': 'Fill or Kill (FOK)',
        '5': 'Good Till Crossing (GTX)',
        '6': 'Good Till Date'},
 '6': {},
 '60': {},
 '61': {'0': 'Normal', '1': 'Flash', '2': 'Background'},
 '62': {},
 '624': {'1': 'Buy',
         '2': 'Sell',
         '3': 'Buy minus',
         '4': 'Sell plus',
         '5': 'Sell short',
         '6': 'Sell short exempt'},
 '63': {'0': 'Regular',
        '1': 'Cash',
        '2': 'Next Day',
        '3': 'T+2',
        '4': 'T+3',
        '5': 'T+4',
        '6': 'Future',
        '7': 'When Issued',
        '8': 'Sellers Option',
        '9': 'T+ 5'},
 '64': {},
 '65': {},
 '66': {},
 '67': {},
 '68': {},
 '69': {},
 '7': {},
 '70': {},
 '71': {'0': 'New', '1': 'Replace', '2': 'Cancel'},
 '72': {},
 '73': {},
 '74': {},
 '75': {},
 '76': {},
 '77': {},
 '78': {},
 '79': {},
 '8': {},
 '80': {},
 '81': {'0': 'regular',
        '1': 'soft dollar',
        '2': 'step-in',
        '3': 'step-out',
        '4': 'soft-dollar step-in',
        '5': 'soft-dollar step-out',
        '6': 'plan sponsor'},
 '82': {},
 '83': {},
 '84': {},
 '85': {},
 '86': {},
 '87': {'0': 'accepted (successfully processed)',
        '1': 'rejected',
        '2': 'partial accept',
        '3': 'received (received, not yet processed)'},
 '88': {'0': 'unknown account(s)',
        '1': 'incorrect quantity',
        '2': 'incorrect average price',
        '3': 'unknown executing broker mnemonic',
        '4': 'commission difference',
        '5': 'unknown ',
        '6': 'unknown ',
        '7': 'other'},
 '89': {},
 '9': {},
 '90': {},
 '91': {},
 '92': {},
 '93': {},
 '94': {'0': 'New', '1': 'Reply', '2': 'Admin Reply'},
 '95': {},
 '96': {},
 '97': {},
 '98': {'0': 'None / other',
        '1': 'PKCS (proprietary)',
        '2': 'DES (EBC mode)',
        '3': 'PKCS/DES (proprietary)',
        '4': 'PGP/DES (defunct)',
        '5': 'PGP/DES-MD5 (see app note on FIX home page)',
        '6': 'PEM/DES-MD5 (see app note on FIX home page)'},
 '99': {}}
