field_by_tag =  {'1': 'Account',
 '10': 'CheckSum',
 '100': 'ExDestination',
 '102': 'CxlRejReason',
 '103': 'OrdRejReason',
 '104': 'IOIQualifier',
 '105': 'WaveNo',
 '106': 'Issuer',
 '107': 'SecurityDesc',
 '108': 'HeartBtInt',
 '109': 'ClientID',
 '11': 'ClOrdID',
 '110': 'MinQty',
 '111': 'MaxFloor',
 '112': 'TestReqID',
 '113': 'ReportToExch',
 '114': 'LocateReqd',
 '115': 'OnBehalfOfCompID',
 '116': 'OnBehalfOfSubID',
 '117': 'QuoteID',
 '118': 'NetMoney',
 '119': 'SettlCurrAmt',
 '12': 'Commission',
 '120': 'SettlCurrency',
 '121': 'ForexReq',
 '122': 'OrigSendingTime',
 '123': 'GapFillFlag',
 '124': 'NoExecs',
 '126': 'ExpireTime',
 '127': 'DKReason',
 '128': 'DeliverToCompID',
 '129': 'DeliverToSubID',
 '13': 'CommType',
 '130': 'IOINaturalFlag',
 '131': 'QuoteReqID',
 '132': 'BidPx',
 '133': 'OfferPx',
 '134': 'BidSize',
 '135': 'OfferSize',
 '136': 'NoMiscFees',
 '137': 'MiscFeeAmt',
 '138': 'MiscFeeCurr',
 '139': 'MiscFeeType',
 '14': 'CumQty',
 '140': 'PrevClosePx',
 '141': 'ResetSeqNumFlag',
 '142': 'SenderLocationID',
 '143': 'TargetLocationID',
 '144': 'OnBehalfOfLocationID',
 '145': 'DeliverToLocationID',
 '146': 'NoRelatedSym',
 '147': 'Subject',
 '148': 'Headline',
 '149': 'URLLink',
 '15': 'Currency',
 '150': 'ExecType',
 '151': 'LeavesQty',
 '152': 'CashOrderQty',
 '153': 'AllocAvgPx',
 '154': 'AllocNetMoney',
 '155': 'SettlCurrFxRate',
 '156': 'SettlCurrFxRateCalc',
 '157': 'NumDaysInterest',
 '158': 'AccruedInterestRate',
 '159': 'AccruedInterestAmt',
 '16': 'EndSeqNo',
 '160': 'SettlInstMode',
 '161': 'AllocText',
 '162': 'SettlInstID',
 '163': 'SettlInstTransType',
 '164': 'EmailThreadID',
 '165': 'SettlInstSource',
 '166': 'SettlLocation',
 '167': 'SecurityType',
 '168': 'EffectiveTime',
 '169': 'StandInstDbType',
 '17': 'ExecID',
 '170': 'StandInstDbName',
 '171': 'StandInstDbID',
 '172': 'SettlDeliveryType',
 '173': 'SettlDepositoryCode',
 '174': 'SettlBrkrCode',
 '175': 'SettlInstCode',
 '176': 'SecuritySettlAgentName',
 '177': 'SecuritySettlAgentCode',
 '178': 'SecuritySettlAgentAcctNum',
 '179': 'SecuritySettlAgentAcctName',
 '18': 'ExecInst',
 '180': 'SecuritySettlAgentContactName',
 '181': 'SecuritySettlAgentContactPhone',
 '182': 'CashSettlAgentName',
 '183': 'CashSettlAgentCode',
 '184': 'CashSettlAgentAcctNum',
 '185': 'CashSettlAgentAcctName',
 '186': 'CashSettlAgentContactName',
 '187': 'CashSettlAgentContactPhone',
 '188': 'BidSpotRate',
 '189': 'BidForwardPoints',
 '19': 'ExecRefID',
 '190': 'OfferSpotRate',
 '191': 'OfferForwardPoints',
 '192': 'OrderQty2',
 '193': 'FutSettDate2',
 '194': 'LastSpotRate',
 '195': 'LastForwardPoints',
 '196': 'AllocLinkID',
 '197': 'AllocLinkType',
 '198': 'SecondaryOrderID',
 '199': 'NoIOIQualifiers',
 '2': 'AdvId',
 '20': 'ExecTransType',
 '200': 'MaturityMonthYear',
 '201': 'PutOrCall',
 '202': 'StrikePrice',
 '203': 'CoveredOrUncovered',
 '204': 'CustomerOrFirm',
 '205': 'MaturityDay',
 '206': 'OptAttribute',
 '207': 'SecurityExchange',
 '208': 'NotifyBrokerOfCredit',
 '209': 'AllocHandlInst',
 '21': 'HandlInst',
 '210': 'MaxShow',
 '211': 'PegDifference',
 '22': 'IDSource',
 '23': 'IOIid',
 '24': 'IOIOthSvc',
 '25': 'IOIQltyInd',
 '26': 'IOIRefID',
 '27': 'IOIShares',
 '28': 'IOITransType',
 '29': 'LastCapacity',
 '3': 'AdvRefID',
 '30': 'LastMkt',
 '31': 'LastPx',
 '32': 'LastShares',
 '33': 'LinesOfText',
 '34': 'MsgSeqNum',
 '35': 'MsgType',
 '36': 'NewSeqNo',
 '37': 'OrderID',
 '38': 'OrderQty',
 '39': 'OrdStatus',
 '4': 'AdvSide',
 '40': 'OrdType',
 '41': 'OrigClOrdID',
 '42': 'OrigTime',
 '43': 'PossDupFlag',
 '44': 'Price',
 '45': 'RefSeqNum',
 '46': 'RelatdSym',
 '48': 'SecurityID',
 '49': 'SenderCompID',
 '5': 'AdvTransType',
 '50': 'SenderSubID',
 '52': 'SendingTime',
 '53': 'Shares',
 '54': 'Side',
 '55': 'Symbol',
 '56': 'TargetCompID',
 '57': 'TargetSubID',
 '58': 'Text',
 '59': 'TimeInForce',
 '6': 'AvgPx',
 '60': 'TransactTime',
 '61': 'Urgency',
 '62': 'ValidUntilTime',
 '63': 'SettlmntTyp',
 '64': 'FutSettDate',
 '65': 'SymbolSfx',
 '66': 'ListID',
 '67': 'ListSeqNo',
 '68': 'ListNoOrds',
 '69': 'ListExecInst',
 '7': 'BeginSeqNo',
 '70': 'AllocID',
 '71': 'AllocTransType',
 '72': 'RefAllocID',
 '73': 'NoOrders',
 '74': 'AvgPrxPrecision',
 '75': 'TradeDate',
 '76': 'ExecBroker',
 '77': 'OpenClose',
 '78': 'NoAllocs',
 '79': 'AllocAccount',
 '8': 'BeginString',
 '80': 'AllocShares',
 '81': 'ProcessCode',
 '82': 'NoRpts',
 '83': 'RptSeq',
 '84': 'CxlQty',
 '87': 'AllocStatus',
 '88': 'AllocRejCode',
 '89': 'Signature',
 '9': 'BodyLength',
 '90': 'SecureDataLen',
 '91': 'SecureData',
 '92': 'BrokerOfCredit',
 '93': 'SignatureLength',
 '94': 'EmailType',
 '95': 'RawDataLength',
 '96': 'RawData',
 '97': 'PossResend',
 '98': 'EncryptMethod',
 '99': 'StopPx'}
tag_by_field =  {'Account': '1',
 'AccruedInterestAmt': '159',
 'AccruedInterestRate': '158',
 'AdvId': '2',
 'AdvRefID': '3',
 'AdvSide': '4',
 'AdvTransType': '5',
 'AllocAccount': '79',
 'AllocAvgPx': '153',
 'AllocHandlInst': '209',
 'AllocID': '70',
 'AllocLinkID': '196',
 'AllocLinkType': '197',
 'AllocNetMoney': '154',
 'AllocRejCode': '88',
 'AllocShares': '80',
 'AllocStatus': '87',
 'AllocText': '161',
 'AllocTransType': '71',
 'AvgPrxPrecision': '74',
 'AvgPx': '6',
 'BeginSeqNo': '7',
 'BeginString': '8',
 'BidForwardPoints': '189',
 'BidPx': '132',
 'BidSize': '134',
 'BidSpotRate': '188',
 'BodyLength': '9',
 'BrokerOfCredit': '92',
 'CashOrderQty': '152',
 'CashSettlAgentAcctName': '185',
 'CashSettlAgentAcctNum': '184',
 'CashSettlAgentCode': '183',
 'CashSettlAgentContactName': '186',
 'CashSettlAgentContactPhone': '187',
 'CashSettlAgentName': '182',
 'CheckSum': '10',
 'ClOrdID': '11',
 'ClientID': '109',
 'CommType': '13',
 'Commission': '12',
 'CoveredOrUncovered': '203',
 'CumQty': '14',
 'Currency': '15',
 'CustomerOrFirm': '204',
 'CxlQty': '84',
 'CxlRejReason': '102',
 'DKReason': '127',
 'DeliverToCompID': '128',
 'DeliverToLocationID': '145',
 'DeliverToSubID': '129',
 'EffectiveTime': '168',
 'EmailThreadID': '164',
 'EmailType': '94',
 'EncryptMethod': '98',
 'EndSeqNo': '16',
 'ExDestination': '100',
 'ExecBroker': '76',
 'ExecID': '17',
 'ExecInst': '18',
 'ExecRefID': '19',
 'ExecTransType': '20',
 'ExecType': '150',
 'ExpireTime': '126',
 'ForexReq': '121',
 'FutSettDate': '64',
 'FutSettDate2': '193',
 'GapFillFlag': '123',
 'HandlInst': '21',
 'Headline': '148',
 'HeartBtInt': '108',
 'IDSource': '22',
 'IOINaturalFlag': '130',
 'IOIOthSvc': '24',
 'IOIQltyInd': '25',
 'IOIQualifier': '104',
 'IOIRefID': '26',
 'IOIShares': '27',
 'IOITransType': '28',
 'IOIid': '23',
 'Issuer': '106',
 'LastCapacity': '29',
 'LastForwardPoints': '195',
 'LastMkt': '30',
 'LastPx': '31',
 'LastShares': '32',
 'LastSpotRate': '194',
 'LeavesQty': '151',
 'LinesOfText': '33',
 'ListExecInst': '69',
 'ListID': '66',
 'ListNoOrds': '68',
 'ListSeqNo': '67',
 'LocateReqd': '114',
 'MaturityDay': '205',
 'MaturityMonthYear': '200',
 'MaxFloor': '111',
 'MaxShow': '210',
 'MinQty': '110',
 'MiscFeeAmt': '137',
 'MiscFeeCurr': '138',
 'MiscFeeType': '139',
 'MsgSeqNum': '34',
 'MsgType': '35',
 'NetMoney': '118',
 'NewSeqNo': '36',
 'NoAllocs': '78',
 'NoExecs': '124',
 'NoIOIQualifiers': '199',
 'NoMiscFees': '136',
 'NoOrders': '73',
 'NoRelatedSym': '146',
 'NoRpts': '82',
 'NotifyBrokerOfCredit': '208',
 'NumDaysInterest': '157',
 'OfferForwardPoints': '191',
 'OfferPx': '133',
 'OfferSize': '135',
 'OfferSpotRate': '190',
 'OnBehalfOfCompID': '115',
 'OnBehalfOfLocationID': '144',
 'OnBehalfOfSubID': '116',
 'OpenClose': '77',
 'OptAttribute': '206',
 'OrdRejReason': '103',
 'OrdStatus': '39',
 'OrdType': '40',
 'OrderID': '37',
 'OrderQty': '38',
 'OrderQty2': '192',
 'OrigClOrdID': '41',
 'OrigSendingTime': '122',
 'OrigTime': '42',
 'PegDifference': '211',
 'PossDupFlag': '43',
 'PossResend': '97',
 'PrevClosePx': '140',
 'Price': '44',
 'ProcessCode': '81',
 'PutOrCall': '201',
 'QuoteID': '117',
 'QuoteReqID': '131',
 'RawData': '96',
 'RawDataLength': '95',
 'RefAllocID': '72',
 'RefSeqNum': '45',
 'RelatdSym': '46',
 'ReportToExch': '113',
 'ResetSeqNumFlag': '141',
 'RptSeq': '83',
 'SecondaryOrderID': '198',
 'SecureData': '91',
 'SecureDataLen': '90',
 'SecurityDesc': '107',
 'SecurityExchange': '207',
 'SecurityID': '48',
 'SecuritySettlAgentAcctName': '179',
 'SecuritySettlAgentAcctNum': '178',
 'SecuritySettlAgentCode': '177',
 'SecuritySettlAgentContactName': '180',
 'SecuritySettlAgentContactPhone': '181',
 'SecuritySettlAgentName': '176',
 'SecurityType': '167',
 'SenderCompID': '49',
 'SenderLocationID': '142',
 'SenderSubID': '50',
 'SendingTime': '52',
 'SettlBrkrCode': '174',
 'SettlCurrAmt': '119',
 'SettlCurrFxRate': '155',
 'SettlCurrFxRateCalc': '156',
 'SettlCurrency': '120',
 'SettlDeliveryType': '172',
 'SettlDepositoryCode': '173',
 'SettlInstCode': '175',
 'SettlInstID': '162',
 'SettlInstMode': '160',
 'SettlInstSource': '165',
 'SettlInstTransType': '163',
 'SettlLocation': '166',
 'SettlmntTyp': '63',
 'Shares': '53',
 'Side': '54',
 'Signature': '89',
 'SignatureLength': '93',
 'StandInstDbID': '171',
 'StandInstDbName': '170',
 'StandInstDbType': '169',
 'StopPx': '99',
 'StrikePrice': '202',
 'Subject': '147',
 'Symbol': '55',
 'SymbolSfx': '65',
 'TargetCompID': '56',
 'TargetLocationID': '143',
 'TargetSubID': '57',
 'TestReqID': '112',
 'Text': '58',
 'TimeInForce': '59',
 'TradeDate': '75',
 'TransactTime': '60',
 'URLLink': '149',
 'Urgency': '61',
 'ValidUntilTime': '62',
 'WaveNo': '105'}
desc_by_tag_value =  {'1': {},
 '10': {},
 '100': {},
 '102': {'0': 'Too late to cancel', '1': 'Unknown order'},
 '103': {'0': 'Broker option',
         '1': 'Unknown symbol',
         '2': 'Exchange closed',
         '3': 'Order exceeds limit',
         '4': 'Too late to enter',
         '5': 'Unknown Order',
         '6': 'Duplicate Order'},
 '104': {'A': 'All or none',
         'C': 'At the close',
         'I': 'In touch with',
         'L': 'Limit',
         'M': 'More behind',
         'O': 'At the open',
         'P': 'Taking a position',
         'Q': 'At the Market (previously called Current ',
         'S': 'Portfolio show-n',
         'T': 'Through the day',
         'V': 'Versus',
         'W': 'Indication - Working away',
         'X': 'Crossing opportunity',
         'Y': 'At the Midpoint',
         'Z': 'Pre-open'},
 '105': {},
 '106': {},
 '107': {},
 '108': {},
 '109': {},
 '11': {},
 '110': {},
 '111': {},
 '112': {},
 '113': {'N': 'Indicates that party sending message will report trade',
         'Y': 'Indicates that party receiving message must report trade'},
 '114': {'N': 'Indicates the broker is not required to locate',
         'Y': 'Indicates the broker is responsible for locating the stock'},
 '115': {},
 '116': {},
 '117': {},
 '118': {},
 '119': {},
 '12': {},
 '120': {},
 '121': {'N': 'Do not execute Forex after security trade',
         'Y': 'Execute Forex after security trade'},
 '122': {},
 '123': {'N': 'Sequence Reset <4>', 'Y': 'Gap Fill message, '},
 '124': {},
 '126': {},
 '127': {'A': 'Unknown symbol',
         'B': 'Wrong side',
         'C': 'Quantity exceeds order',
         'D': 'No matching order',
         'E': 'Price <44>',
         'Z': 'Other'},
 '128': {},
 '129': {},
 '13': {'1': 'per share', '2': 'percentage', '3': 'absolute'},
 '130': {'N': 'Not natural', 'Y': 'Natural'},
 '131': {},
 '132': {},
 '133': {},
 '134': {},
 '135': {},
 '136': {},
 '137': {},
 '138': {},
 '139': {'1': 'Regulatory (e.g. SEC)',
         '2': 'Tax',
         '3': 'Local ',
         '4': 'Exchange Fees',
         '5': 'Stamp',
         '6': 'Levy',
         '7': 'Other',
         '8': 'Markup'},
 '14': {},
 '140': {},
 '141': {'N': 'No', 'Y': 'Yes, reset sequence numbers'},
 '142': {},
 '143': {},
 '144': {},
 '145': {},
 '146': {},
 '147': {},
 '148': {},
 '149': {},
 '15': {},
 '150': {'0': 'New',
         '1': 'Partial fill',
         '2': 'Fill',
         '3': 'Done for day',
         '4': 'Cancelled',
         '5': 'Replace',
         '6': 'Pending Cancel/Replace',
         '7': 'Stopped',
         '8': 'Rejected',
         '9': 'Suspended',
         'A': 'Pending New',
         'B': 'Calculated',
         'C': 'Expired'},
 '151': {},
 '152': {},
 '153': {},
 '154': {},
 '155': {},
 '156': {},
 '157': {},
 '158': {},
 '159': {},
 '16': {},
 '160': {'0': 'Default',
         '1': 'Standing Instructions Provided',
         '2': 'Specific ',
         '3': 'Specific '},
 '161': {},
 '162': {},
 '163': {'C': 'Cancel', 'N': 'New', 'R': 'Replace'},
 '164': {},
 '165': {'1': "Broker's Instructions", '2': "Institution's Instructions"},
 '166': {'CED': 'CEDEL',
         'DTC': 'Depository Trust Company',
         'EUR': 'Euroclear',
         'FED': 'Federal Book Entry',
         'PTC': 'Participant Trust Company'},
 '167': {'BA': 'Bankers Acceptance',
         'CD': 'Certificate Of Deposit',
         'CMO': 'Collateralize Mortgage Obligation',
         'CORP': 'Corporate Bond',
         'CP': 'Commercial Paper',
         'CPP': 'Corporate Private Placement',
         'CS': 'Common Stock',
         'FHA': 'Federal Housing Authority',
         'FHL': 'Federal Home Loan',
         'FN': 'Federal National Mortgage Association',
         'FOR': 'Foreign Exchange Contract',
         'FUT': 'Future',
         'GN': 'Government National Mortgage Association',
         'GOVT': 'Treasuries + Agency Debenture',
         'MF': 'Mutual Fund',
         'MIO': 'Mortgage Interest Only',
         'MPO': 'Mortgage Principle Only',
         'MPP': 'Mortgage Private Placement',
         'MPT': 'Miscellaneous Pass-Thru',
         'MUNI': 'Municipal Bond',
         'NONE': 'No ISITC Security Type',
         'OPT': 'Option',
         'PS': 'Preferred Stock',
         'RP': 'Repurchase Agreement',
         'RVRP': 'Reverse Repurchase Agreement',
         'SL': 'Student Loan Marketing Association',
         'TD': 'Time Deposit',
         'USTB': 'US Treasury Bill',
         'WAR': 'Warrant',
         'ZOO': 'Cats, Tigers & Lions (a real code: US Treasury Receipts)'},
 '168': {},
 '169': {'0': 'Other',
         '1': 'DTC SID',
         '2': 'Thomson ALERT',
         '3': 'A Global Custodian ('},
 '17': {},
 '170': {},
 '171': {},
 '172': {},
 '173': {},
 '174': {},
 '175': {},
 '176': {},
 '177': {},
 '178': {},
 '179': {},
 '18': {'0': 'Stay on offerside',
        '1': 'Not held',
        '2': 'Work',
        '3': 'Go along',
        '4': 'Over the day',
        '5': 'Held',
        '6': "Participate don't initiate",
        '7': 'Strict scale',
        '8': 'Try to scale',
        '9': 'Stay on bidside',
        'A': 'No cross (cross is forbidden)',
        'B': 'OK to cross',
        'C': 'Call first',
        'D': "Percent of volume '(indicates that the sender does not want to "
             "be all of the volume on the floor vs. a specific percentage)'",
        'E': 'Do not increase - DNI',
        'F': 'Do not reduce - DNR',
        'G': 'All or none - AON',
        'I': 'Institutions only',
        'L': 'Last peg (last sale)',
        'M': 'Mid-price peg (midprice of inside quote)',
        'N': 'Non-negotiable',
        'O': 'Opening peg',
        'P': 'Market peg',
        'R': 'Primary peg (primary market - buy at bid/sell at offer)',
        'S': 'Suspend',
        'U': 'Customer Display Instruction (Rule11Ac1-1/4)',
        'V': 'Netting (for Forex)'},
 '180': {},
 '181': {},
 '182': {},
 '183': {},
 '184': {},
 '185': {},
 '186': {},
 '187': {},
 '188': {},
 '189': {},
 '19': {},
 '190': {},
 '191': {},
 '192': {},
 '193': {},
 '194': {},
 '195': {},
 '196': {},
 '197': {'0': 'F/X Netting', '1': 'F/X Swap'},
 '198': {},
 '199': {},
 '2': {},
 '20': {'0': 'New', '1': 'Cancel', '2': 'Correct', '3': 'Status'},
 '200': {},
 '201': {'0': 'Put', '1': 'Call'},
 '202': {},
 '203': {'0': 'Covered', '1': 'Uncovered'},
 '204': {'0': 'Customer', '1': 'Firm'},
 '205': {},
 '206': {},
 '207': {},
 '208': {'N': 'Details should not be communicated',
         'Y': 'Details should be communicated'},
 '209': {'1': 'Match', '2': 'Forward', '3': 'Forward and Match'},
 '21': {'1': 'Automated execution order, private, no Broker intervention',
        '2': 'Automated execution order, public, Broker intervention OK',
        '3': 'Manual order, best execution'},
 '210': {},
 '211': {},
 '22': {'1': 'CUSIP',
        '2': 'SEDOL',
        '3': 'QUIK',
        '4': 'ISIN number',
        '5': 'RIC code',
        '6': 'ISO ',
        '7': 'ISO Country Code'},
 '23': {},
 '24': {'A': 'Autex', 'B': 'Bridge'},
 '25': {'H': 'High', 'L': 'Low', 'M': 'Medium'},
 '26': {},
 '27': {'L': 'Large', 'M': 'Medium', 'S': 'Small'},
 '28': {'C': 'Cancel', 'N': 'New', 'R': 'Replace'},
 '29': {'1': 'Agent',
        '2': 'Cross as agent',
        '3': 'Cross as principal',
        '4': 'Principal'},
 '3': {},
 '30': {},
 '31': {},
 '32': {},
 '33': {},
 '34': {},
 '35': {'0': 'Heartbeat <0>',
        '1': 'Test Request <1>',
        '2': 'Resend Request <2>',
        '3': 'Reject <3>',
        '4': 'Sequence Reset <4>',
        '5': 'Logout <5>',
        '6': 'Indication of Interest <6>',
        '7': 'Advertisement <7>',
        '8': 'Execution Report <8>',
        '9': 'Order Cancel Reject <9>',
        'A': 'Logon <A>',
        'B': 'News <B>',
        'C': 'Email <C>',
        'D': 'Order - Single <D>',
        'E': 'Order - List <E>',
        'F': 'Order Cancel Request <F>',
        'J': 'Allocation <J>',
        'K': 'List Cancel Request <K>',
        'L': 'List Execute <L>',
        'M': 'List Status Request <M>',
        'N': 'List Status <N>',
        'P': 'Allocation ACK <P>',
        'Q': "Don't Know Trade <Q>",
        'R': 'Quote Request <R>',
        'S': 'Quote <S>',
        'T': 'Settlement Instructions <T>'},
 '36': {},
 '37': {},
 '38': {},
 '39': {'0': 'New',
        '1': 'Partially filled',
        '2': 'Filled',
        '3': 'Done for day',
        '4': 'Canceled',
        '5': 'Replaced',
        '6': 'Pending Cancel/Replace',
        '7': 'Stopped',
        '8': 'Rejected',
        '9': 'Suspended',
        'A': 'Pending New',
        'B': 'Calculated',
        'C': 'Expired'},
 '4': {'B': 'Buy', 'S': 'Sell', 'T': 'Trade', 'X': 'Cross'},
 '40': {'1': 'Market',
        '2': 'Limit',
        '3': 'Stop',
        '4': 'Stop limit',
        '5': 'Market on close',
        '6': 'With or without',
        '7': 'Limit or better',
        '8': 'Limit with or without',
        '9': 'On basis',
        'A': 'On close',
        'B': 'Limit on close',
        'D': 'Previously quoted',
        'E': 'Previously indicated',
        'F': 'Forex - Limit',
        'G': 'Forex - Swap',
        'H': 'Forex - Previously Quoted',
        'P': 'Pegged (requires '},
 '41': {},
 '42': {},
 '43': {'N': 'Original transmission', 'Y': 'Possible duplicate'},
 '44': {},
 '45': {},
 '46': {},
 '48': {},
 '49': {},
 '5': {'C': 'Cancel', 'N': 'New', 'R': 'Replace'},
 '50': {},
 '52': {},
 '53': {},
 '54': {'1': 'Buy',
        '2': 'Sell',
        '3': 'Buy minus',
        '4': 'Sell plus',
        '5': 'Sell short',
        '6': 'Sell short exempt',
        '7': 'Undisclosed (valid for IOI message only)',
        '8': 'Cross (orders where counterparty is an exchange, valid for all '
             'messages except IOIs)'},
 '55': {},
 '56': {},
 '564': {},
 '57': {},
 '58': {},
 '59': {'0': 'Day',
        '1': 'Good Till Cancel (GTC)',
        '2': 'At the Opening (OPG)',
        '3': 'Immediate or Cancel (OC)',
        '4': 'Fill or Kill (FOK)',
        '5': 'Good Till Crossing (GTX)',
        '6': 'Good Till Date'},
 '6': {},
 '60': {},
 '61': {'0': 'Normal', '1': 'Flash', '2': 'Background'},
 '62': {},
 '624': {'1': 'Buy',
         '2': 'Sell',
         '3': 'Buy minus',
         '4': 'Sell plus',
         '5': 'Sell short',
         '6': 'Sell short exempt',
         '7': 'Undisclosed (valid for IOI message only)',
         '8': 'Cross (orders where counterparty is an exchange, valid for all '
              'messages except IOIs)'},
 '63': {'0': 'Regular',
        '1': 'Cash',
        '2': 'Next Day',
        '3': 'T+2',
        '4': 'T+3',
        '5': 'T+4',
        '6': 'Future',
        '7': 'When Issued',
        '8': 'Sellers Option',
        '9': 'T+ 5'},
 '64': {},
 '65': {},
 '66': {},
 '67': {},
 '68': {},
 '69': {},
 '7': {},
 '70': {},
 '71': {'0': 'New',
        '1': 'Replace',
        '2': 'Cancel',
        '3': 'Preliminary (without MiscFees and ',
        '4': 'Calculated (includes MiscFees and '},
 '72': {},
 '73': {},
 '74': {},
 '75': {},
 '76': {},
 '77': {},
 '78': {},
 '79': {},
 '8': {},
 '80': {},
 '81': {'0': 'regular',
        '1': 'soft dollar',
        '2': 'step-in',
        '3': 'step-out',
        '4': 'soft-dollar step-in',
        '5': 'soft-dollar step-out',
        '6': 'plan sponsor'},
 '82': {},
 '83': {},
 '84': {},
 '87': {'0': 'accepted (successfully processed)',
        '1': 'rejected',
        '2': 'partial accept',
        '3': 'received (received, not yet processed)'},
 '88': {'0': 'unknown account(s)',
        '1': 'incorrect quantity',
        '2': 'incorrect average price',
        '3': 'unknown executing broker mnemonic',
        '4': 'commission difference',
        '5': 'unknown ',
        '6': 'unknown ',
        '7': 'other'},
 '89': {},
 '9': {},
 '90': {},
 '91': {},
 '92': {},
 '93': {},
 '94': {'0': 'New', '1': 'Reply', '2': 'Admin Reply'},
 '95': {},
 '96': {},
 '97': {},
 '98': {'0': 'None / other',
        '1': 'PKCS (proprietary)',
        '2': 'DES (ECB mode)',
        '3': 'PKCS/DES (proprietary)',
        '4': 'PGP/DES (defunct)',
        '5': 'PGP/DES-MD5 (see app note on FIX web site)',
        '6': 'PEM/DES-MD5 (see app note on FIX web site)'},
 '99': {}}
