#!/usr/bin/env perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;
use TPSUP::AUTOSYS qw(get_dependency autorep_J autorep_q_J get_univ_patterns);
use TPSUP::UTIL    qw(get_setting_from_env);

my $prog = $0; $prog =~ s:.*/::;

my $DetailExpire = 24*60*60;
my $StatusExpire = 24*60*60;

sub usage {
   my ($message) = @_;
   print "$message\n" if $message;

   print << "END";
usage:

   $prog joblist.txt
   
description:

   run a list of autosys jobs, stored in a file

   -x  ExcludePattern  perl regex pattern, exclude job matched this pattern, case insensitive

   -m  MatchPattern    perl regex pattern, only run job matching this pattern, case insensitive

   -chkdep              check dependent jobs, so that we won't trigger dependent
                        jobs by mistake

   -u UnivPatterns      use this to check dependent jobs, when '-chkdep' specified

   -n                   dry-run

   -v                   verbose

   If '-u UnivPatterns' is not set, this script will first search \$UNIV_PATTERNS in
   shell environment.

   If \$UNIV_PATTERNS is not set in environment, this script will search it in
   ~/.tpautosys, a bash init file.

examples:

   $prog abatch_test.txt

END

   exit 1;
}

my $verbose;
my $MatchPattern;
my $ExcludePattern;
my $dryrun;
my $chkdep;
my $DetailFiles;
my $StatusFiles;
my $UnivPatterns;

GetOptions(
   'v|verbose'     => \$verbose,
   'm=s'           => \$MatchPattern,
   'x=s'           => \$ExcludePattern,
   'n|dryrun'      => \$dryrun,
   'chkdep'        => \$chkdep,
   'u=s'           => \$UnivPatterns,
   'df=s'          => \$DetailFiles,
   'sf=s'          => \$StatusFiles,
   'de=s'          => \$DetailExpire,
   'se=s'          => \$StatusExpire,
) || usage("cannot parse command line: $!");

usage("wrong number of args") if @ARGV != 1;

my ($file) = @ARGV;

my $ifh = get_in_fh($file);

if (!$UnivPatterns) {
   $UnivPatterns = get_univ_patterns();
}

my $status = autorep_J(  $UnivPatterns, {StatusExpire=>1});
my $detail = autorep_q_J($UnivPatterns, {DetailExpire=>600});

while (<$ifh>) {
    chomp $_;
    my $job = $_;

    next if $job =~ /^\s*$/;     # skip blank lines
    next if $job =~ /^\s*#/;     # skip comment

    next if defined $ExcludePattern && $job =~ /$ExcludePattern/i; 
    next if defined   $MatchPattern && $job !~   /$MatchPattern/i; 

    if (!$status->{$job}) {
       croak "cannot find $job in $UnivPatterns\n";
    }

    my $dep = get_dependency($job
}

my $opt = { 
   verbose      => $verbose,
   DetailFiles  => $DetailFiles,
   StatusFiles  => $StatusFiles,
   DetailExpire => $DetailExpire,
   StatusExpire => $StatusExpire,
   UnivPatterns => $UnivPatterns,
};

my $dependency = get_dependency($job, $opt);

no warnings 'uninitialized';

for my $updown (qw(up self down)) {
   for my $dep ($updown eq 'up' ? reverse(@{$dependency->{$updown}})
                                :         @{$dependency->{$updown}}  ) {
      print "$dep->{serial}, $dep->{job}, $dep->{detail}->{job_type}, ",
            "$dep->{status}->{Status}, ",
            "$dep->{status}->{LastStart}, $dep->{status}->{LastEnd}\n";
   }
}
