#!/bin/bash

# add exec permission to tpsup scripts because files created in windows sometimes missing it
# or lost exec permission when checked in

tpfind -he '($type eq "file") && (($mode & 0755) != 0755) && ($fh=ifh($path)) && ($line=<$fh>) && ($line=~/^#!/)' -ha '!system("ls -l $path; chmod 755 $path")'  ~/github/tpsup/scripts

