#!/usr/bin/env perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;
use TPSUP::AUTOSYS qw( 
   query_jobs 
   print_autorep_J_header
   get_autorep_J_format
   print_autorep_J_job
   autorep_J
   autorep_q_J
);
use TPSUP::UTIL qw(
   source_profile
   resolve_string_in_env
);
# use Carp::Always;

my $prog = $0; $prog =~ s:.*/::;

my $DetailExpire = 24*3600;
my $StatusExpire = 10;  

sub usage {
   my ($message) = @_;
   print "$message\n" if $message;

   print << "END";
usage:

   $prog jobname
   
description:

   debug an autosys job:
      - support job_types: CMD, FW
      - load the profile if defined
      - resolve variables in attributes: command, std_out_file, std_err_file, watch_file
      - find the command path
      - ls -l file

   -df DetailFiles     Use DetailFiles instead. multiple filenames separated by coma.

   -sf StatusFiles     Use StatusFiles instead. multiple filenames separated by coma.

   -v                  verbose mode

examples:

   - test without autosys, a CMD
   $prog -df adep_autorep_q_J_example.txt -sf adep_autorep_J_example.txt test_job2

   - test without autosys, a FW, file watcher
   $prog -df adep_autorep_q_J_example.txt -sf adep_autorep_J_example.txt test_job3

END

   exit 1;
}

my $verbose;
my $DetailFiles;
my $StatusFiles;
my $reset;
my $arg_is_job;

GetOptions(
   'v|verbose'     => \$verbose,
   'df=s'          => \$DetailFiles,
   'sf=s'          => \$StatusFiles,
) || usage("cannot parse command line: $!");

usage("wrong number of args") if @ARGV != 1;

my ($job) = @ARGV;

my $opt = {
   StatusExpire => $StatusExpire,  # always need the latest info
   DetailFiles  => $DetailFiles,
   StatusFiles  => $StatusFiles,
   verbose      => $verbose,
};

my $info;

if ($StatusFiles || $DetailFiles) { 
   $info = query_jobs($job, $opt);
} else {
   my $status_ref = autorep_J($job, $opt);
   my $detail_ref = autorep_q_J($job, $opt);

   die "cannot find job detail for $job\n" if ! $detail_ref->{$job};
   die "cannot find job status for $job\n" if ! $status_ref->{$job};

   $info->{$job} = {%{$status_ref->{$job}}, %{$detail_ref->{$job}}};
}

my $error = 0;
if (!exists $info->{$job}) {
   die "$job not found.\n";
}

if (!exists $info->{$job}->{Status}) {
   die "$job status not found. just deleted?\n";
}

print_autorep_J_header();
print_autorep_J_job($info, $job, "", $opt);
print "\n";

if ($info->{$job}->{Status} =~ /^(OH|OI)$/) {
   print "ERROR: $job is in $info->{$job}->{Status} mode.\n";
   print "\n";
   $error ++;
}

if (!$info->{$job}->{defination}) {
   print "\$info->{$job} = ", Dumper($info->{$job});
   die "$job missing defination. just deleted?\n";
}

print $info->{$job}->{defination};
print "\n";

my $machine = $info->{$job}->{machine};
my $owner   = $info->{$job}->{owner};

if ($machine) {
   my $ssh = "ssh -n -q -o StrictHostKeyChecking=no -o ConnectTimeout=5 -o BatchMode=yes";
   my $test_cmd = "$ssh $owner\@$machine hostname >/dev/null";
   system($test_cmd);
   if ($?==0) {
      # we can ssh to the machine, then run the script remotely

      my $script = "\n";

      $script .= ". $info->{$job}->{profile};\n\n"        if $info->{$job}->{profile};
      $script .= "ls -l $info->{$job}->{watch_file};\n\n" if $info->{$job}->{watch_file};

      if ($info->{$job}->{command}) {
         my ($command, $rest) = split /\s/, $info->{$job}->{command}, 2;
         $script .= "which $command; echo \"\";\n\n";
      }

      for my $attr (qw(std_out_file std_err_file)) {
         my $file = $info->{$job}->{$attr};

         # sometimes people put > in the output file, like below
         #    std_out_file: ">/tmp/test.log"
         #    std_err_file: ">/tmp/test.err"
         # remove the >
         $file =~ s/[>]+//g;
         if ($file) {
            $script .= "ls -l $file && tail $file; echo \"\";\n\n";
         }
      }

      $script =~ s/\$AUTO_JOB_NAME/$job/g;
      
      my $cmd = "tpssh -sshargs=-q $owner\@$machine '$script'";
      print "cmd = $cmd\n\n";
      system($cmd);
      exit 0;
   } else {
      print "test_cmd=$test_cmd failed.\n";
      print "We will run the rest locally, or please log onto $owner\@$machine\n"; 
   }
}

# now we do everything locally
if ($info->{$job}->{profile}) {
   my $profile = $info->{$job}->{profile};
   
   print "begin sourcing $profile\n";
   TPSUP::UTIL::source_profile($profile);
   print "done  sourcing $profile\n";
   print "\n";
}

$ENV{AUTO_JOB_NAME} = $job;

if ($info->{$job}->{job_type} =~ /^(FW|CMD)/) {
   # resolve any env variables
   for my $attr (qw(watch_file command std_out_file std_err_file)) {
      my $string = $info->{$job}->{$attr};
      next if ! $string;

      $string =~ s/\$AUTO_JOB_NAME/$job/g;

      my $resolved = resolve_string_in_env($string);
      print "$attr: $resolved\n\n";
  
      if ($attr =~ /watch_file/) {
         system("ls -l $resolved");
      } elsif ($attr =~ /std_out_file|std_err_file/) {
         $resolved =~ s/[>]+//g;
         system("ls -l $resolved");
         system("tail $resolved");
      } elsif ($attr =~ /^(command)$/) {
         my ($exe, $junk) = split /[\s<>]/, $resolved;
         print "which exe: "; system("which $exe");
      }
      print "\n";

   }
} else {
   die "unsupported job_type = $info->{$job}->{job_type}\n";
}


