#!/usr/bin/env perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;
use TPSUP::AUTOSYS qw(get_dependency);

my $prog = $0; $prog =~ s:.*/::;

my $DetailExpire = 24*60*60;
my $StatusExpire = 24*60*60;
my @DepExps;

sub usage {
   my ($message) = @_;
   print "$message\n" if $message;

   print << "END";
usage:

   $prog JobName
   
description:

   check autosys dependency

   -u UnivPatterns    job universe pattern. eg PROJ1_APP1%,PROJ2_APP2%. Multiple
                       patterns are separated by coma.

   -df DetailFiles     Use DetailFiles instead. multiple filenames separated by coma.

   -sf StatusFiles     Use StatusFiles instead. multiple filenames separated by coma.
   
   -r                  reset cache, ie, time out all caches

   -me matchExpression eg -m '\$Status !~ /OH|OI/'

   If '-u UnivPatterns' is not set, this script will first search \$UNIV_PATTERNS in
   shell environment.

   If \$UNIV_PATTERNS is not set in environment, this script will search it in
   ~/.tpautosys, a bash init file.

examples:

   - test a job in box
   $prog -df adep_autorep_J_q_example.txt -sf adep_autorep_J_example.txt test_job1

   - test a box
   $prog -df adep_autorep_J_q_example.txt -sf adep_autorep_J_example.txt test_box1

   - filter out job on-hold and on-ice
   $prog -df adep_autorep_J_q_example.txt \\
         -sf adep_autorep_J_example.txt \\
         -me '\$Status !~ /OH|OI/' \\
         test_job1

END

   exit 1;
}

my $verbose;
my $DetailFiles;
my $StatusFiles;
my $UnivPatterns;
my $reset;

GetOptions(
   'v|verbose'     => \$verbose,
   'r|reset'       => \$reset,
   'u=s'           => \$UnivPatterns,
   'df=s'          => \$DetailFiles,
   'sf=s'          => \$StatusFiles,
   'me=s'          => \@DepExps,
) || usage("cannot parse command line: $!");

usage("wrong number of args") if @ARGV != 1;

my ($job) = @ARGV;

my $opt = { 
   verbose      => $verbose,
   DetailFiles  => $DetailFiles,
   StatusFiles  => $StatusFiles,
   DetailExpire => $DetailExpire,
   StatusExpire => $StatusExpire,
   UnivPatterns => $UnivPatterns,
   DepExps      => \@DepExps,
};

if ($reset) {
   $opt->{DetailExpire} = 0;
   $opt->{StatusExpire} = 0;
} 

my $dependency = get_dependency($job, $opt);

$verbose && print STDERR "dependency=", Dumper($dependency);

no warnings 'uninitialized';

for my $updown (qw(up self down)) {
   next if ! exists $dependency->{$updown};

   for my $dep ($updown eq 'up' ? reverse(@{$dependency->{$updown}})
                                :         @{$dependency->{$updown}}  ) {
                                  
      print $updown eq 'up'   ? '-': 
            $updown eq 'down' ? '+' : '',
            join('.', @{$dep->{serial}}),
            ",   $dep->{detail}->{JobName}, $dep->{detail}->{job_type}, ",
            "$dep->{reason}, ",
            "$dep->{detail}->{Status}, ",
            "$dep->{detail}->{LastStart}, $dep->{detail}->{LastEnd}\n";
   }
}
