#!/bin/bash

# set CLASSPATH=".;%SITEBASE%\java\lib\antlr-4.9.3-complete.jar"
# java org.antlr.v4.Tool %*

usage () {
   cat >&2 <<EOF
usage:

   $0 grammar.g4

examples:

   $0 -Dlanguage=Python3 Chat.g4

EOF
   exit 1
}

if [ $# -eq 0 ]; then
   echo "wrong number of args" >&2
   usage
fi

. $TPSUP/profile
antlrenv default

# echo "CLASSPATH=$CLASSPATH"
# echo "ANTLR_JAR=$ANTLR_JAR"
# export CLASSPATH
# export ANTLR_JAR
set -x
# java org.antlr.v4.Tool $@
# somehow CLASSPATH not working in gitbash
java -cp "$ANTLR_JAR" org.antlr.v4.Tool $@
