#!/usr/bin/env perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;
use TPSUP::AUTOSYS qw(get_dependency autorep_J autorep_q_J get_univ_patterns);
use TPSUP::UTIL    qw(get_setting_from_env);
# use Carp::Always;

my $prog = $0; $prog =~ s:.*/::;

my $DetailExpire = 300;
my $StatusExpire = 1;

sub usage {
   my ($message) = @_;
   print "$message\n" if $message;

   print << "END";
usage:

   $prog joblist.txt
   
description:

   To prepare to run a list of autosys jobs in a file:
      validate job's existence.
      print the current job status.
      spot jobs in OH (on-hold), OI (on-ice), or RU (running).
      spot jobs that have downstream dependency.

   -x  ExcludePattern  perl regex pattern, exclude job matched this pattern, case insensitive

   -m  MatchPattern    perl regex pattern, only run job matching this pattern, case insensitive

   -u UnivPatterns      use this to check dependent jobs, when '-chkdep' specified

   -de n               expire Detail cache after n seconds. default $DetailExpire.

   -se n               expire Status cache after n seconds. default $StatusExpire.

   If '-u UnivPatterns' is not set, this script will first search \$UNIV_PATTERNS in
   shell environment.

   If \$UNIV_PATTERNS is not set in environment, this script will search it in
   ~/.tpautosys, a bash init file.

examples:

   $prog abatch_test.txt

END

   exit 1;
}

my $verbose;
my $MatchPattern;
my $ExcludePattern;
my $DetailFiles;
my $StatusFiles;
my $UnivPatterns;

GetOptions(
   'v|verbose'     => \$verbose,
   'm=s'           => \$MatchPattern,
   'x=s'           => \$ExcludePattern,
   'n|dryrun'      => \$dryrun,
   'chkdep'        => \$chkdep,
   'u=s'           => \$UnivPatterns,
   'df=s'          => \$DetailFiles,
   'sf=s'          => \$StatusFiles,
   'de=s'          => \$DetailExpire,
   'se=s'          => \$StatusExpire,
) || usage("cannot parse command line: $!");

usage("wrong number of args") if @ARGV != 1;

my ($file) = @ARGV;

my $ifh = get_in_fh($file);

if (!$UnivPatterns) {
   $UnivPatterns = get_univ_patterns();
}

my $info = query_jobs({
   UnivPatterns=>$UnivPatterns,
   DetailExpire=>$DetailExpire,
   StatusExpire=>$StatusExpire,
   DetailFiles=>\$DetailFiles,
   StatusFiles=>\$StatusFiles,
});

my $exists_box_job;

for my $job (keys %$info) {
   my $box_name = $info->{box_name};

   if ($box_name) {
      $exists_box_job->{$box_name}->{$job} ++;
   }
}

my @jobs;
my $seen;

while (<$ifh>) {
   chomp $_;
   my $job = $_;

   next if $job =~ /^\s*$/;     # skip blank lines
   next if $job =~ /^\s*#/;     # skip comment

   next if defined   $MatchPattern && $job !~   /$MatchPattern/i; 

   push @jobs, $job;
   $seen->{$job} ++;
}

close $ifh;

my $subjobs_by_job;

for my $job (@jobs) {
   if (!$status->{$job}) {
      croak "cannot find $job in $UnivPatterns\n";
   }

   my $dep = get_dependency($job, {DepExps=>['$Status !~ /OH|OI/']});

   if ($dep->{down}) {
      croak "$job has dependent\n";
   }

   if ($info->{$job}->{job_type} eq 'BOX') {
      for my $j2 (keys %$exists_box_job->{$job}) {
         if $info->{$j2}->{Status} !~ /^(OH|OI)$/) {
            push @{$subjobs_by_job->{$job}}, $j2;
         } 
      }

      if (!$subjobs_by_job->{$job}) {
         croak "all jobs in BOX $job are OH or OI";
      }
   } else {
      push @{$subjobs_by_job->{$job}}, $job;
   }
}

for my $job (@jobs) {
   { 
      my $cmd = "sendevent -E FORCE_STARTJOB -J $job";
   
      print "cmd = $cmd\n";
      if (!$dry_run) {
         system($cmd);
         $? && exit 1;
      }
   }

   
   while (1) { 
      my $cmd = "autorep -J $job";
   
      print "cmd = $cmd\n";

      if (!$dry_run) {
         my @lines = `$cmd`;
         $? && exit 1;

         my @falied = grep { / (TE|FA) /} @lines;

         if (@failed) {
            print "$job failed\n"; 
            print @lines;
            exit 1;
         }

         my @successful = grep { / (SU) /} @lines;

         print "$job: ", scalar(@successful), " of ", scalar(@{$subjobs_by_job->{$job}}), " succeeded\n";

         if (scalar(@successful) == scalar(@{$subjobs_by_job->{$job}})  
            last;
         }
      }

      last if $dry_run;

      sleep 10;
   }
}

print "all complete successfully\n";

exit 0;
