#!/usr/bin/env perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;
use TPSUP::AUTOSYS qw(get_dependency 
                      query_jobs
                      autorep_J
                      get_autorep_J_format
                      print_autorep_J_header
                      print_autorep_J_job
                      );
use TPSUP::UTIL    qw(get_in_fh);
# use Carp::Always;

my $prog = $0; $prog =~ s:.*/::;

my $DetailExpire = 300;
my $StatusExpire = 15;

sub usage {
   my ($message) = @_;
   print "$message\n" if $message;

   print << "END";
usage:

   $prog [-q] joblist.txt
   
description:

   Run autorep for jobs listed in a file, joblist.txt. Within the file, one job per line.
   The file allows comments (#) and blank lines.

   -xp ExcludePattern  perl regex pattern, exclude job matched this pattern, case insensitive
                       this is to filter input file

   -mp MatchPattern    perl regex pattern, only run job matching this pattern, case insensitive
                       this is to filter input file

   -me MatchExpression perl regex, eg, -me '\$Status !~ /OH|OI/'. can set multiple times

   -u UnivPatterns     use this to check dependent jobs, when '-chkdep' specified

   -de n               expire Detail cache after n seconds. default $DetailExpire.
                       mainly for testing purpose.

   -se n               expire Status cache after n seconds. default $StatusExpire.
                       mainly for testing purpose.

   -r                  reset cache, ie, time out all caches

   -df DetailFiles     Use DetailFiles instead. multiple filenames separated by coma.

   -sf StatusFiles     Use StatusFiles instead. multiple filenames separated by coma.

   -f                  force to run the jobs without prompt for confirmation.

   -n                  dryrun mode, check-only. will print the command but won't run the jobs.

   If '-u UnivPatterns' is not set, this script will first search \$UNIV_PATTERNS in
   shell environment.

   If \$UNIV_PATTERNS is not set in environment, this script will search it in
   ~/.tpautosys, a bash init file.

examples:

   $prog abatch_test.txt   # take from file
   $prog -                 # take from STDIN

   - test without autosys
   $prog    -df adep_autorep_J_q_example.txt -sf adep_autorep_J_example.txt abatch_test_fatal.txt
   $prog -q -df adep_autorep_J_q_example.txt -sf adep_autorep_J_example.txt abatch_test_good.txt
END

   exit 1;
}

my $verbose;
my $MatchPattern;
my $ExcludePattern;
my @JobExps;
my $DetailFiles;
my $StatusFiles;
my $UnivPatterns;
my $detail;
my $reset;

GetOptions(
   'v|verbose'     => \$verbose,
   'r|reset'       => \$reset,
   'q'             => \$detail,
   'mp=s'          => \$MatchPattern,
   'xp=s'          => \$ExcludePattern,
   'me=s'          => \@JobExps,
   'u=s'           => \$UnivPatterns,
   'df=s'          => \$DetailFiles,
   'sf=s'          => \$StatusFiles,
   'de=s'          => \$DetailExpire,
   'se=s'          => \$StatusExpire,
) || usage("cannot parse command line: $!");

usage("wrong number of args") if @ARGV != 1;

my ($file) = @ARGV;

my @jobs;
my $seen;

my $ifh = get_in_fh($file);

while (<$ifh>) {
   chomp $_;
   my $job = $_;

   next if $job =~ /^\s*$/;     # skip blank lines
   next if $job =~ /^\s*#/;     # skip comment

   $job =~ s/^[^0-9a-zA-Z.#_-]+//;     # trim spaces or bad chars
   $job =~ s/[^0-9a-zA-Z.#_-]+$//;     # trim spaces or bad chars

   next if $job eq '';

   next if defined   $MatchPattern && $job !~   /$MatchPattern/i; 
   next if defined $ExcludePattern && $job =~ /$ExcludePattern/i; 

   push @jobs, $job;
   $seen->{$job} ++;
}

close $ifh;

my $opt = {
   UnivPatterns => $UnivPatterns,
   DetailExpire => $DetailExpire,
   StatusExpire => $StatusExpire,
   DetailFiles  => $DetailFiles,
   StatusFiles  => $StatusFiles,
   JobExps      => \@JobExps,
   Jobs         => \@jobs,
   verbose      => $verbose,
};

if (!$detail) {
   $opt->{StatusOnly} = 1;
} else {
   $opt->{DetailOnly} = 1;
}

my $info;
if ($reset) {
   my $opt2 = {%$opt};
   $opt2->{DetailExpire} = 0;
   $opt2->{StatusExpire} = 0;
   $info = query_jobs($opt2);
} else {
   $info = query_jobs($opt);
}

my $exists_box_job;

for my $job (keys %$info) {
   my $box_name = $info->{box_name};

   if ($box_name) {
      $exists_box_job->{$box_name}->{$job} ++;
   }
}

if (!$detail) {
   print_autorep_J_header();

   for my $job (@jobs) {
      if (!$info->{$job}) {
         printf get_autorep_J_format(), $job,  "not found", "", "";
      } else {
         print_autorep_J_job($info, $job, "", $opt);
      }
   }
} else {
   for my $job (@jobs) {
      if (!$info->{$job}) {
         print  "$job not found\n";
      } elsif (!$info->{$job}->{job_type}) {
         print  "$job detail not found\n";
      } else {
         print "insert_job: $info->{$job}->{JobName}    job_type: $info->{$job}->{job_type}\n";
         for my $attr (sort keys(%{$info->{$job}})) {
            if ($attr =~ /^(JobName|job_type|LastStart|LastEnd|Status)$/) {
               next;
            }
            print  "$attr: $info->{$job}->{$attr}\n";
         }
      }
      print "\n";
   }  
}

exit 0;
