#!/usr/bin/env perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;
use TPSUP::AUTOSYS qw(get_dependency query_jobs print_autorep_J_header
                      get_autorep_J_format autorep_J print_autorep_J_job);
use TPSUP::UTIL    qw(get_in_fh);
# use Carp::Always;

my $prog = $0; $prog =~ s:.*/::;

my $DetailExpire = 24*3600;
my $interval = 10;
my $interval_limit = 60;
my $StatusExpire = 0;  

sub usage {
   my ($message) = @_;
   print "$message\n" if $message;

   print << "END";
usage:

   $prog joblist.txt
   
description:

   Watch autosys jobs listed in a file, joblist.txt, to complete. 

   Within the file, one job per line. The file allows comments (#) and blank lines.

   The running job is checked in $interval seconds; if not done after, $interval increases
   10 seconds for the next round, all the way up to $interval_limit seconds.

   -x  ExcludePattern  perl regex pattern, exclude job matched this pattern, case insensitive

   -m  MatchPattern    perl regex pattern, only run job matching this pattern, case insensitive

   -u UnivPatterns     use this to check dependent jobs, when '-chkdep' specified

   -df DetailFiles     Use DetailFiles instead. multiple filenames separated by coma.

   -sf StatusFiles     Use StatusFiles instead. multiple filenames separated by coma.

   If '-u UnivPatterns' is not set, this script will first search \$UNIV_PATTERNS in
   shell environment.

   If \$UNIV_PATTERNS is not set in environment, this script will search it in
   ~/.tpautosys, a bash init file.

examples:

   $prog abatch_test.txt    # take from file
   $prog -                  # take from STDIN

   - test without autosys
   $prog -df adep_autorep_J_q_example.txt -sf adep_autorep_J_example.txt abatch_test_fatal.txt
   $prog -df adep_autorep_J_q_example.txt -sf adep_autorep_J_example.txt abatch_test_good.txt

END

   exit 1;
}

my $verbose;
my $MatchPattern;
my $ExcludePattern;
my $DetailFiles;
my $StatusFiles;
my $UnivPatterns;
my $reset;

GetOptions(
   'v|verbose'     => \$verbose,
   'm=s'           => \$MatchPattern,
   'x=s'           => \$ExcludePattern,
   'u=s'           => \$UnivPatterns,
   'df=s'          => \$DetailFiles,
   'sf=s'          => \$StatusFiles,
) || usage("cannot parse command line: $!");

usage("wrong number of args") if @ARGV != 1;

my ($file) = @ARGV;

my @jobs;
my $seen;

my $ifh = get_in_fh($file);

while (<$ifh>) {
   chomp $_;
   my $job = $_;

   next if $job =~ /^\s*$/;     # skip blank lines
   next if $job =~ /^\s*#/;     # skip comment

   #$job =~ s/^\s+//;     # trim spaces
   #$job =~ s/\s+$//;     # trim spaces
   $job =~ s/^[^0-9a-zA-Z.#_-]+//;     # trim spaces or bad chars
   $job =~ s/[^0-9a-zA-Z.#_-]+$//;     # trim spaces or bad chars

   next if $job eq '';

   next if defined   $MatchPattern && $job !~   /$MatchPattern/i; 
   next if defined $ExcludePattern && $job =~ /$ExcludePattern/i;

   push @jobs, $job;
   $seen->{$job} ++;
}

close $ifh;

my $opt = {
   UnivPatterns => $UnivPatterns,
   StatusExpire => 0,  # always need the latest info
   DetailFiles  => $DetailFiles,
   StatusFiles  => $StatusFiles,
   Jobs         => \@jobs,
   StatusOnly   => 1,  # only need to query status, ie, autorep -J
   verbose      => $verbose,
};

my $info = query_jobs($opt);

my $error = 0;
my $bad_by_job;
my @jobs_to_watch;

for my $job (@jobs) {
   if (!exists $info->{$job}) {
      $bad_by_job->{$job} = "not found";
      print "ERROR: $job $bad_by_job->{$job}.\n";
      $error ++;
      next;
   }

   if (!exists $info->{$job}->{Status}) {
      $bad_by_job->{$job} = "status not found. just deleted?";
      print "ERROR: $job $bad_by_job->{$job}.\n";
      $error ++;
      next;
   }

   #if ($info->{$job}->{Status} =~ /^(OH|OI)$/) {
   #   print "ERROR: $job is in $info->{$job}->{Status} mode.\n";
   #   $error ++;
   #   next;
   #}

   #if ($info->{$job}->{Status} =~ /^(RU|ST|AC)$/) {
   #   push @jobs_to_watch, $job;
   #   next;
   #}
}

my $sub_interval = $interval;

while (1) {
   my $need_next_round = 0;

   print_autorep_J_header();

   my $info = query_jobs($opt);
   my $failed = 0;

   for my $job (@jobs) {
      if ($bad_by_job->{$job}) {
         printf get_autorep_J_format(), $job,  $bad_by_job->{$job}, "", "";
      } else {
         print_autorep_J_job($info, $job, "", $opt);
	 if ($info ->{$job}->{Status} =~ /^(RU|ST|AC)$/) {  
            $need_next_round ++;
         }

	 if ($info ->{$job}->{Status} =~ /^(TE|FA)$/) {  
            $failed ++;
         }
      }
   }

   last if ! $need_next_round;
   print "$need_next_round jobs not completed. $failed failed so far. sleep for $sub_interval\n";
   sleep $sub_interval;
   $sub_interval += 10;
   $sub_interval = $interval_limit if $sub_interval > $interval_limit;
   $info = query_jobs($opt);
}
   
if ($error) {
   print "ERROR: total $error errors\n";
} else {
   print "OK:    All good.\n";
}

exit $error;
