#!/usr/bin/perl

use strict;
use Data::Dumper;
use Getopt::Long;
use TPSUP::DATE qw(get_interval_seconds);
use TPSUP::LOG qw(get_PatternCfg find_log_pattern);
use TPSUP::UTIL qw(get_in_fh);

my $prog = $0; $prog =~ s:.*/::;
my $dir = $0; $dir =~ s:[^/]+$::;

my $min_idle = 60;

sub usage {
   my ($msg) = @_;

   print STDERR "$msg\n" if $msg;

   print STDERR << "EOF";
usage:

   $prog log
   $prog -

 description:
   
    check log for error

   -x exclude_pattern     Perl style, exclude lines with this pattern
   -m  match_pattern      Perl style, only count the lines with this pattern

examples:

   $prog log_event_test.log

EOF

   exit 1;
}

 our ($exclude_pattern, $match_pattern, $verbose);

 GetOptions(
   "x=s"            => \$exclude_pattern,
   "m=s"            => \$match_pattern,
   "v"              => \$verbose,
) or usage("Could not parse command line: $!");

usage("wrong number of args") if !@ARGV;

for my $f (@ARGV) {
   print STDERR "file = $f\n";

   my $pattern = find_log_pattern($f);

   if ($pattern) {
      print "file=$f, matched =", Dumper($pattern), "\n";
   } else {
      print "file=$f, cannot match any pattern\n";
      exit 1;
   }

   my $ifh = get_in_fh($f);

   while(<$ifh>) {

   }
}
