#!/usr/bin/env perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;

my $prog = $0; $prog =~ s:.*/::;

my $delimiter = ":";

sub usage {
   my ($message) = @_;

   print "$message\n" if $message;

   print STDERR <<"END";
Usage:

   $prog prod|dr map.csv

   This script check DNS mapping between logical name and physical prod and dr name, used
   during failover process.

   map.csv contains the mapping.

   -v          verbose mode

Examples:

   $prog prod chkdns_test.csv
   $prog dr   chkdns_test.csv

END

   exit 1;
}

my $verbose;

GetOptions(
   'v|verbose' => \$verbose,
   ) || usage ("cannot parse command line: $!");
usage("wrong number of args") if @ARGV != 2;

my ($side, $file) = @ARGV;

usage "unknown side='$side'" if $side !~ /^(prod|dr)$/i;

my $error = 0;
my $rowno = 0;
  
open my $fh, "<$file" or die "cannot read $file";

while (<$fh>) {
   $rowno ++;

   next if /^\s*#/; 
   next if /^\s*$/; 
   next if /^logical,/;  # skip header 

   chomp;

   my $line = $_;

   my ($logical, $prod, $dr, $comment) = split /,/, $line, 4; 

   my $physical = ($side =~ /^prod/i) ? $prod : $dr;

   if (!$physical) {
      print "ERROR: bad format at row #$rowno: $line\n";
   }
                  
   my $logical_ip  = get_ipv4($logical);
   my $physical_ip = get_ipv4($physical);

   if ($logical_ip && $physical_ip && $logical_ip eq $physical_ip) {
      print "OK:    logical ($logical $logical_ip) and $side ($physical $physical_ip) match\n";
   } else {
      print "ERROR: logical ($logical $logical_ip) and $side ($physical $physical_ip) don't  match\n";
      $error ++;
   }
}

close $fh;

if ($error) {
   print "ERROR: total $error errors\n";
} else {
   print "OK:    All good.\n";
}

exit $error;

##############################################################
# subs
##############################################################
   
sub get_ipv4 {
   my ($hostname, $opt) = @_;

   # https://unix.stackexchange.com/questions/50365/getent-hosts-prints-ipv6-getent-ahosts-prints-ipv4
   # Both getent hosts and getent ahosts can potentially print both IPv4 and IPv6 addresses,
   # but they decide which address(es) to print differently (that's the point of having two
   # different commands).

   # hosts calls gethostbyname2 (the IPv6-supporting variant of gethostbyname). The behavior
   # is hard-coded: look up an IPv6 address, and if none exists, look up an IPv4 address.

   # ahosts calls getaddrinfo. This function enumerates all protocols for a given name, so
   # it can return both IPv4 and IPv6 addresses in the same call. What it returns is 
   # determined by the settings in /etc/gai.conf. Because many applications are still
   # struggling to cope with IPv6, most distributions prefer IPv4 by default and only use
   # IPv6 by explicit request.

   # SOCK_STREAM (reliable stream-oriented service or Stream Sockets)
   # SOCK_DGRAM (datagram service or Datagram Sockets)
   # SOCK_SEQPACKET (reliable sequenced packet service), or
   # SOCK_RAW (raw protocols atop the network layer).

   my @ahosts = `getent ahosts $hostname`;
   chomp @ahosts;

   for my $line (@ahosts) {
      if ( $line =~ /^(\d+[.]\d+[.]\d+[.]\d+)\s/) {
         return $1;
      }
   }

   print "WARN:   cannot find ipv4 for $hostname\n", join("\n  ", @ahosts), "\n"; 
   return "";
}
