#!/bin/bash

. $TPSUP/profile

for cmd in tpscripts kdbnotes tpnotes mycpp joomla kivy java
do 
   echo ""
   echo "------ $cmd -------"
   echo ""
   $cmd 2>/dev/null || continue
   (set -x; git status)
   echo ""
   (set -x; git fetch --dry-run)
done
