#!/bin/bash
   
usage () {
   cat <<EOF
usage:

   $0 dir|file

   check php file syntax recursively

examples:

   $0 .

EOF
   exit 1
}

if [ $# -lt 1 ]; then
   echo "wrong number of args"
   usage
fi

export PATH=$PATH:/usr/local/bin:

verbose=N

while getopts hds v; do
   case "$o" in
      v) verbose=Y;;
     #x) exclude=$OPTARG;;
      *) echo "unknow switch '$o'"; usage;;
   esac
done

shift $((OPTIND-1))

for path in "$@"
do
   for f in `find $path -name \*.php`
   do
      echo $f
      php -l $f |grep -v "No syntax errors detected"
   done
done
