#!/usr/bin/perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;

my $prog = $0; $prog =~ s:.*/::;

sub usage {
   my ($message) = @_;

   print "$message\n" if $message;

   print STDERR <<"END";
Usage:

   $0 pattern path1:path2:...

   delete path components matching the pattern

   -v verbose mode

Examples:

   $0 tpsup "\$PATH"
   $0 tpsup "\$LD_LIBRARY_PATH"

END

   exit 1;
}

my $verbose;

GetOptions(
   'v|verbose' => \$verbose,
) || usage ("cannot parse command line: $!");

usage("wrong number of args") if @ARGV != 2;

my ($pattern, $old_path) = @ARGV;

print STDERR "old_path=$old_path\n";

my @old = split /:/, $old_path;

my @new;

for my $p (@old) {
   if ($p =~ /$pattern/) {
      print STDERR "dropping $p\n";
   } else {
      push @new, $p;
   }
}

my $new_path = join(":", @new);

print STDERR "new_path=$new_path\n";

print "$new_path\n";

exit 0;
