#!/usr/bin/env perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;
use TPSUP::UTIL    qw(get_in_fh);
# use Carp::Always;

my $prog = $0; $prog =~ s:.*/::;

my $comment_pattern = '[#;]';

sub usage {
   my ($message) = @_;
   print "$message\n" if $message;

   print << "END";
usage:

   $prog [-q] original.cfg
   
description:
   
   extract pure config for record purpose.
   remove blank lines.
   remove all comments. comment start with pattern '$comment_pattern' 

   -v       verbose mode

examples:

   $prog /etc/samba/smb.conf

END

   exit 1;
}

my $verbose;

GetOptions(
   'v|verbose'     => \$verbose,
) || usage("cannot parse command line: $!");

usage("wrong number of args") if @ARGV != 1;

my ($file) = @ARGV;

my $ifh = get_in_fh($file);

while (<$ifh>) {
   next if /^\s*$/;                    # skip blank lines
   next if /^\s*$comment_pattern/;     # skip comment

   print;
}

close $ifh if $ifh != \*STDIN;

exit 0;
