#!/bin/bash

usage () {
   cat <<EOF
usage:

   $0 module

examples:

   $0 Carp
   $0 Data::Dumper
   $0 Inline::MakeMaker
   $0 TPSUP::CSV

EOF
   exit 1
}

if [ $# -eq 0 ]; then
   echo "wrong number of args"
   usage
fi

which perl

for i in $@
do
   short=`echo $i|sed -e 's/::/\//g;s/$/.pm/'`

   echo "perl -M$i -e \"print \\\$INC{'$short'}\""

   perl -M$i -e "print \$INC{'$short'}"

   echo ""
done
