#!/bin/bash

usage () {
   cat <<EOF
usage:

   $0 file

   find the rpm name for a file

   note:
   use findrpm on rhel/centos/fedora.
   use findpkg on ubuntu/debian.

examples:

   $0 libc.so

EOF
   exit 1
}

if [ $# -eq 0 ]; then
   echo "wrong number of args"
   usage
fi

# check whether /etc/os-release ID=...
if ! [ -f /etc/os-release ]; then
   echo "this OS is not linux because /etc/os-release does not exist"
   exit 1
fi

ID=$(grep -i '^ID=' /etc/os-release | cut -d= -f2 | tr -d '"')
if [[ $ID =~ ^(rhel|centos|fedora)$ ]]; then
   echo "this is a $ID system"
elif [[ $ID =~ ^(ubuntu|debian)$ ]]; then
   echo "ERROR: this is an ubuntu/debian system. use findpkg instead"
else
   echo "ERROR: this is not a rhel/centos/fedora or ubuntu/debian system"
   exit 1
fi


# sometimes 3rd party (anaconda) lib gets linked to rpm command, causing error
unset LD_LIBRARY_PATH

for i in $@
do
   echo "rpm --filesbypkg -aq|egrep -i 'Si'"

   rpm --filesbypkg -aq|egrep -i "$i"

   echo

done
