#!/bin/bash
   
prog=`basename $0`

usage () {
   cat <<EOF
usage:

   locate java code.

   - to use specific jar files
   $prog pattern jarl jar2 ...

   - to use the CLASSPATH
   $prog pattern env

   -d dump the code. it does "javap my.class" to disassemble class file.
   -h print header of the code
   -s save tmp dir for troubleshooting, default is no

examples:

   $prog FileFixPublisher env
   $prog FileFixPublisher *jar

   - often, we need set up env before search, 
     for example, github/antlr/examples/06_vistor_if_else has this code
        import org.antlr.v4.runtime.CharStreams;
        ... CharStreams.fromFileName("test.mu") ...
     to confirm formFileName was defined in CharStreams
        $ siteenv             # this loads antlrenv and javaenv functions
        $ antlrenv default    # this sets CLASSPATH
        $ javaenv 11          # this sets java and jar executables path
        $ findjar org.antlr.v4.runtime.CharStreams env
        $ findjar -d org.antlr.v4.runtime.CharStreams env |grep fromFileName

   - to explode a jar file
      mkdir junkdir
      cd junkdir
      jar -xvf found.jar

   - to extract a component from a jar file to stdout.  
      unzip -q -c /c/users/william/sitebase/java/lib/antlr-4.13.0-complete.jar \\
         org/antlr/v4/runtime/CharStreams.class
         -q    quiet
         -c    to stdout

EOF
   exit 1
}

if [ $# -lt 2 ]; then
   echo "wrong number of args"
   usage
fi

dump=N
header=N
save_tmp_dir=N
# where is java
export PATH=$PATH:/usr/local/bin:

while getopts hds o; do
   case "$o" in
      h) header=Y;;
      d) dump=Y;;
      s) save_tmp_dir=Y;;
     #x) exclude=$OPTARG;;
      *) echo "unknow switch '$o'"; usage;;
   esac
done

shift $((OPTIND-1))

pattern="$1"
shift

check_jar () {
   f=$1
   pattern=$2

   line=`jar -tvf $f |grep -si "$pattern"`

   if [ "X$line" != "X" ];then
      echo ""
      echo $line
      echo "found in $f"

      if [ $dump = Y -o $header = Y ]; then
         path=`echo $line |sed -e 's:.* ::'`
         #echo $path
         tmpdir=`get_tmp /tmp findjar`

         [ -d $tmpdir ] || mkdir $tmpdir || exit 1

         oldpwd=`pwd`
         abspath=`readlink -f $f`
         cd $tmpdir
         jar -xvf $abspath $path

         if [ $header = Y ]; then
            echo ""
            javap $path
            echo ""
         fi

         if [ $dump = Y ]; then
            echo ""
            # javap - Disassembles one or more class files.
            #   -c  - prints disassembled code.
            javap -c $path
            echo ""
         fi

         if [ $save_tmp_dir = Y ]; then
            echo "class file is saved at: "
            readlink -f $path
         else
            /bin/rm -fr $tmpdir
         fi

         cd $oldpwd
      fi
   fi
}

if [ "$1" = "env" ]; then
   parts=`echo $CLASSPATH|sed -e 's/:/ /g'`
else
   parts="$@"
fi

for f in `echo $parts`
do
   # https://medium.com/javarevisited/back-to-the-basics-of-java-part-1-classpath-47cf3f834ff
   # The classpath is simply a list of 
   #    - directories, 
   #    - JAR files, 
   #    - ZIP archives

   if [ -d $f ]; then
      echo "TODO: handle dir: $f"
   elif [[ $f =~ jar$ ]]; then
      check_jar $f "$pattern"
   else
      echo "TODO: unknow type at file: $f"
   fi
done

exit 0;

# $ for i in *jar; do if jar -tvf $i | grep -Hsi FileFixPublisher;then echo $i;fi done
# (standard input): 4886 Sat Sep 21 14:25:30 EDT 2013 com/abc/fix/tools/FileFixPublisher.class
# fix-support-tools.jar
# (standard input): 4860 Mon Mar 19 13:08:10 EDT 2012 com/abc/fix/tools/FileFixPublisher.class
# fix-tools.jar
