#!/bin/bash

usage () {
   cat <<EOF
usage:

   $0 file

   find the pkg name for a file

   note: Ubuntu doesn't use rpm.

examples:

   $0 libc.so

EOF
   exit 1
}

if [ $# -eq 0 ]; then
   echo "wrong number of args"
   usage
fi

for i in $@
do
   #(set -x; dpkg -l |egrep -i "$i")
   (set -x; dpkg -S "$i")

   echo

done
