#!/usr/bin/perl

use strict;
use warnings;
use Data::Dumper;
use Carp;
use Getopt::Long;
#use TPSUP::UTIL qw(get_in_fh get_out_fh);

my $prog = $0; $prog =~ s:.*/::;

sub usage {
   my ($msg) = @_;

   print STDERR "$msg\n" if $msg;

   print STDERR << "EOF";
usage:

   $prog symbol_pattern elf1 (elf2 ...)

description:
   
   search for a symbole in elf files using nm command

examples:

   $prog locale /usr/lib/chromium-browser/chromium-browser

EOF

   exit 1;
}

my $verbose;

GetOptions(
   "v"        => \$verbose,
) or usage("Could not parse command line: $!");

usage("wrong number of args") if @ARGV < 2;

my $pattern = shift @ARGV;
#$pattern = qr/$pattern/;

for my $elf (@ARGV) {
   my $prefix = @ARGV == 1 ? "" : "$elf";
   if (! search_nm($elf, $pattern, $prefix)) {
      next;
   }

   my $ldd_command = "ldd $elf";

   my @ldd_output = `$ldd_command`;
   next if $?;

   # tian@linux1:/home/tian$ ldd /usr/lib/chromium-browser/chromium-browser
   #     linux-vdso.so.1 (0x00007ffebf1ec000)
   #     libffmpeg.so => /usr/lib/chromium-browser/libffmpeg.so (0x00007f4c2b05b000)
   #     ...
   # note: vdso is provided by kernel, not from file system. see vdso(7)

   for my $line (@ldd_output) {
      if ($line =~ /(.+?) => (.+)/) {
         my ($lib, $resolution) = ($1, $2);
         $lib =~ s:^\s+::;

         if ($resolution =~ /not found/) {
            print "$prefix:ldd: $lib not found\n";
         } elsif ($resolution =~ /(.+?) \((.+)\)/)  {
            my ($path, $addr) = ($1, $2);
            search_nm($path, $pattern, $lib);
         } else {
            print "unknown format at line: $line";
            print "from command: $ldd_command\n";
         }
      }
   }
}

sub search_nm {
   my ($elf_file, $pattern, $prefix, $opt) = @_;

   $prefix = $prefix ? "$prefix:nm" : "nm";
   my @nm_output = `nm -D $elf_file`;

   return undef if $?;

   for my $line (@nm_output) {
      if ($line =~ /$pattern/i) {
         print "$prefix: $line";
      }
   }

   return 1;
}
