#!/bin/bash

usage () {
   cat <<EOF
usage:

   $0 file1 file2 ...

   find the rpm/dpkg name for a file

   note:
      rhel/centos/fedora use rpm.
      ubuntu/debian use dpkg.

examples:

   $0 libc.so

EOF
   exit 1
}

if [ $# -eq 0 ]; then
   echo "wrong number of args"
   usage
fi

# sometimes 3rd party (anaconda) lib gets linked to rpm command, causing error
unset LD_LIBRARY_PATH

# check whether /etc/os-release ID=...
if ! [ -f /etc/os-release ]; then
   echo "this OS is not linux because /etc/os-release does not exist"
   exit 1
fi

ID=$(grep -i '^ID=' /etc/os-release | cut -d= -f2 | tr -d '"')
echo "this is a $ID system"
if [[ $ID =~ ^(rhel|centos|fedora)$ ]]; then
   for i in $@
   do
      echo "rpm --filesbypkg -aq|egrep -i 'Si'"

      (set -x; rpm --filesbypkg -aq|egrep -i "$i")
   done
elif [[ $ID =~ ^(ubuntu|debian)$ ]]; then
   for i in $@
   do
      echo "---- match by filename, search in /var/lib/dpkg/info/*.list, case-insensitive ----"
      # 'set -x' will print *.list files, too much output. so we use echo instead.
      # (set -x; grep -Fi "$i" /var/lib/dpkg/info/*.list |sed 's:/var/lib/dpkg/info/::;s/.list:/: /')
      echo "grep -Fi '$i' /var/lib/dpkg/info/*.list |sed 's:/var/lib/dpkg/info/::;s/.list:/: /'"
      grep -Fi "$i" /var/lib/dpkg/info/*.list |sed 's:/var/lib/dpkg/info/::;s/.list:/: /'

      echo ""
      echo "---- match by pkg name, case-sensitive ----"
      (set -x; dpkg -l "$i")

      #echo ""
      #echo "---- match by file name, case-sensitive ----"
      #(set -x; dpkg -S "$i")
   done
else
   echo "ERROR: we only support rhel/centos/fedora or ubuntu/debian system"
   exit 1
fi

echo ""
