#!/bin/bash

prog=$(basename $0)

usage() {
   cat <<END
usage:

   $prog module

   Find whether a node module is a built-in module or not.
   If it is not a built-in module, then find the path to the module.
   The installation could be global or local.
   
examples:
   
      $prog http     # built-in module
      $prog ganache  # not a built-in module
      $prog tianjunk # none-exist module

END

   exit 1
}

if [ $# -ne 1 ]; then
   echo "ERROR: wrong number of arguments"
   usage
fi

module=$1

echo "check whether '$module' is a built-in module"
result=$(
   set -x
   node -e "console.log(require.resolve.paths('$module'))"
)
if [ "$result" == "null" ]; then
   echo "$module is a built-in module"
else
   echo "$module is not a built-in module"
fi

echo ""
echo "check whether '$module' is a local module"
(
   set -x
   npm list $module
)

echo ""
echo "check whether '$module' is a global module"
(
   set -x
   npm list -g $module
)

echo ""
echo "check whether '$module' in registry"
(
   set -x
   npm search $module | grep "^$module\b"
   # npm view $module
)

echo ""
echo "for detail of registry: npm view $module"
