#!/usr/bin/env perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;
# use Carp::Always;

my $prog = $0;
$prog =~ s:.*/::;

sub usage {
   my ($message) = @_;
   print "$message\n" if $message;

   print << "END";
usage:

   $prog    grain fps
 
description:

   fpe formula = 1/2*M*V*V = velcoity (fps) x velocity (fps) x weight (grains) / 450240
   
   1 pfe = 1.356 joule

examples:

   $prog 11.75 1070

END

   exit 1;
}

my $verbose;

GetOptions( 'v|verbose' => \$verbose, ) || usage("cannot parse command line: $!");

usage("wrong number of args") if @ARGV != 2;

my ( $grain, $fps ) = @ARGV;

my $fpe = $grain * $fps * $fps / 450240;
# round to 3 decimal places
printf "%.3f fpe\n", $fpe;

my $joule = $fpe * 1.356;
printf "%.3f joule\n", $joule;
