#!/bin/bash

prog=`basename $0`
dir=`dirname $0`

usage () {
   cat <<EOF
usage:

   $prog  all
   $prog  filename

   -f           force without asking for confrimation
   -n           dryrun
   -m message   commit message, default to 'update'.
   -v           versbose

example:

   $prog all
   $prog scratchpad.txt

EOF

   exit 1
}

force=N
verbose=N
dryrun=''
commit_message=update

while getopts fnvm: o;
do
   case "$o" in
      n) dryrun='--dry-run';;
      f) force=Y;;
      v) verbose=Y;;
      m) commit_message=$OPTARG;;
      *) echo "unknow switch '$o'"; usage;;
   esac 
done

shift $((OPTIND-1))

if [ $# -eq 0 ]; then
   echo "wrong number of args"
   usage
fi

if [ $1 = all ]; then
   ( set -x; git add $dryrun -A )
else 
   ( set -x; git add $dryrun "$@" )
fi

echo ""

# run git diff only if the remote repo is not empty - it had commits
# if the repo is empty, there is no commit.
# if we run git diff against empty remote repo, we get error:
# fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
# https://stackoverflow.com/questions/5491832
if git rev-parse HEAD 1>/dev/null 2>&1; then
   # remoterepo is not empty - it had commits
   ( set -x; git diff --cached --name-only )
   echo ""
fi

( set -x; git commit $dryrun -m "$commit_message" )
rc=$?
echo ""

if [ $rc -eq 0 ]; then
   ( set -x; git diff --stat --cached origin/master )
   echo ""
   
   if [ $force = N ]; then
      echo "Do you want to push the changes Y|N ? [N]"
      read answer
   
      if [ "X$answer" != "XY" -a "X$answer" != "Xy" ]; then
          echo "Answer is '$answer'. Therefore, skipped $f."
          exit 0
      fi
   fi
   
   echo ""
   ( set -x; git push $dryrun )
   echo ""
   ( set -x; git status )
fi
