#!/bin/bash

# set CLASSPATH=".;%SITEBASE%\java\lib\antlr-4.9.3-complete.jar"
# java org.antlr.v4.Tool %*

usage () {
   cat >&2 <<EOF
usage:

   $0 grammar_name rule_to_test

examples:

   $0 Chat chat

EOF
   exit 1
}

if [ $# -eq 0 ]; then
   echo "wrong number of args" >&2
   usage
fi

UNAME=`uname -a`
if [[ $UNAME =~ Cygwin ]] ; then
   # Cygwin 
   jar=`cygpath -w "$SITEBASE/java/lib/antlr-4.9.3-complete.jar"`
   export CLASSPATH=".;$jar"
elif [[ $UNAME =~ Linux ]] || [[ $UNAME =~ Msys ]] ; then
   # linux or GitBash
   export CLASSPATH=".:$SITEBASE/java/lib/antlr-4.9.3-complete.jar"
else
   echo "unsupported os: $UNAME" >&2
   usage 
fi

echo "CLASSPATH=$CLASSPATH"
java org.antlr.v4.gui.TestRig $@
