#!/bin/bash

# set CLASSPATH=".;%SITEBASE%\java\lib\antlr-4.9.3-complete.jar"
# java org.antlr.v4.Tool %*

usage () {
   cat >&2 <<EOF
usage:

   $0 grammar_name rule_to_test

examples:

   $0 Chat chat

EOF
   exit 1
}

if [ $# -eq 0 ]; then
   echo "wrong number of args" >&2
   usage
fi

. $TPSUP/profile
antlrenv default

set -x
# antlr CLASSPATH need two parts
#    the download jar file
#    the dir - normally . - which has the generated class files. runtime needs this one.
java -cp "$ANTLR_JAR:." org.antlr.v4.gui.TestRig $@

