#!/usr/bin/perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;
use TPSUP::FILE qw(get_in_fh get_out_fh);

my $prog = $0;
$prog =~ s:.*/::;

sub usage {
   my ($message) = @_;

   print "$message\n" if $message;

   print STDERR << "END";
usage:

   $prog input

   wrap html body around input

   -title string           html title

   -o output.hmtl          default to STDOUT

examples:

    csv2html -TableOnly tpcsv2_test.csv | $prog -

END

   exit 1;
}

my $verbose;
my $title;
my $output = "-";

GetOptions(
   'v|verbose'  => \$verbose,
   'title=s'    => \$title,
   'o|output=s' => \$output,
) || usage("cannot parse command line: $!");

usage("wrong number of args") if @ARGV != 1;

my ($input) = @ARGV;

my $opt = {
   verbose      => $verbose,
   CSVHTMLTitle => $title,
};

my $input_string = slurp( $input, $opt );

my $out_fh = get_out_fh($output);

print {$out_fh} wrap_in_html_body( \$input_string ), "\n";

exit 0;

#####################################################
# subs
#####################################################

# https://perlmaven.com/slurp
sub slurp {
   my ( $input, $opt ) = @_;

   my $in_fh = get_in_fh( $input, $opt );

   local $/ = undef;

   my $cont = <$in_fh>;

   close $in_fh if $in_fh != \*STDIN;

   return $cont;
}

sub wrap_in_html_body {
   my ( $string_ref, $opt ) = @_;

   my $html = "<HTML><body bgcolor=white>";

   my $title = defined $opt->{CSVHTMLTitle} ? $opt->{CSVHTMLTitle} : "";

   $html .= "<title>$title</title>\n";

   $html .= $$string_ref;

   $html .= "</body></HTML>";

   return $html;
}

