#!/bin/bash

prog=`basename $0`

usage () {
   cat >&2 <<EOF
usage:

   $prog jar

   print the version of jar file
      https://stackoverflow.com/questions/5834794
      unzip -p file.jar META-INF/MANIFEST.MF

examples:

   $prog   /c/users/william/sitebase/java/lib/antlr-4.9.3-complete.jar 

EOF

   exit 1
}

verbose=N
while getopts v o;
do
   case "$o" in
      v) verbose=Y;;
      #s) site_dir="$OPTARG";;
      *) echo "unknow switch '$o'"; usage;;
   esac
done

shift $((OPTIND-1))

if [ $# -ne 1 ]; then
   echo "wrong number of args"
   usage
fi

jar=$1

( set -x; unzip -p $jar META-INF/MANIFEST.MF )
