#!/bin/bash

prog=`basename $0`
delimiter=':'

usage="
usage:

    $prog [path]

   'path' can be any env var, default to PATH

   -d delimiter, default to '$delimiter'

example:

   $prog PATH
   $prog LD_LIBRARY_PATH
"

while getopts "d:" opt; do
   case $opt in
      d)
         delimiter="$OPTARG"
         ;;
      \?)
         echo "ERROR: invalid option -$OPTARG" >&2
         echo "$usage" >&2
         exit 1
         ;;
   esac
done
shift $((OPTIND - 1))

if [ $# -ne 1 ]; then
   echo "ERROR: wrong number of args" >&2
   echo "$usage" >&2
   exit 1
fi

path=$1

resolved=`eval "echo \\\$$path"`

echo "$resolved" | /bin/sed -e "s/$delimiter/\n/g" | while read line
do
   echo "$line"
done
