#!/usr/bin/env perl

use strict;
use Data::Dumper;
use Carp;
use Getopt::Long;
#use File::ReadBackwards;
use TPSUP::DATE qw(get_interval_seconds);
use TPSUP::LOG qw(get_PatternCfg);
use TPSUP::FIX qw(parse_fix_message);
use TPSUP::UTIL qw(get_out_fh get_in_fh);
use TPSUP::DATE qw(get_Mon_by_number yyyymmddHHMMSS_to_epoc);

my $prog = $0; $prog =~ s:.*/::;
my $dir  = $0; $dir  =~ s:[^/]+$::;

my $min_idle = 60;
my $grepmax = 200;
my $yyyy = `date +%Y`; chomp $yyyy;

sub usage {
   my ($msg) = @_;

   print STDERR "$msg\n" if $msg;

   print STDERR << "EOF";
usage:

   $prog log
   $prog -
   
description:
   to check whether a sequence of events happened in the log.
   
   The configurations are by default in $dir/log_pattern.csv.
   
   -x exclude_pattern             Perl style, exclude lines with this pattern
   -m   match_pattern             Perl style, only count the lines with this pattern
   
   -app App                       As it is in pattern_file .
                                  this is required to handle timestamps

   -pf  pattern_file              pattern file, default to $dir/log_pattern.csv.
   
   -t TimePattern                 Perl style. Default is in $dir/log_pattern.csv.
   -a Assignment                  How to assign the matched time_pattern. Default is in $dir/log_pattern.csv.
   -k TimeKey                     default is in $dir/log_pattern.csv. use ',' as separator.
                                  eg, -k HH,MM,SS
   
   -event tag=pattern             define event tag to specify a chain of events, in order.
                                  can define multiple times
   
   -test test=expression
   -test test:attr1,attr2=expression
                                  Perl expression
                                  can define multiple times
                                  'attr' are attributes of the test. 
                                      'continue' means to continue if failed. default to exit.
   
   -reset tag                     clear all events after matched these tag's patterns happend.
                                  can define multiple times
   
   -halt tag                      stop parsing after matched these tag's pattern, until reset.
                                  can define multiple times

   -exit tag                      exit parsing after matched these tag's pattern happend.
                                  can define multiple times
   
   -geneos                        output into geneos-friendly csv format
   
   -progress int                  to show progress every this number of lines, a positive integer.
   -grep  pattern                 grep lines matching this pattern and print out at the end.
   -grepv pattern                 not to grep lines matching this pattern, used with -grep
   -grepmax int                   max lines to grep, default to $grepmax
   
   -tail number                   Staring from this number of lines backward from end of file
   
   -front number                  only parse these number of lines from beginning
   
   -startpattern exp              Staring from this pattern
   
   -starttime time                Staring from this time and after.
   
   -backpattern exp               Staring from last pattern from end of file
   
   -backtime time                 Staring from this time and after.
                                  This searches from end of file, the time is in the format
                                  decided by the app.
   
   -backseconds number            Go back this number of seconds from now. This setting
                                  will be converted into backtime
   
   -endtime time                  End searching after this time

   -now yyyymmddHHMMSS            use this during test, to fake the current time.
   
   -print                         print matching lines
   
   -oid order_id                  trace this order, can be tag 11,41,17,37. can set multiple times.
   
   -output output.txt             default to stdout

   -v                             verbose. -v -v will increase verbose

examples:
   
   - timestamp-based test
   $prog -app syslog \\
   -event "begin=testapp started, config =" \\
   -event "feeds=reading from /dev/null" \\
   -event "runsql=running sql/positions.sql" \\
   -event "complete=entered state=(.+?)\\\\b" \\
   -reset begin \\
   -halt complete \\
   -test has_begun='defined(\$time{begin}[0])' \\
   -test has_got_feeds='defined(\$time{feeds}[0])' \\
   -test has_run_sql='defined(\$time{runsql}[0])' \\
   -test has_completed='defined(\$time{complete}[0])' \\
   -test got_feeds_before_complete:continue='\$time{feeds}[0] lt \$time{complete}[0]' \\
   -test got_postion_before_complete:continue='\$time{runsql}[0] lt \$time{complete}[0]' \\
   -test complete_status_is_DONE='\$value{complete}[0][0] eq "DONE"' \\
   log_event_test.log

   OK: PASSED: has_begun defined(\$time{begin}[0]) => defined(Sep18081606)
   OK: PASSED: has_got_feeds defined(\$time{feeds}[0]) => defined(Sep18081606)
   OK: PASSED: has_run_sql defined(\$time{runsql}[0]) => defined(Sep18081635)
   OK: PASSED: has_completed defined(\$time{complete}[0]) => defined(Sep18092635)
   OK: PASSED: got_feeds_before_complete \$time{feeds}[0] lt \$time{complete}[0] => Sep18081606 lt Sep18092635
   OK: PASSED: got_postion_before_complete \$time{runsql}[0] lt \$time{complete}[0] => Sep18081635 lt Sep18092635
   OK: PASSED: complete_status_is_DONE \$value{complete}[0][0] eq "DONE" => DONE eq "DONE"

   - row-based test, in case row is not timestamped. this should be faster than time-based.
   $prog \\
   -event "begin=testapp started, config =" \\
   -event "feeds=reading from /dev/null" \\
   -event "runsql=running sql/positions.sql" \\
   -event "complete=entered state=(.+?)\\\\b" \\
   -reset begin \\
   -halt complete \\
   -test has_begun='defined(\$row{begin}[0])' \\
   -test has_got_feeds='defined(\$row{feeds}[0])' \\
   -test has_run_sql='defined(\$row{runsql}[0])' \\
   -test has_completed='defined(\$row{complete}[0])' \\
   -test got_feeds_before_complete:continue='\$row{feeds}[0] < \$row{complete}[0]' \\
   -test got_postion_before_complete:contine='\$row{runsql}[0] < \$row{complete}[0]' \\
   -test complete_status_is_DONE='\$value{complete}[0][0] eq "DONE"' \\
   log_event_test.log

   OK: PASSED: has_begun defined(\$row{begin}[0]) => defined(2)
   OK: PASSED: has_got_feeds defined(\$row{feeds}[0]) => defined(12)
   OK: PASSED: has_run_sql defined(\$row{position}[0]) => defined(13)
   OK: PASSED: has_completed defined(\$row{complete}[0]) => defined(16)
   OK: PASSED: got_feeds_before_complete \$row{feeds}[0] < \$row{complete}[0] => 12 < 16
   OK: PASSED: got_postion_before_complete \$row{runsql}[0] < \$row{complete}[0] => 13 < 16
   OK: PASSED: complete_status_is_DONE \$value{complete}[0][0] eq "DONE" => DONE eq "DONE"

   - put the test detail in a plan file
   $prog -app syslog -plan log_event_test_plan.txt log_event_test.log

   - grep the state of the last start
   $prog \\
      -event "begin=testapp started, config =" -reset begin \\
      -grep state= -grepmax 1 \\
      log_event_test.log

   - the following is like a tail command
   $prog -app syslog -backtime "Sep 18 13:02:33" -print log_event_test.log
   $prog -app syslog -backpattern "Starting Message of the Day" -print log_event_test.log
   
   - assume now to be a different time 'Sep 18 13:18:00', need to follow the format.
   $prog -app syslog -now ${yyyy}0918131800 -backseconds 300 -print log_event_test.log
   (you should see only three lines: two at 13:15:01 and one at 13:17:01)
   
   - the following is to trace an order
   $prog -progress 100000 -app syslog -oid USABC999-1 -print log_event_test.log
   
   - to extact a period of a log file
   $prog -app syslog -starttime "Sep 18 13:02:33" -print log_event_test.log
   $prog -app syslog -starttime "Sep 18 13:02:33" -endtime "Sep 18 13:02:34" -print log_event_test.log

   - use -k TimeKey to simplify the timestamp comparation
     the following should get the same output as the above command. add -v to see the internal.
   $prog -app syslog -k HH,MM,SS -starttime "Sep 18 13:02:33" -endtime "Sep 18 13:02:34" -print log_event_test.log
   
EOF
   
   exit 1;
}
   
our ($exclude_pattern, $match_pattern, $App, $pattern_file, $TimePattern, $Assignment, $TimeKey) = @_;

my $verbose = 0;
my @events;
my @tests;
my @resets;
my @exits;
my @halts;
my $geneos;
my $progress;
my $tail;
my $grep;
my $grepv;
my $startpattern;
my $starttime;
my $endtime;
my $backpattern;
my $backtime;
my $backseconds;
my $print;
my $front;
my @oids;
my $output;
my $fake_now;
my $plan;
   
GetOptions(
   "x=s" => \$exclude_pattern,
   "m=s" => \$match_pattern,
   "i=s" => \$min_idle,
   "v+"  => \$verbose,  
   "t=s" => \$TimePattern,
   "a|assignment=s" => \$Assignment,
   "pf=s" => \$pattern_file,
   "app=s" => \$App,
   "k=s" => \$TimeKey,
   "event=s"=> \@events,
   "test=s" => \@tests,
   "reset=s"=> \@resets,
   "exit=s" => \@exits,
   "halt=s" => \@halts,
   "g|geneos" => \$geneos,
   "progress=s" => \$progress,
   "tail=s" => \$tail,
   "grep=s" => \$grep,
   "grepv=s" => \$grepv,
   "grepmax=s" => \$grepmax,
   "startpattern=s" => \$startpattern,
   "starttime=s" => \$starttime,
   "endtime=s" => \$endtime,
   "backpattern=s" => \$backpattern,
   "backtime=s" => \$backtime,
   "backseconds=s" => \$backseconds,
   "print" => \$print,
   "front=s" => \$front,
   "oid=s"=> \@oids,
   "output=s"=> \$output,
   "now=s"=> \$fake_now,
   "plan=s"=> \$plan,
) or usage("Could not parse command line: $!");
   
usage("wrong number of args") if !@ARGV;
   
usage("-progress must be followed by a positive integer")
   if $progress && "$progress" !~ /^[1-9][0-9]*/;
   
my @oid_tags = qw(11 41 17 37);
my $oid_tags_piped = join("|", @oid_tags);   # qw(11 41) -> "11|41"

my $seen_oid;
my $oid_pattern;
my $oid_pattern_compiled;
my $oid_pattern_with_tags;
my $oid_pattern_with_tags_compiled;
      
sub update_oid_pattern {
   $oid_pattern          = join("|", keys(%$seen_oid));
   $oid_pattern_compiled = qr/\b($oid_pattern)\b/;

   $oid_pattern_with_tags          = "($oid_tags_piped)=($oid_pattern)";
   $oid_pattern_with_tags_compiled = qr/\b$oid_pattern_with_tags\b/;

   $verbose && print STDERR "updated oid_pattern=\\b($oid_pattern)\\b\n";
   $verbose && print STDERR "updated oid_pattern_with_tags=\\b$oid_pattern_with_tags\\b\n";
}

if (@oids) {
   # this pre-filter will speed up but will also filter out none fix-message lines
   # therefore, i took it out from default
   # if (!$match_pattern) {
   #   $match_pattern = '35=';
   #}

   for my $oid (@oids) {
      $seen_oid->{$oid}->{cmdline} ++;
   }

   update_oid_pattern();
}
   
my $out_fh = get_out_fh($output);
   
die "no events defined" if !@events && !$print && !$grep && !$grepv && !@oids && !$plan;

my  $grep_compiled = qr/$grep/;
my $grepv_compiled = qr/$grepv/;
         
my $cfg;
my @assignments;
my @timekeys;
if ($App) {
   $cfg = get_PatternCfg({
      PatternFile => $pattern_file,
      RemoveInputQuotes => 1,
      App               => $App,
      TimePattern       => $TimePattern,
      Assignment        => $Assignment,
      TimeKey           => $TimeKey,
      CheckSettings     => [ qw(TimePattern Assignment TimeKey) ],
   });
   
   @assignments = split /,/, $cfg->{Assignment};
   @timekeys = split /,/, $cfg->{TimeKey};

   # https://perldoc.perl.org/perlop.html#Regexp-Quote-Like-Operators
   # use qr// to precompile to speed up
   if (defined($cfg->{TimePattern})) {
      $cfg->{TimePattern_compiled} = qr/$cfg->{TimePattern}/;
   }
}

$verbose && print "cfg = ", Dumper($cfg);
$verbose && print "\@assignments = ", Dumper(\@assignments);
$verbose && print "\@timekeys = ",    Dumper(\@timekeys);
         
if (defined $exclude_pattern) {
   $exclude_pattern = qr/$exclude_pattern/;
}
         
if (defined $match_pattern) {
   $match_pattern = qr/$match_pattern/;
};
         
if (defined $startpattern) {
   $startpattern = qr/$startpattern/;
};
         
my $backpattern_compiled;
if (defined $backpattern) {
   $backpattern_compiled = qr/$backpattern/;
};

my $array_by_directive;
if ($plan) {
   my $fh = get_in_fh($plan);

   my $to_be_continued;
   while (my $line = <$fh>) {
       chomp $line;
       if ($to_be_continued) {
          if ($line =~ /^(.*)\\$/) {
             # \ at the end of line means to continue to the next line
             $array_by_directive->{$to_be_continued}->[-1] .= "$1\n";
          } else {
             $array_by_directive->{$to_be_continued}->[-1] .= $line;
             $to_be_continued = undef;
          }
       } elsif ($line =~ /^\s*(event|test|reset|halt|exit)\s+(\S+.*)/) {
          my ($directive, $detail) = ($1, $2);

          if ($detail =~ /^(.*)\\$/) {
             # \ at the end of line means to continue to the next line
             push @{$array_by_directive->{$directive}}, "$1\n";
             $to_be_continued = $directive;
          } else {
             push @{$array_by_directive->{$directive}}, $detail;
          }
       } elsif ($line =~ /^\s*#|^\s*$/) {
          # skip comment and blank lines
          next;
       } else {
          die "failed to parse plan $plan at: $line\n";
       }
   }
   close $fh;

   $verbose && print "array_by_directive = \n", Dumper($array_by_directive);

   push @events, exists $array_by_directive->{event} ? @{$array_by_directive->{event}} : ();
   push @tests,  exists $array_by_directive->{test}  ? @{$array_by_directive->{test}}  : ();
   push @resets, exists $array_by_directive->{reset} ? @{$array_by_directive->{reset}} : ();
   push @halts,  exists $array_by_directive->{halt}  ? @{$array_by_directive->{halt}}  : ();
   push @exits,  exists $array_by_directive->{exit}  ? @{$array_by_directive->{exit}}  : ();
}
         
my          $pattern_by_tag;
my $compiled_pattern_by_tag;
for my $e (@events) {
   if ($e =~ /^(.+?)=(.+)/s ) {
      # multiline regex match
      my ($tag, $pattern) = ($1, $2);
         
      croak "tag='$tag' shows up multiple times in -event" if exists $pattern_by_tag->{$tag};
         
               $pattern_by_tag->{$tag} =    $pattern;
      $compiled_pattern_by_tag->{$tag} = qr/$pattern/;
   } else {
      croak "event='$e' bad format";
   }
}
         
my @tags = sort(keys(%$pattern_by_tag));
         
my $is_reset_tag;
for my $t (@resets) {
   croak "'$t' in -reset '$t' is not defined in -event"
       if ! exists $pattern_by_tag->{$t};
   $is_reset_tag->{$t} ++;
}
$verbose && print "is_reset_tag = ", Dumper($is_reset_tag);
         
my $is_exit_tag;
for my $t (@exits) {
   croak "'$t' in -exit '$t' is not defined in -event"
      if ! exists $pattern_by_tag->{$t};
   $is_exit_tag->{$t} ++;
}
$verbose && print "is_exit_tag = ", Dumper($is_exit_tag);

my $is_halt_tag;
for my $t (@halts) {
   croak "'$t' in -halt '$t' is not defined in -event"
      if ! exists $pattern_by_tag->{$t};
   $is_halt_tag->{$t} ++;
}
$verbose && print "is_halt_tag = ", Dumper($is_halt_tag);

my $check_tag_during_on_halt = {};
for my $t ((@resets,@exits)) {
   $check_tag_during_on_halt->{$t} ++;
}
my @on_halts = sort(keys %$check_tag_during_on_halt);
$verbose && print "\@on_halts = ", Dumper(\@on_halts);
      
my $tag_will_capture;
my @test_tag_expressions;
      
for my $test (@tests) {
   my ($front, $expression);
      
   if ($test =~ /^(.+?)=(.+)/s ) {
      # multiline regex match
      ($front, $expression) = ($1, $2);
   } else {
      croak "test='$test' bad format";
   }

   my ($test_tag, $attrString) = split /:/, $front;

   my $has_attr = {};
   if ($attrString) {
      my @a = split /,/, $attrString;
      for my $e (@a) {
         $has_attr->{$e} = 1;
      }
   }
      
   while ($expression =~ /\$value\{(.+?)\}/g) {
      my $event_tag = $1;
      
      croak "event_tag='$event_tag' in test='$test' is not defined." if ! exists $pattern_by_tag->{$event_tag};
      croak "event_tag='$event_tag' in test='$test' is defined, but not capturing anything." if $pattern_by_tag->{$event_tag} !~ /\(.*\)/;
      $tag_will_capture->{$event_tag} ++;
   }
      
   push @test_tag_expressions, [ $test_tag, $expression, $has_attr ];
}
      
$verbose && print "tag_will_capture ", Dumper($tag_will_capture);
$verbose && print "test_tag_expressions ", Dumper(\@test_tag_expressions);
      
my $error = 0;

for my $f (@ARGV) {
   my $prefix = @ARGV > 1 ? "$f:" : "";

   my   $tried_timestamp_pattern = 0;
   my $matched_timestamp_pattern = 0;
      
   my $fh;
      
   if ($f eq '-') {
      if ($tail) {
         open $fh, "tail -$tail|" or croak "tail -$tail failed";
      } else {
         $fh = \*STDIN;
      }
   } else {
      if (! -f $f) {
         print "${prefix}ERROR: cannot find $f\n" if ! -f $f;
         $error ++;
         next;
      }
      
      if ($f =~ /gz$/) {
         my $cmd = $tail ? "gunzip -c $f |tail -$tail" : "gunzip -c $f";
         open $fh, "$cmd|" or die "cmd=$cmd failed";
      
      } else {
         if ($tail) {
            open $fh, "tail -$tail $f|" or die "tail -$tail $f failed";
         } elsif ($backpattern || $backtime || $backseconds) {
            require File::ReadBackwards;
            my $back = File::ReadBackwards->new($f) or die $!;
            my $backstring;
            my $backstring_criteria;
      
            if ($backseconds) {
               die "must specify -app AppName to parse timestamp" if !$App;

               my $now_seconds;
               if ($fake_now) {
                  $now_seconds = yyyymmddHHMMSS_to_epoc($fake_now); 
               } else {
                  $now_seconds = time();
               }

               my $old_seconds = $now_seconds - $backseconds;
               my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime($old_seconds);
      
               my $r;
               $r->{SS}   = sprintf("%02d", $sec);
               $r->{MM}   = sprintf("%02d", $min);
               $r->{HH}   = sprintf("%02d", $hour);
               $r->{yyyy} = sprintf("%04d", $year+1900);
               $r->{mm}   = sprintf("%02d", $mon+1);
               $r->{dd}   = sprintf("%02d", $mday);
               $r->{d}    = sprintf("%d",   $mday);
               $r->{Mmm}  = get_Mon_by_number($mon+1);
         
               $backstring = join("", @{$r}{@timekeys});
               $backstring_criteria = "le $backstring";
            } elsif ($backtime) {
               die "must specify -app AppName to parse timestamp" if !$App;

               my @a = ($backtime =~ /$cfg->{TimePattern_compiled}/);
      
               die "backtime=$backtime not matching: /$cfg->{TimePattern}/\n" if !@a;
            
               my $r; # ref
               @{$r}{@assignments} = @a;
            
               $backstring = join("", @{$r}{@timekeys});
               $backstring_criteria = "le '$backstring'";
            } elsif ($backpattern) {
               $backstring_criteria = "=~ /$backpattern/";
            }

            $verbose && print STDERR "backstring_criteria: $backstring_criteria\n";
            
            my $line_count = 0;
            my $pos;
            
            my $last_time = time();
            my $last_progress_time = $last_time;
            my $timestring;
            
            while (1) {
               $line_count ++;
            
               if ($front && $line_count >= $front) {
                  $verbose && print STDERR "total front=$front lines parsed. stop\n";
                  last;
               }
            
               my $line = $back->readline();
            
               last if ! defined($line);
            
               if ($progress) {
                  if ($line_count % $progress == 0 ) {
                     my $now = time();
            
                     my $seconds = $now - $last_progress_time;
            
                     $last_progress_time = $now;
            
                     print STDERR "$line_count lines are processed backwards, $progress lines in $seconds seconds\n";
                     if ($verbose) {
                        print STDERR "\nlast test: \$timestring($timestring) <= \$backstring($backstring)\n";
                        print STDERR "$line";
                     }
                  }
               }
               
               next if defined $exclude_pattern && $line =~ /$exclude_pattern/;
               
               next if defined   $match_pattern && $line !~ /$match_pattern/;
               
               my @a = ($line =~ /$cfg->{TimePattern_compiled}/);

               if (!@a) {
                  $tried_timestamp_pattern ++;
                  next;
               }
               $matched_timestamp_pattern ++;
               
               if ($backpattern) {
                  if ($line =~ /$backpattern/) {
                     $pos = $back->tell();
                     $verbose && print STDERR "\nbackpattern=$backpattern found line: $line\n";
                     last;
                  }
               } elsif ($backstring) {
                  die "must specify -app AppName to parse timestamp" if !$App;

                  my $r; # ref
                  @{$r}{@assignments} = @a;

                  $timestring = join("", @{$r}{@timekeys});
               
                  $verbose>=2 && print STDERR "check backward: $timestring le $backstring ?\n";
                  if ($timestring le $backstring) {
                     $pos = $back->tell();
                     $verbose && print STDERR "\nbackward found line: $timestring le $backstring\n$line\n";
                     last;
                  }
               }
            }
               
            {
               my $now = time();
               
               my $seconds = $now - $last_time;
               
               $last_time = $now;
   
               $verbose && print STDERR "total $line_count lines are processed backwards in $seconds seconds\n";
            }
               
            if ($backstring_criteria && !defined $pos) {
               print STDERR "WARN: cannot find the backward position using $backstring_criteria. Going back to beginning of file\n";
               $pos = 0;
            }
               
            if (defined $pos) {
               $fh = $back->get_handle();
               seek($fh, $pos, 0);
            } else {
               croak "cannot find the backward position in $f";
            }
         } else {
            open $fh, "<$f" or die "cannot read $f failed";
            
            if ($startpattern || $starttime) {
               my $startstring;
               my $startstring_criteria;
            
               if ($starttime) {
                  # these two are the same
                  # die "must specify -app AppName to parse timestamp" if !$App;
                  die "must specify -app AppName to parse timestamp" if !$cfg;

                  my @a = ($starttime =~ /$cfg->{TimePattern_compiled}/);
                  die "starttime='$starttime' not matching: $cfg->{TimePattern}" if !@a;
            
                  my $r; # ref
                  @{$r}{@assignments} = @a;

                  $startstring = join("", @{$r}{@timekeys});
                  $startstring_criteria = ">='$startstring'";
               } elsif ($startpattern) {
                  $startstring_criteria = "=~/$startpattern/";
               }
               $verbose && print "startstring_criteria: >='$startstring'\n";
            
               my $line_count = 0;
               my $pos = 0;
               my $found_position;
            
               my $last_time = time();
               my $last_progress_time = $last_time;
               my $timestring;
            
               while (<$fh>) {
                  my $line = $_;
            
                  $line_count ++;
            
                  if ($front && $line_count >= $front) {
                     $verbose && print STDERR "total front=$front lines parsed. stop\n";
                     last;
                  }
                  
                  if ($progress) {
                     if ($line_count % $progress == 0 ) {
                        my $now = time();

                        my $seconds = $now - $last_progress_time;
                  
                        $last_progress_time = $now;
                  
                        print STDERR "$line_count lines are processed, $progress lines in $seconds seconds\n";
                        if ($verbose) {
                           print STDERR "\nlast test: \$timestring($timestring) <= \$startstring($startstring)\n";
                           print STDERR "$line";
                        }
                     }
                  }
                  
                  next if defined $exclude_pattern && $line =~ /$exclude_pattern/;
                  
                  next if defined   $match_pattern && $line !~   /$match_pattern/;
                  
                  if ($App) {
                     # we need to parse timestamp
                     my @a = ($line =~ /$cfg->{TimePattern_compiled}/);
                  
                     if (!@a) {
                        $tried_timestamp_pattern ++;
                        next;
                     }
                     $matched_timestamp_pattern ++;
                  
                     my $r; # ref
                     @{$r}{@assignments} = @a;
                  
                     $timestring = join("", @{$r}{@timekeys});
                  }
                  
                  if ($startpattern) {
                     if ($line =~ /$startpattern/) {
                        $verbose && print STDERR "\nfound start line: $line\n";
                        $found_position = 1;
                        last;
                     }
                  } elsif ($startstring) {
                     $verbose >= 2 && print STDERR "check beginning: $timestring gt $startstring ?\n";
                     if ($timestring gt $startstring) {
                        $verbose && print STDERR "\nfound start line: $timestring gt $startstring\n$line\n";
                        $found_position = 1;
                        last;
                     }
                  }
                  
                  $pos = tell $fh; # save the next line position
               }
                  
               { 
                  my $now = time();
                  
                  my $seconds = $now - $last_time;

                  $last_time = $now;
                  
                  $verbose && print STDERR "total $line_count lines are processed in $seconds seconds\n";
               }
                  
               if ($found_position) {
                  seek($fh, $pos, 0); # move to previous line
               } else {
                  print STDERR "WARN: cannot find start position using $startstring_criteria in $f. skipped the file\n";
                  next;
               }
            }
         }
      }
   }
                  
   my $endstring;
   my $endstring_criteria;
      
   if ($endtime) {
      die "must specify -app AppName to parse timestamp" if !$App;

      my @a = ($endtime =~ /$cfg->{TimePattern_compiled}/);
      die "endtime='$endtime' not matching: $cfg->{TimePattern}" if !@a;
      
      my $r; # ref
      @{$r}{@assignments} = @a;
      
      $endstring = join("", @{$r}{@timekeys});
   }
      
   my %time;
   my %value;
   my %row;
   my $halted;
   my $line_count;
   my $last_time = time();
   my $start_time = $last_time;
   my @grepped;
   my $grepcount = 0;
      
   LINE:
   while (<$fh>) {
      $line_count ++;
      
      if ($front && $line_count >= $front) {
         $verbose && print STDERR "total front=$front lines parsed. stop\n"; last;
      }
         
      if ($progress) {
         if ($line_count % $progress == 0 ) {
            my $now = time();
         
            my $seconds = $now - $last_time;
            
            $last_time = $now;
            
            print STDERR "$line_count lines are processed forwards, $progress lines in $seconds seconds\n";
         }
      }
            
      my $line = $_;

      chomp $line;
         
      next if defined $exclude_pattern && $line =~ /$exclude_pattern/;
         
      next if defined   $match_pattern && $line !~   /$match_pattern/;
          
      my $r; # ref
      if ($App) {
         # we need to parse timestamp
         my @a = ($line =~ /$cfg->{TimePattern_compiled}/);
         
         if (!@a) {
            $tried_timestamp_pattern ++;
            next;
         }
         $matched_timestamp_pattern ++;
         
         @{$r}{@assignments} = @a;
         
         if ($endtime) {
            my $timestring = join("", @{$r}{@timekeys});
            $verbose>=2 && print STDERR "check end: $timestring gt $endstring ?\n";
            if ("$timestring" gt "$endstring") {
               $verbose && print STDERR "\nmatched endtime line: $timestring gt $endstring\n$line\n";
               last;
            }
         }
      }
         
      if ($grep && $grepcount < $grepmax && $line =~ /$grep_compiled/ ) {
         if ( !defined($grepv) || $line !~ /$grepv_compiled/ ) {
            $grepcount ++;
            push @grepped, $line;
         }
      }
         
      if (! $seen_oid) {
         # when tracing order, $seen_oid is defined, we will decide whether to print later
         $print && print {$out_fh} "$line\n";
      }
         
      if ($seen_oid) {
         if ($line =~ /$oid_pattern_with_tags_compiled/) {
            my $tag = $1;
            my $val = $2;
         
            $verbose && print STDERR "matched $tag=$val: $line\n";
         
            my $v_by_k = parse_fix_message($line);
            my $need_update_pattern;
            for my $k (@oid_tags) {
               my $v = $v_by_k->{$k};
         
               next if !defined $v || !"$v";
         
               if (!$seen_oid->{$v}->{$k}) {
                  $verbose && print STDERR "new link: $tag=$val => $k=$v\n";
                  $need_update_pattern ++; 
               }
               $seen_oid->{$v}->{$k}++;
            }

            if ($need_update_pattern) {
               $verbose && print STDERR "updated seen_oid = ", Dumper($seen_oid);
               update_oid_pattern();
            }

            # we haven't printed this line. print now
            $print && print {$out_fh} "$line\n";
         } elsif ($line =~ /$oid_pattern_compiled/) {
            $verbose && print STDERR "matched pattern=$1: $line\n";
            $print && print {$out_fh} "$line\n";
         }
      }
         
      my @check_tags;
         
      if ($halted) {
         @check_tags = @on_halts;
      } else {
         @check_tags = @tags;
      }
         
      for my $t (@check_tags) {
         my @captures;
         my $matched;
         
         if ($tag_will_capture->{$t}) {
            @captures = ($line =~ /$compiled_pattern_by_tag->{$t}/);
         } elsif ($line =~ /$compiled_pattern_by_tag->{$t}/) {
            $matched ++;
         }
         
         if ($matched || @captures) {
            $verbose && print STDERR "event='$t' pattern='$pattern_by_tag->{$t}' matched: $line\n";

            my $timestring;
            if ($App) {
               $timestring = join("", @{$r}{@timekeys});
            }

            if ($is_reset_tag->{$t}) {
               $verbose && print STDERR "event='$t' reset processing\n";
               undef %time;
               undef %value;
               push @{$time{$t}}, $timestring if $App;
               push @{$value{$t}}, \@captures if @captures;
               push @{$row{$t}}, $line_count;
               $halted = 0;
               @grepped = ();
               next LINE;
            } elsif ($is_exit_tag->{$t}) {
               $verbose && print STDERR "event='$t' exits processing\n";
               push @{$time{$t}}, $timestring if $App;
               push @{$value{$t}}, \@captures if @captures;
               push @{$row{$t}}, $line_count;
               last LINE;
            } elsif ($halted) {
               $verbose >=2 && print STDERR "event='$t' is skipped while in halted state\n";
               next LINE;
            } elsif ($is_halt_tag->{$t}) {
               $verbose && print STDERR "event='$t' halted processing\n";
               push @{$time{$t}}, $timestring if $App;
               push @{$value{$t}}, \@captures if @captures;
               push @{$row{$t}}, $line_count;
               $halted ++;
               next LINE;
            } else {
               $verbose && print STDERR "event='$t' is saved\n";
               push @{$time{$t}}, $timestring if $App;
               push @{$value{$t}}, \@captures if @captures;
               push @{$row{$t}}, $line_count;
               next LINE;
            }
         }
      }
   }
         
   close $fh if $fh != \*STDIN;
         
   {
      my $now = time();
         
      my $seconds = $now - $start_time;
         
      $verbose && print STDERR "total $line_count lines are processed forwards in $seconds seconds\n";
   }
         
   $verbose && print "\%time = ", Dumper(\%time);
   $verbose && print "\%value = ", Dumper(\%value);
         
   my $warn = $verbose ? 'use' : 'no';
         
   if ($verbose) {
      $Data::Dumper::Deparse = 1;
   }
         
   my $index = 0;
   if ($geneos) {
      print "index,status,check,expression,detail\n";
   }
   
   for my $r (@test_tag_expressions) {
      my ($test_tag, $expression, $attr) = @$r;
   
      my $compiled = eval "$warn warnings; no strict; sub { $expression } ";
      if ($@) { 
         if ($geneos) {
            $index ++;
            print "$index,FAIL,$test_tag,$expression,Bad expression";
         } else {
            print "${prefix}ERROR: $test_tag, $expression,Bad expression: $@\n";
            $error ++;
         }
         last if !$attr->{continue};
      }
   
      if ($compiled->()) {
         if ($geneos) {
            $index ++;
            print "$index,OK,$test_tag,$expression,";
         } else {
            print "${prefix}OK: PASSED: $test_tag $expression => ";
         }
         eval "no warnings; print qq($expression), \"\\n\"";
      } else {
         if ($geneos) {
            $index ++;
            print "$index,FAIL,$test_tag,$expression,";
         } else {
            print "${prefix}ERROR: FAILED: $test_tag $expression => ";
            $error ++;
         }
         eval "no warnings; print qq($expression), \"\\n\"";
         last if !$attr->{continue};
      }
   }
      
   if ($grep) {
      $verbose && print STDERR "$grepcount lines matching pattern='$grep'. ",
            $grepcount>$grepmax ? "truncated to $grepmax lines" : "",
            ";\n";
      
      for my $line (@grepped) {
         print "$line\n";
      }
   }

   if ($tried_timestamp_pattern) {
      my $matched_percentage = $matched_timestamp_pattern*100/$tried_timestamp_pattern;

      if ($matched_percentage < 5) {
         print STDERR "timestamp pattern='$cfg->{TimePattern}' is likely wrong, because only $matched_percentage% ($matched_timestamp_pattern/$tried_timestamp_pattern) matched.\n";
      }
   }
}
      
exit 0 if $geneos;
      
if ($error) {
   $verbose && print STDERR "ERROR: Total $error ERRORS.\n";
} else {
   $verbose && print STDERR "OK: All Good.\n";
}
exit 0;
