#!/usr/bin/env perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;
#use TPSUP::AUTOSYS qw(get_dependency);
#use TPSUP::UTIL    qw(get_setting_from_env);

use WWW::Mechanize; my $mech = WWW::Mechanize->new();

my $prog = $0; $prog =~ s:.*/::;

sub usage {
   my ($message) = @_;
   print "$message\n" if $message;

   print << "END";
usage:

   $prog JobName
   
description:


examples:

END

   exit 1;
}

my $verbose;

GetOptions(
   'v|verbose'     => \$verbose,
) || usage("cannot parse command line: $!");

#usage("wrong number of args") if @ARGV != 1;

#my ($job) = @ARGV;

my $url = "https://docs.impact.broadridge.com";
$mech->get($url);
#$mech->follow_link( url => 'https://account.login.page.com');
if (! $mech->success()){
   print "Not a successful connection\n"; 
   exit 1;
}

print "content\n";
print $mech->content;
print "\n";

print "dump\n";
$mech->dump_text;
