#!/usr/bin/perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;
use TPSUP::XML qw(parse_inline_xml_log);

my $prog = $0; $prog =~ s:.*/::;

sub usage {
   my ($message) = @_;

   print "$message\n" if $message;

   print STDERR << "END";
usage:

   $prog file.log

   parse a log with inline xml message, eg, those from MQ

   -v verbose

   -m MatchPattern        perl-style, can use once

   -m ExcludePattern      perl-style, can exclude once

   -path string           perl-style, eg, -path {FIXSession}->{suppress-out}
                          can repeat

   -ForceArray a,b,c      force this tags into array.

   -KeyAttr tag=attr      can repeat, eg, -KeyAttr tl=a1 -KeyAttr t2=a2

   -addRoot string        add a root node

examples:

   $prog parse_xml_log_test.log

   # To get a branch or leaf, taking steps to narrow down to your target
   $prog -path 'return \$root' parse_xml_log_test.log
   $prog -path 'return \$root->{FIXSession}' parse_xml_log_test.log
   $prog -path 'return \$root->{FIXSession}->{"suppress-out"}' parse_xml_log_test.log

   # 'return' is optional
   $prog -path '\$root->{FIXSession}->{"suppress-out"}' parse_xml_log_test.log
   
   # To handle array, we have to use loop. The following are the same
   $prog -ForceArray FIXSession -path \\
      'for my \$e (\@{\$root->{FIXSession}}) {
         if (\$e->{"sender-comp-id"} eq "SENDER1") {
            return \$e->{"suppress-out"} }}' parse_xml_log_test.log

   $prog -ForceArray FIXSession -path \\
      "for my \\\$e (\@{\\\$root->{FIXSession}}) {
         if (\\\$e->{'sender-comp-id'} eq 'SENDER1') {
            return \\\$e->{'suppress-out'} }}" parse_xml_log_test.log

   $prog -ForceArray FIXSession -path \\
      "for (\@{\\\$root->{FIXSession}}) {
         if (\\\$_->{'sender-comp-id'} eq 'SENDER1') {
           return \\\$_->{'suppress-out'} }}" parse_xml_log_test.log

   $prog -ForceArray FIXSession -path \\
      "for (\@{\\\$root->{FIXSession}}) {
         (\\\$_->{'sender-comp-id'} eq 'SENDER1') && return \\\$_->{'suppress-out'} }" parse_xml_log_test.log

   # Return an array
   $prog -path 'my \@a=keys(\%{\$root->{FIXSession}}); return \\\@a;' parse_xml_log_test.log

   #This is equivalent to xmllint
   $prog -path 'return \$root' parse_xml_log_test.log

   # this add a root node to an file without root node
   $prog -addRoot xml XML_test_withoutRoot.xml

END

   exit 1;
}

my $tag_string;
my $verbose;
my %attr_by_key;
my $ForceArrayString;
my @paths;
my $addRoot;
my $MatchPattern;
my $ExcludePattern;

GetOptions(
   'v|verbose'    => \$verbose,
   'ForceArray=s' => \$ForceArrayString,
   'KeyAttr=s'    => \%attr_by_key,
   'p|path=s'     => \@paths,
   'addRoot=s'    => \$addRoot,
   'm=s'          => \$MatchPattern,
   'x=s'          => \$ExcludePattern,
) || usage ("cannot parse command line: $!");

usage("wrong number of args") if @ARGV != 1 ;

my $file = shift @ARGV;

my $rows = parse_inline_xml_log($file, {
   KeyAttr        => \%attr_by_key,
   ForceArray     => $ForceArrayString,
   verbose        => $verbose,
   paths          => \@paths,
   AddRootNode    => $addRoot,
   yamlOutput     => 1,
   MatchPattern   => $MatchPattern,
   ExcludePattern => $ExcludePattern,
});


#$Data::Dumper::Terse = 1;

exit 0;
   
