#!/usr/bin/env perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;
use TPSUP::BINARY qw( 
   get_fixed_records
);

# use Carp::Always;

my $prog = $0; $prog =~ s:.*/::;

my $delimiter = ',';

sub usage {
   my ($message) = @_;
   print "$message\n" if $message;

   print << "END";
usage:

   $prog [-t template] record_size fixed_record_file
   
   break a fixed-record file into one record a line

   -t template      break the record using the template (perl pack/unpack template)
                    https://perldoc.perl.org/functions/pack
                    for text file, in particular: 
                       A  A text (ASCII) string, will be space padded.
                    We noramally extract the text and then let perl to convert the
                    data.

                    for binary file, we will have to use other templates

   -d delimiter     output delimiter when "-t template" is also specified. 
                    default to '$delimiter'

examples:
   $prog                        50 parse_fixed_record_test.txt
   $prog -t 'A12 A12 A4 A4 A18' 50 parse_fixed_record_test.txt

END

   exit 1;
}

my $verbose;
my $template;

GetOptions(
   'v|verbose'     => \$verbose,
   't=s'           => \$template,
   'd=s'           => \$delimiter,
) || usage("cannot parse command line: $!");

usage("wrong number of args") if @ARGV != 2;

my ($record_size, $file) = @ARGV;

my $opt = {
   Template => $template,
};

my $records = get_fixed_records($file, $record_size, $opt);

for my $record (@$records) {
   if (!$template) {
      print $record, "\n";
   } else {
      print join($delimiter, @$record), "\n";
   }
}

exit 0;
