#!/bin/bash


prog=`basename $0`
user=`id |cut -d\( -f2|cut -d\) -f1`

min=0
max=9

usage () {
   cat >&2 <<EOF
usage:

   $prog min max

   position a putty's window in the next available position between min and max.

   min starts from 0.

   if no available position, quit.

examples:

   $prog 0 9
   $prog 10 12

EOF
   exit 1
}


verbose=N
while getopts v o;
do
   case "$o" in
      v)  verbose=Y;;
      #x)  max=$OPTARG;;
      *)   usage;;
   esac
done

shift $((OPTIND-1))

if [ $# -ne 2 ]; then
   echo "wrong number of args" >&2
   usage
fi

min=$1
max=$2

if [[ $min =~ [^0-9] ]]; then
   echo "ERROR: min='$min' is not a number" >&2
   usage
fi

if [[ $max =~ [^0-9] ]]; then
   echo "ERROR: max='$max' is not a number" >&2
   usage
fi

if [ $min -ge $max ]; then
   echo "ERROR: min=$min is not less than max=$max"
   usage
fi

# get my pid
tty=`tty`

# tian@linux1:/home/tian$ ps -t /dev/pts/1 
#     PID TTY          TIME CMD
#   37801 pts/1    00:00:00 bash
#   38110 pts/1    00:00:00 ps

[ $verbose = Y ] && ps -t $tty -f 
mypid=`ps -t $tty |grep bash|awk '{print $1}'`
   
declare -A seen # bash seen implementation, using associate array

# get ssh client IP
SSHID=`echo $SSH_CLIENT |cut -d\  -f1`

# for loop range, works for numbers
#    for i in {0..10} 
# but not work for variables
#    for i in {$min..$max}
# for variables, use C-style instead
for (( i = $min; i <= $max; i ++ ))
do
   [ $verbose = Y ] && echo ""
   [ $verbose = Y ] && echo "checking spot $i"

   padded=`printf '%03d' $i`
   posfile=/tmp/puttypos.$user.$SSHID.$padded 

   if [ -e $posfile ]; then
      pid=`cat $posfile`

      if ! [ "X$pid" = "X" ]; then
         if ps -p $pid >/dev/null; then
            [ $verbose = Y ] && echo "putty $padded is running, pid=$pid."             
            if [ ${seen[$pid]+_} ]; then
               if [ $verbose = Y ]; then
                  [ $verbose = Y ] && echo "already seen pid=$pid in ${seen[$pid]}. use $i"
               fi
            elif [ "$mypid" = "$pid" ]; then
               # this file has mypid
               [ $verbose = Y ] && echo "seen mypid=$mypid in $posfile. keep spot $i"
            else
               [ $verbose = Y ] && echo "we will check next spot"
               seen[$pid]=$posfile
               continue
            fi
         else 
            if [ $verbose = Y ]; then
               [ $verbose = Y ] &&  "pid=$pid in $posfile is not running.  use sport $i"
            fi
         fi
      else
         [ $verbose = Y ] && "$posfile is empty. we can use sport $i"
      fi
   fi

   # found a spot
   offset=`expr 30 \* $i`

   # https://superuser.com/questions/1162451
   printf '\033[3;'"$offset;$offset"'t'

   echo $mypid > $posfile

   found=$i
   break
done
   
if [ "X$found" = "X" ]; then
   echo "$prog: no available spot found"
else
   [ $verbose = Y ] && echo "spot found at $found"
fi
