#!/usr/bin/env perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;
#use TPSUP::AUTOSYS qw(get_dependency);
#use TPSUP::UTIL    qw(get_setting_from_env);
use Selenium::Chrome;

my $prog = $0; $prog =~ s:.*/::;

sub usage {
   my ($message) = @_;
   print "$message\n" if $message;

   print << "END";
usage:

   $prog JobName
   
description:


examples:

END

   exit 1;
}

my $verbose;

GetOptions(
   'v|verbose'     => \$verbose,
) || usage("cannot parse command line: $!");

#usage("wrong number of args") if @ARGV != 1;

#my ($job) = @ARGV;

# start local chrome c1,
# $ /usr/bin/chromium-browser --no-sandbox --disable-dev-shm-usage --window-size=960,540 --user-data-dir=/tmp/selenium_chrome_browser_dir --remote-debugging-port=9222
# from another chrome c2, enter url http://localhost:9222, this will show 'inspectable page'.
# click the first link in c2. this will bring up DevTools
# now back to c1, go to any page, eg, google.com, you will see c1 and c2 are linked

my $driver = Selenium::Chrome->new (
   # the following seting are in Selenium::Chrome
   startup_timeout => 20,
   custom_args => '--verbose --log-path=/tmp/selenium_chromedriver.log',  # chromedriver cmd line

   # the following setting are in Selenium/CanStartBinary.pm
   logfile => '/tmp/selenium_chromedriver_short.log',  # another chromedriver log, shorter version

   # Selenium::Chrome is an extension of Selenium::Remote::Driver
   # the following setting are in Selenium::Remote::Driver
   debug_on   => 1, 
   extra_capabilities => {
      'goog:chromeOptions' => {
         # these are chrome browser (including chromium-browser) command line args
         args => [
            '--no-sandbox',              # to run without root
            '--disable-dev-shm-usage',   # to run without root
            '--window-size=960,540',

            # use a separate browser dir to avoid corruption
            '--user-data-dir=/tmp/selenium_chrome_browser_dir',  

            #'--headless',
            #'--proxy-pac-url=http://pac.abc.net',
         ],
      },
   },
);

sleep 2;

my $url = "https://www.google.com";
$driver->get($url);

sleep 2;

# <input class="gLFyf gsfi" maxlength="2048" name="q" type="text" jsaction="paste:puy29d" aria-autocomplete="both" aria-haspopup="false" autocapitalize="off" autocomplete="off" autocorrect="off" autofocus="" role="combobox" spellcheck="false" title="Search" value="" aria-label="Search" data-ved="0ahUKEwjt7s-M5pXnAhVDuVkKHUlHBscQ39UDCAY">

my $search_box = $driver->find_element('q', 'name');
$driver->send_keys_to_active_element("perl Selenium", "\n");
sleep 2;

# https://gist.github.com/dnmfarrell/5dde6d3957bf9ae037e170cdb44f75a5 
my @links = $driver->find_elements('a', 'tag_name');
for my $l (@links) {
   my $link_url = eval { $l->get_attribute('href') };
   next unless $link_url;
   my $link_uri = URI->new($link_url);
   next unless $link_uri->can('host'); # not all URIs have a domain
   my $link_host = $link_uri->host;
   print $link_host, "\n";
}

sleep 5;

$driver->shutdown_binary;

__END__
use Selenium::Remote::Driver;
#use Encode 'encode';

my $driver = Selenium::Remote::Driver->new(
  browser_name => 'chrome',
  #browser_name => 'chromium-browser',
  extra_capabilities => { chromeOptions => {args => [
    'window-size=960,540',
    'headless',
  ]}},
);
