#!/usr/bin/perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;
use TPSUP::UTIL qw(get_tmp_file);
use TPSUP::SQL qw(run_sql);

my $prog = $0; $prog =~ s:.*/::;

my $output = '-'; #STDOUT

sub usage {
   my ($message) = @_;

   print "$message\n" if $message;

   print STDERR << "END";
usage:
   $prog db_nickname sql
   $prog db_nickname file file.sql
   $prog db_nickname batch file.txt

   $prog db_nickname (sql|file file.sql)+

   $prog -s 'dbiString,login,password' (sql|file file.sql)+
   
   -v              verbose

   -noheader       no header

   -output output.csv
                   default to STDOUT

   -trim           trim ending of sql: remove 'go', 'quit', and ';' at the end of sql

   -conn conn.csv  connection file, default to \$HOME/.tpsup/conn.csv

   -LowMemory      use as little memory as possible

   -OutputDelimiter string
                   output delimiter, default to

   -OutputHeader "c1,c2 ,..."
                   output header, default to database column names

   -maxout int     print only this number of rows

   -Dbistring      use "dbiString,login,password" instead of db nickname

   -plain          use plain password with '-DbiString'

   -op other options: for example,
                   -op NonQuery=1 # use this if the sql is not a query

   'batch' is for file containing multiple sql, for example, in this format,
      <SQL>select * from tablel</SQL>
      <SQL>select * from table2</SQL>

examples:

   - oracle
   sql -maxout 10 ORA_USER\@db1 "select * from all_synonyms"
   sql -maxout 10 ORA_USER\@db1 file sql_test.sql
   sql -maxout 10 ORA_USER\@db1 batch sql_test_batch.txt

   - sybase
   $prog imagine "select \@\@version"
   $prog imagine file /apps/get_positions.sql

   - test passwords
   $prog -maxout 10 -DbiString \\
   'dbi:Oracle:host=h.db.com;service_name=h.db.com;port=l725,ORA_USER,\%encoded\%' \\
   "select * from all_synonyms"
   $prog -maxout 10 -DbiString -plain \\
   'dbi:Oracle:host=h.db.com;service_name=h.db.com;port=l725,ORA_USER,plain' \\
   "select * from all_synonyms"

END

   exit 1;
}

my $tag_string;
my $verbose;
my $noheader;
my $maxout;
my $trim=0;
my $connfile;
my $LowMemory;
my $OutputDelimiter;
my $OutputHeader;
my $useDbiString;
my $usePlainPassword;
my @other_options;

GetOptions(
   'v|verbose'      => \$verbose,
   'trim'           => \$trim,
   'noheader'       => \$noheader,
   'maxout=s'       => \$maxout,
   'o|output=s'     => \$output,
   'conn=s'         => \$connfile.
   'LowMemory'      => \$LowMemory,
   'OutputDelimiter=s' => \$OutputDelimiter,
   'OutputHeader=s' => \$OutputHeader,
   'DbiString'      => \$useDbiString,
   'plain'          => \$usePlainPassword,
   'op|option=s'    => \@other_options,
) || usage ("cannot parse command line: $!");

usage("wrong number of args") if @ARGV < 2;

my $opt = {
   output=> $output,
   noheader=>$noheader,
   maxout=> $maxout,
   TrimSql=>$trim,
   connfile=>$connfile,
   LowMemory=>$LowMemory,
   OutputDelimiter=>$OutputDelimiter,
   OutputHeader=>$OutputHeader,
};

my $arg1 = shift @ARGV;

if ($useDbiString) {
   my @triple = split /,/, $arg1;
   $opt->{dbiArray} = \@triple;
   $opt->{dbiPasswordLocked} = $usePlainPassword ? 0 : 1;
} else {
   $opt->{nickname} = $arg1;
}

for my $op (@other_options) {
   if ($op =~ /^(.+?)=(.+)/) {
      my ($k, $v) = ($1, $2);

      if ($k =~ /(placeholder1|placeholder2)$/) {
         @{$opt->{$k}} = split /,/, $v;
      } else {
         $opt->{$k} = $v;
      }
   } else {
      $opt->{$op} = 1;
   }
}

my $error = 0;

while (@ARGV) {
   my $sql;

   my $a = shift @ARGV;

   if ($a eq 'file' || $a eq 'batch') {
      die "wrong number of args" if !@ARGV;
      my $file = shift @ARGV;

      if ($file ne '-') {
         die "cannot find $file" if ! -f $file;
         die "cannot read $file" if ! -r $file;
      }

      if ($a eq 'file') {
         $sql = `cat $file`;
         chomp $sql;

         $verbose && print "sql ='$sql'\n";
         my $ret = run_sql($sql, $opt);
         $error ++ if !$ret;
      } else {
         # batch
         #require TPSUP::XML qw(query_xml);
         require TPSUP::XML;

         my $sqls = TPSUP::XML::query_xml($file, { ForceArray => 'SQL',
                                                   AddRootNode => 'xml',
                                                   paths => ['$root->{SQL}'],
                                                   verbose => $verbose});

         print "sqls = ", Dumper($sqls) if $verbose;

         if ($sqls->[0]) {
            for my $sql (@{$sqls->[0]}) {
               $verbose && print "sql='$sql'\n";
               my $ret = run_sql($sql, $opt);
               $error ++ if !$ret;
            }
         }
      }
   } else {
      $sql = $a;

      $verbose && print "sql='$sql'\n";
      my $ret = run_sql($sql, $opt);
      $error ++ if !$ret;
   }
}

exit $error;
