#!/bin/bash

timeout=5

usage () {
   cat >&2 <<EOF
usage:

   $0 db_nickname
   $0 all

   -t sec    timeout. default to $timeout (seconds)
   -v        verbose mode


example:

   $0 a@b

EOF

   exit 1
}

verbose=N

while getopts t:v o;
do
   case "$o" in
      v) verbose=Y;;
      t) timeout=$OPTARG;;
      *) echo "unknow switch '$o'"; usage;;
   esac
done

shift $((OPTIND-1))

if [ $# -eq 0 ]; then
   echo "wrong number of args" >&2
   usage
fi

error=0

if [ $1 = all ]; then
   pinglist=`sed 1d ~/.tpsup/conn.csv|cut -d, -f1|sed -e 's:^[ ][ ]*::'|grep ^[a-zA-Z0-9@]`
else
   pinglist="$@"
fi

for nickname in $pinglist
do 
   if [ $verbose = Y ]; then 
      echo >&2 ""
      echo >&2 "INFO: pinging $nickname"
   fi

   if ! timeout 5 sql -noheader $nickname "select '$nickname: success'"; then
      echo "$nickname: failure"
      ((error++))
   fi
done

exit $error

