#!/bin/bash

usage () {
   cat >&2 <<EOF
usage:

   $0 db_nickname

example:

   $0 a@b

EOF

   exit 1
}

if [ $# -ne 1 ]; then
   echo "wrong number of args" >&2
   usage
fi

db_nickname=$1

sql -noheader $db_nickname "select 'success'" || echo "failure"
