#!/bin/bash

depot_dir=~/depot
site_dir=~/github

usage () {
   cat <<EOF
usage:

   $0 check
   $0 diff          # check and then diff
   $0 sync

   -d depot_dir     where you should see <depot_dir>/tpsup. 
                    default to $depot_dir. 
                    this is the dir to do clone tpsup from github.com

   -s site_dir      where you should see  <site_dir>/tpsup.
                    dfault to $site_dir

EOF

   exit 1
}

while getopts s:d: o;
do
   case "$o" in
      d) depot_dir="$OPTARG";;
      s)  site_dir="$OPTARG";;
      *) echo "unknow switch '$o'"; usage;;
   esac
done

shift $((OPTIND-1))

if [ $# -ne 1 ]; then
   echo "wrong number of args"
   usage
fi

action=$1

cd $depot_dir/tpsup || exit 1
git pull 
echo ""

if [ $action = check -o $action = diff ]; then
   flag="-n"
elif [ $action = sync ]; then
   flag=""
else
   echo "unknown action='$action'"
   usage
fi

# --existing           only to update existing files
# --exclude='*[.]site' to skips site-specific files
# --exclude='[.]git*'  to skip .git/ and .gitignore
# -i                   to print item to be changed, ie, --itemize-changes
# --out-format="%n%L"  to print out the relative path, only for -i, same as used in -v
files=`(set -x;rsync $flag -a -i --existing --exclude='[.]git*' --exclude='.nfs*' --exclude='.sw*' --exclude='[.]idea' --exclude=__pychche__ --exclude='*[.]site' --out-format="%n%L" $depot_dir/tpsup $site_dir/)`

echo ""
echo "$files"

if [ $action = diff ]; then
   # skip dir
   for f in `echo "$files"|egrep -v '/$'`
   do
      echo ""
      (set -x; diff $depot_dir/$f $site_dir/$f)
   done
fi


