#!/usr/bin/perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;
use TPSUP::CSV   qw(parse_csv_file);
use TPSUP::PRINT qw(render_arrays);

my $prog = $0;
$prog =~ s:.*/::;

my $method = 'tpdist';

my $home = `/bin/bash -c "echo ~"`;
chomp $home;

sub usage {
   my ($message) = @_;

   print "$message\n" if $message;

   print STDERR <<"END";
Usage:

   $prog do    proj
   $prog list  proj
   $prog check proj
   $prog diff  proj
   $prog info

   'proj' is defined in tpbackup.csv.

   'action' can be
   do    - do the backup
   list  - list the backup folders
   check - list the changes since the backup
   diff  - show the diff between this backup and previous backup.
   info  - show config in the tpbackup.csv

   -v              verbose mode

   -m <method>     rsync, tpdist, default to $method.

   -d yyyymmdd     when 'check', check against this day. default to the last day of backup.

   -f tpbackup.csv default to ~/.tpsup/tpbackup.csv. Example of format:
                     proj,source,backup_base,retention,comment
                     tpsup,\$home/sitebase/github/\$proj,\$home/backup/\$proj,5,these are scripts
                     notes,\$home/sitebase/github/\$proj,\$home/backup/\$proj,5,these are notes
     retention is number of backups

   -b brief mode when 'check'. only prints the file names

Examples:

   $prog check tpsup
   $prog do    tpsup
   $prog list  tpsup
   $prog diff  tpsup 
   $prog info

   $prog -m tpdist do home
   
END

   exit 1;
}

my $verbose;
my $yyyymmdd;
my $CfgFile = "$home/.tpsup/tpbackup.csv";
my $brief;

GetOptions(
   'verbose' => \$verbose,
   'brief'   => \$brief,
   'd=s'     => \$yyyymmdd,
   'f=s'     => \$CfgFile,
   'm=s'     => \$method,
) || usage("cannot parse command line: $!");

usage("wrong number of args") if !@ARGV;

my ( $action, $proj ) = @ARGV;

usage("unknown action='$action'") if $action !~ /(do|list|check|diff|info)$/;

my $cfg_by_key = parse_csv_file( $CfgFile, { keyColumn => 'proj,source' } );

die "cannot parse $CfgFile" if !$cfg_by_key;

$verbose && print "cfg_by_key = ", Dumper($cfg_by_key);

if ( $action eq 'info' ) {
   usage("wrong number of args") if @ARGV != 1;

   print_cfg($cfg_by_key);
   exit 0;
}

# now action is either of do|list|check
usage("wrong number of args") if @ARGV != 2;

my $matched = 0;
for my $key ( sort keys(%$cfg_by_key) ) {
   if ( $key !~ /^$proj,/ ) {
      next;
   }
   $matched = 1;

   my $today = `date +%Y%m%d`;
   chomp $today;

   my ( $source, $backup_base, $retention ) = @{ $cfg_by_key->{$key}->[0] }{qw(source backup_base retention)};

   $source      =~ s:\$home:$home:g;
   $backup_base =~ s:\$home:$home:g;
   $source      =~ s:\$proj:$proj:g;
   $backup_base =~ s:\$proj:$proj:g;

   # [.]*[.]sw[pon]       tmp files of vi. vi only create up to 3 tmp files:  .*.swp, .*.swo, .*.swn
   my $rsync_excludes =
     "--exclude='[.]git' --exclude='.nfs*' --exclude='[.]*[.]sw[ponmlkj]' --exclude='[.]idea' --exclude=__pycache__";

   my $diff_excludes = "--exclude='[.](svn|sw[ponmlkj]|git|nfs|idea)|__pycache__|^Common subdirectories'";

   if ( $action eq 'do' ) {
      {
         my @dirs  = `/bin/ls -d "$backup_base"/[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]`;
         my $count = scalar(@dirs);

         if ( $count > $retention ) {
            print "too many backups ($count) > retention ($retention) under $backup_base, cleaning up\n";
            chomp @dirs;
            my $remove_count = $count - $retention;

            for ( my $i = 0 ; $i < $remove_count ; $i++ ) {
               my $cmd = "/bin/rm -fr \"$dirs[$i]\"";
               print "$cmd\n";
               system($cmd);
            }

            # to test:
            #    cd /home/tian/backup/config;i=0;while [ $i -lt 30 ];do mkdir 0$i; ((i++));done
         }
      }

      if ( !-d $backup_base ) {
         my $cmd = "mkdir -p '$backup_base'";
         print "$cmd\n";
         system($cmd) && die "$cmd failed";
      }

      {
         my $cmd;
         if ( $method eq 'rsync' ) {
            $cmd = "rsync -av --delete $rsync_excludes '$source' '$backup_base'/$today/";
         } elsif ( $method eq 'tpdist' ) {
            $cmd = "tpdist local -q '$source' '$backup_base'/$today/";
         } else {
            print "unsupported method='$method'\n";
            exit 1;
         }

         print "$cmd\n";
         system("$cmd");
      }
   } elsif ( $action eq 'check' ) {
      if ($yyyymmdd) {
         my $backupdir = "$backup_base/$yyyymmdd";
         usage("$backupdir doesn't exist, we don't have a backup for $yyyymmdd") if !-d $backupdir;
      } else {
         $yyyymmdd = `/bin/ls "$backup_base"|tail -1`;
         die "we don't have any backup" if !$yyyymmdd;
         chomp $yyyymmdd;
      }

      # source_basename, source_parentdir
      my ($source_basename)  = $source =~ /\/?([^\/]+)$/;
      my ($source_parentdir) = $source =~ /^(.*)\/[^\/]+$/;

      my $cmd;
      if ($brief) {
         if ( $method eq 'rsync' ) {
            $cmd = "rsync -avn $rsync_excludes '$backup_base'/$yyyymmdd/$source_basename '$source'";
         } elsif ( $method eq 'tpdist' ) {
            $cmd = "tpdist local -diff -q '$backup_base'/$yyyymmdd/$source_basename '$source_parentdir'";
         } else {
            print "unsupported method='$method'\n";
            exit 1;
         }
      } else {
         $cmd = "diff $diff_excludes -r '$backup_base'/$yyyymmdd/$source_basename '$source'";
      }

      print "$cmd\n";
      system("$cmd");
   } elsif ( $action eq 'diff' ) {
      my $current_yyyymmdd = `/bin/ls "$backup_base"|tail -1`;
      die "we don't have any backup" if !$current_yyyymmdd;
      chomp $current_yyyymmdd;
      my $previous_yyyymmdd = `/bin/ls "$backup_base"|tail -2|head -1`;
      die "we don't have enough backup to compare. need at least 2 backups" if !$previous_yyyymmdd;
      chomp $previous_yyyymmdd;
      my $cmd = "diff -r $diff_excludes '$backup_base'/$previous_yyyymmdd '$backup_base'/$current_yyyymmdd";
      print "$cmd\n";
      system("$cmd");
   } elsif ( $action eq 'list' ) {
      my $cmd = "/bin/ls '$backup_base'";
      print "$cmd\n";
      system("$cmd");
   } elsif ( $action eq 'info' ) {
      print_cfg($cfg_by_key);
   }
}

if ( !$matched ) {
   print "ERROR: proj='$proj' is not in $CfgFile\n";
   usage();
}

exit 0;
##############################################################
# subs
##############################################################
sub print_cfg {
   my ($cfg_by_proj) = @_;
   my @rows;
   for my $proj ( sort keys(%$cfg_by_proj) ) {
      push @rows, @{ $cfg_by_proj->{"$proj"} };
   }
   render_arrays( \@rows, { headers => [qw(proj source backup_base retention comment)], verbose => $verbose } );
}
