#!/usr/bin/perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;

my $prog = $0; $prog =~ s:.*/::;

sub usage {
   my ($message) = @_;

   print "$message\n" if $message;

   print STDERR << "END";
usage:

   $prog old_pattern new_string path1 path2 ...

   $prog -s sed_clause path1 path2 ...

   massively change file names using pattern

   'sed_clause'    eg, s/old_pattern/new_pattern/g
   'path1 path2 ...'
                   can be both file and directory

   -m pattern      only files with name matching this pattern

   -x pattern      exclue files with name to matching this pattern

   -i              case-insensitive when handling '-x' and '-m'.
                   default to case-sensitive.

   -f force        the change without asking for confirmation

   -v              verbose mode

   -n              dry run. just list the changes without making the changes

   -s              the next arg is a perl substitution, eg s/old_pattern/new_pattern/g

   -y              when prompt, simple return means 'Y'. default to 'N';

example:

   - change fix.4.4.py ... to fix_4_4.py
   $prog -x fix.py  [.]   _ fix.*py
   $prog            _py .py fix*_py

   - the following commands are the same
   $prog uat prod          uat.txt uatdir
   $prog -s "s/uat/prod/g" uat.txt uatdir

   - when patten contains '/', use a. different separator, eg,
   $prog -s "s:/apps/data/:/apps/archive:/g" apps.txt appsdir

   - only change *.properties files under current dir recursively
   $prog -m .properties old_string new_string .

END

   exit 1;
}

my $verbose;

my @paths;
my $perl_substitution;
my $force;
my $default_yes;
my $maxdepth = 100;
my $insensitive;
my $MatchPattern;
my $ExcludePattern;
my $dryrun;

GetOptions(
   'v|verbose'  =>  \$verbose,
   'f'          =>  \$force,
   'n'          =>  \$dryrun,
   'y'          =>  \$default_yes,
   's=s'        =>  \$perl_substitution,
   'i'          =>  \$insensitive,
   'm=s'        =>  \$MatchPattern,
   'x=s'        =>  \$ExcludePattern,
   'maxdepth=s' =>  \$maxdepth,
) || usage ("cannot parse command line: $!");

my $substitution;

if ($perl_substitution) {
   $substitution = $perl_substitution;
   usage("wrong number of args") if !@ARGV;
} else {
   usage("wrong number of args") if @ARGV < 3;
   my $old = shift @ARGV;
   my $new = shift @ARGV;

   $substitution = "s!$old!$new!g";
}

my $warn = $verbose ? "use" : "no";
my $compiled = eval "$warn warnings; no strict; sub { my (\$path)=\@_; \$path =~ $substitution; return \$path }";

die "failed to compile '$substitution'" if $@;

my $opt = {
   RecursiveMax => $maxdepth,
   compiled     => $compiled,
};

$opt->{DefaultAnswer} = $default_yes ? "Y" : "N";

my $insensitive_flag = $insensitive ? "i" : "";

if ($MatchPattern) {
   if ($insensitive) {
      $opt->{$MatchPattern} = qr/$MatchPattern/i;
   } else {
      $opt->{$MatchPattern} = qr/$MatchPattern/;
   }
}

if ($ExcludePattern) {
   if ($insensitive) {
      $opt->{$ExcludePattern} = qr/$ExcludePattern/i;
   } else {
      $opt->{$ExcludePattern} = qr/$ExcludePattern/;
   }
}

my $error;

for my $path (@ARGV) {
   if (! -e $path) {
      print "$path not found\n";
      $error ++;
      next;
   }

   my $res = move_file($path, $opt);
   $error += $res->{error};

   my $ref = recursive_path($res->{new_file}, 1, $opt);
   $error += $ref->{error};
}

if ($error) {
   print "Total $error errors.\n";
}

exit $error;

################################################################

sub recursive_path {
   my ($path, $level, $opt) = @_;

   my $ret;
   $ret->{error} = 0;

   if (! -e $path) {
      return $ret;
   }

   if (-d $path) {
      # this is a dir

      $level ++;

      my $max_level = defined $opt->{RecursiveMax} ? $opt->{RecursiveMax} : 100;

      if ($level > $max_level) {
         if (defined $opt->{RecursiveMax}) {
            # this is user-defined limit - it is intentional, so return without complain
            return $ret;

         } else {
            # this is safety catch
            croak "recursive level($level) > max_level($max_level), path=$path";
         }
      }

      my $dfh;
      opendir($dfh, $path);

      if (!$dfh) {
         print STDERR "cannot open dir $path\n";
         $ret->{error} ++;
      } else {
         my @files_in_dir = readdir($dfh);

         for my $f (sort @files_in_dir) {
            next if $f eq '.' || $f eq '..';

            my $res = move_file($f, $opt);

            $ret->{error} += $res->{error};
            
            my $ref = recursive_path("$path/$res->{new_file}", $level, $opt);

            $ret->{error} += $ref->{error};

            if ($ref->{exit}) {
               $ret->{exit} ++;
               last;
            }
         }
      }
   } 

   return $ret;
}

sub move_file {
   my ($old_file, $opt) = @_;

   my $new_file = $opt->{compiled}->($old_file);

   my $res = {
      new_file => $new_file,
      error    => 0,
   };

   if ($new_file eq $old_file) {
      return $res;
   }

   my $cmd = "/bin/mv -f $old_file $new_file";

   if (-e $new_file) {
      print "cmd=$cmd cancelled because $new_file already exsits\n";   
      $res->{new_file} = $old_file;
      $res->{error}    = 1;
      return $res;
   }

   print "cmd=$cmd\n";
   print "Do you want to make this change? Y/N [$opt->{DefaultAnswer}]\n";

   my $will_do = 0;

   if ($opt->{force}) {
      $will_do ++;
   } else {
      my $answer = readline(*STDIN);

      if ($answer =~ /^\s*[yY]/) {
         $will_do ++;
      } elsif ($answer =~ /^\s*$/ && $opt->{DefaultAnswer} eq 'Y') {
         $will_do ++;
      }
   }

   if ($will_do) {
      if ($dryrun) {
         print "dryrun\n";
         $res->{new_file} = $old_file;
         $res->{error}    = 0;
      } else {
         my $rc = system($cmd);
         print "executed\n";

         if ($rc) {
            $res->{new_file} = $old_file;
            $res->{error}    = 1;
         } 
      }
   } else {
      print "your answer is not yes. skipped.\n";
      $res->{new_file} = $old_file;
      $res->{error}    = 0;
   }

   return $res;
}
