#!/usr/bin/perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;
use TPSUP::CSV qw(/./);
use TPSUP::PRINT qw(render_arrays);

my $prog = $0;
$prog =~ s:.*/::;

my $method = 'tpdist';

my $home = `/bin/bash -c "echo ~"`;
chomp $home;

sub usage {
   my ($message) = @_;

   print "$message\n" if $message;

   print STDERR <<"END";
Usage:

   $prog do    file1, file2, ...
   $prog list  file1, file2, ...
   $prog check file1, file2, ...
   $prog info

   Restore files that were backed up by tpbackup. (see tpbackup. csv)

   'action' can be
       do    - do the restore
       list  - list the backup folders
       check - list the changes since the backup
       info  - print the config

   -v verbose mode

   -d yyyymmdd   use this day's backup, default to the last day of backup.

   -f tpbackup.csv
                 default to ~/.tpsup/tpbackup.csv. Example of format:
                         proj,source,backup_base,retention,comment
                         tpsup,\$home/\$proj,\$home/backup/\$proj,5,scripts backups
                         notes,\$home/\$proj,\$home/backup/\$proj,5,notes   backups

   -m <method>     rsync, tpdist, default to $method.

   -p            arg is a proj name, not a file.

Examples:

   cd /a/b/c
   $prog check d/e.txt
   $prog do    d/e.txt
   $prog list  d/e.txt
   $prog info

END

   exit 1;
}

my $verbose;
my $yyyymmdd;
my $CfgFile = "$home/.tpsup/tpbackup.csv";
my $is_proj = 0;

GetOptions(
   'verbose' => \$verbose,
   'd=s'     => \$yyyymmdd,
   'f=s'     => \$CfgFile,
   'm=s'     => \$method,
   'p'       => \$is_proj,
) || usage("cannot parse command line: $!");

usage("wrong number of args") if !@ARGV;

my $action = shift @ARGV;

usage("unknown action='$action'") if $action !~ /^(do|list|check|info)$/;

my $cfg_by_key = parse_csv_file(
   $CfgFile,
   {
      keyColumn      => 'proj,source',
      excludePattern => '^\s*$|^\s*#',
   }
);

if ( $action eq 'info' ) {
   usage("wrong number of args") if @ARGV;

   print_cfg($cfg_by_key);
   exit 0;
}

usage("wrong number of args") if !@ARGV;

my $today = `date +%Y%m%d`;
chomp $today;

my $cwd = `/bin/bash -c pwd`;
chomp $cwd;

my $rsync_excludes =
  "--exclude='[.]git' --exclude='.nfs*' --exclude='[.]*[.]sw[ponmlkj]' --exclude='[.]idea' --exclude=__pycache__";

my $diff_excludes = "--exclude='[.](svn|sw[ponmlkj]|git|nfs|idea)|__pycache__|^Common subdirectories'";

my $error = 0;
my @restore_cmds;

for my $f (@ARGV) {
   $f =~ s:/+$::;    # remove ending /

   if ($f eq '.') {
      $f = $cwd;
   }

   my $user_source;

   if ( $f !~ m:^/: ) {
      $user_source = "$cwd/$f";
   } else {
      $user_source = "$f";
   }

   $verbose && print "user_source=$user_source\n";

   my $proj;
   my $backup_source;
   my $backup_base;
   my $relative;

   my $found;

   my $matched_list = [];

 PROJ:
   for my $key ( sort keys(%$cfg_by_key) ) {
      ( $proj, $backup_source ) = split( /,/, $key );

      if ($is_proj) {
         # match by proj
         if ( $f eq $proj ) {
            $found++;

            for my $row ( @{ $cfg_by_key->{$key} } ) {
               ( $backup_source, $backup_base ) = @{$row}{qw(source backup_base)};
               $backup_source =~ s:\$home:$home:g;
               $backup_base   =~ s:\$home:$home:g;

               $backup_source =~ s:\$proj:$proj:g;
               $backup_base   =~ s:\$proj:$proj:g;

               $relative = '';

               push @$matched_list, { proj => $proj, backup_source => $backup_source, backup_base => $backup_base, relative => $relative };
            }
         }
      } else {
         # match by file or dir

         for my $row ( @{ $cfg_by_key->{$key} } ) {
            ( $backup_source, $backup_base ) = @{$row}{qw(source backup_base)};
            $backup_source =~ s:\$home:$home:g;
            $backup_base   =~ s:\$home:$home:g;

            $backup_source =~ s:\$proj:$proj:g;
            $backup_base   =~ s:\$proj:$proj:g;

            if ( $user_source =~ m:${backup_source}/(.*): ) {
               $relative = $1;
               $found++;
            } elsif ( $user_source eq $backup_source ) {
               $relative = '';
               $found++;
            }

            if ($found) {
               push @$matched_list, { proj => $proj, backup_source => $backup_source, backup_base => $backup_base, relative => $relative };
               
               # if match by file or dir, we just get the first match, ignore the rest.
               last PROJ;
            }
         }
      }
   }

   if ( !$found ) {
      print "ERROR: $f ($user_source) is not backed up by any proj in $CfgFile\n";
      print_cfg($cfg_by_key);
      $error++;
      next;
   }

   if ($verbose) {
      print "matched_list=\n";
      print Dumper($matched_list);
      print "\n";
   }

   for my $row (@$matched_list) {
      $proj          = $row->{proj};
      $backup_source = $row->{backup_source};
      $backup_base   = $row->{backup_base};
      $relative      = $row->{relative};

      $verbose && print "relative=$relative\n";
      $verbose && print "proj=$proj\n";
      $verbose && print "backup_source=$backup_source\n";
      $verbose && print "backup_base=$backup_base\n";

      my $source_basename = $backup_source;
      $source_basename =~ s:.*/::;
      $verbose && print "source_basename=$source_basename\n";

      if ( $action eq 'list' ) {
         my $cmd;
         if ( !$relative ) {
            $cmd = "ls -ld \"$backup_base\"/*/\"$source_basename\"";
         } else {
            $cmd = "ls -ld \"$backup_base\"/*/\"$source_basename\"/\"$relative\"";
         }
         print "$cmd\n";
         system($cmd);
         $error ++ if $? != 0;
         next;
      }

      my $backup_dir;

      if ($yyyymmdd) {
         $backup_dir = "${backup_base}/$yyyymmdd/$source_basename";
         usage("$backup_dir doesn't exist, we don't have a backup for $yyyymmdd") if !-d $backup_dir;
      } else {
         my $cmd = "ls -1 \"$backup_base\"|tail -1";
         print "cmd=$cmd\n";
         $yyyymmdd = `$cmd`;
         die "we don't have any backup" if !$yyyymmdd;
         chomp $yyyymmdd;
         $backup_dir = "${backup_base}/$yyyymmdd/$source_basename";
      }

      my $backup_full = $relative ? "$backup_dir/$relative" : $backup_dir;

      $verbose && print "backup_dir=$backup_dir\n";
      $verbose && print "backup_full=$backup_full\n";

      my $need_restore;

      if ( !-e $backup_full ) {
         print "ERROR: ${f}'s backup $backup_full doesn't exist. Please run 'check' to find anothere day's backup\n";
         $error++;
         next;
      } elsif ( !-e $user_source ) {
         print "We lost the source but we have backup.\n";
         $need_restore++;
      } else {
         my $cmd = "diff $diff_excludes -r \"$backup_full\" \"$user_source\"";

         print "$cmd\n";

         my @lines = "$cmd 2>&1";

         print @lines;

         if (@lines) {
            $need_restore++;
         }
      }

      if ($need_restore) {
         if ( -f $backup_full ) {
            push @restore_cmds, "/bin/cp -p \"$backup_full\" \"$user_source\"";
         } else {
            # find the parent dir
            my $user_source_parent = $user_source;
            $user_source_parent =~ s:/+[^/]+$::;

            if ( $method eq 'tpdist' ) {
               push @restore_cmds, "tpdist local -q '$backup_full' '$user_source_parent'";
            } elsif ( $method eq 'rsync' ) {
               push @restore_cmds, "rsync -av --delete $rsync_excludes '$backup_full' '$user_source_parent'";
            } else {
               print "unsupported method='$method'\n";
               exit 1;
            }
         }
      }
   }

   if ( $action eq 'check' || $action eq 'do' ) {
      print "---------begin restore commands--------------------\n";
      print join( "\n", @restore_cmds );
      print "\n";
      print "---------end restore commands----------------------\n";
      print "\n";
   }

   if ( $action eq 'check' ) {
      print "nothing done\n";
   } elsif ( $action eq 'do' ) {
      print "--------- executing restore commands ---------------\n";
      for my $cmd (@restore_cmds) {
         print "cmd= $cmd\n";
         system($cmd);

         if ($?) {
            print "ERROR: cmd=$cmd failed\n";
            $error++;
         }
      }
   }
}

if ($error) {
   print "ERROR: total $error ERRORS\n";
   exit 1;
} else {
   print "OK: All Good.\n";
   exit 0;
}

##############################################################
# subs
##############################################################
sub print_cfg {
   my ($cfg_by_proj) = @_;

   my @rows;

   for my $key ( sort keys(%$cfg_by_key) ) {
      push @rows, @{ $cfg_by_key->{$key} };
   }

   render_arrays( \@rows, { headers => [qw(proj source backup_base retention comment)], verbose => $verbose } );
}
