#!/bin/bash

prog=`basename $0`

usage() {
   cat <<EOF
usage:

   $prog path

   enhanced 'touch' command. It will create the directories if needed.

   if 'path' ends with '/', it is a dir.
   otherwise, we assume it is a file.

   -v verbose

examples:
   /bin/rm -fr /tmp/junkdir
   
   $prog /tmp/junkdir/a.txt /tmp/junkdir/b/c.txt /tmp/junkdir/b/d/

   find /tmp/junkdir -ls

EOF

   exit 1
}

verbose=N

while getopts v o; do
   case "$o" in
   # d) depot_dir="$OPTARG" ;;
   # s) site_dir="$OPTARG" ;;
   v) verbose=Y ;;
   *)
      echo "unknow switch '$o'"
      usage
      ;;
   esac
done

shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
   echo "wrong number of args"
   usage
fi

for path in "$@"; 
do
   # if path ends with /, it is a dir
   if [[ $path == */ ]]; then
      dir=$path
      [[ -d $dir ]] || mkdir -p $dir
   else
      dir=$(dirname $path)
      [[ -d $dir ]] || mkdir -p $dir
      touch $path
   fi
done
