#!/usr/bin/perl

use warnings;
use strict;
use Data::Dumper;
use Getopt::Long;
use Carp;
use TPSUP::XML qw(query_xml);

my $prog = $0; $prog =~ s:.*/::;

sub usage {
   my ($message) = @_;

   print "$message\n" if $message;

   print STDERR << "END";
usage:

   $prog file.xml

   This is a workaround when xmllint or xmlstarlet is not available. (We have
   so many old machines missing the basic utilities.) I tried to install
   XML::Parser but some of our platforms are too old to install.

   NOTE: XML protocol will replace newline with space in the attribute

   -v verbose

   -path string           perl-style, eg, -path {FIXSession}->{suppress-out}
                          can repeat

   -ForceArray a,b,c      force this tags into array.

   -KeyAttr tag=attr      can repeat, eg, -KeyAttr tl=a1 -KeyAttr t2=a2

   -addRoot string        add a root node

examples:

   # To see the XML general structure
   $prog XML_test.xml
   $prog -ForceArray FIXSession XML_test.xml

   # To get a branch or leaf, taking steps to narrow down to your target
   $prog -path 'return \$root' XML_test.xml
   $prog -path 'return \$root->{FIXSession}' XML_test.xml
   $prog -path 'return \$root->{FIXSession}->{"suppress-out"}' XML_test.xml

   # 'return' is optional
   $prog -path '\$root->{FIXSession}->{"suppress-out"}' XML_test.xml
   
   # To handle array, we have to use loop. The following are the same
   $prog -ForceArray FIXSession -path \\
      'for my \$e (\@{\$root->{FIXSession}}) {
         if (\$e->{"sender-comp-id"} eq "SENDER1") {
            return \$e->{"suppress-out"} }}' XML_test.xml

   $prog -ForceArray FIXSession -path \\
      "for my \\\$e (\@{\\\$root->{FIXSession}}) {
         if (\\\$e->{'sender-comp-id'} eq 'SENDER1') {
            return \\\$e->{'suppress-out'} }}" XML_test.xml

   $prog -ForceArray FIXSession -path \\
      "for (\@{\\\$root->{FIXSession}}) {
         if (\\\$_->{'sender-comp-id'} eq 'SENDER1') {
           return \\\$_->{'suppress-out'} }}" XML_test.xml

   $prog -ForceArray FIXSession -path \\
      "for (\@{\\\$root->{FIXSession}}) {
         (\\\$_->{'sender-comp-id'} eq 'SENDER1') && return \\\$_->{'suppress-out'} }" XML_test.xml

   # Return an array
   $prog -path 'my \@a=keys(\%{\$root->{FIXSession}}); return \\\@a;' XML_test.xml

   #This is equivalent to xmllint
   $prog -path 'return \$root' XML_test.xml

   # this add a root node to an file without root node
   $prog -addRoot xml XML_test_withoutRoot.xml

END

   exit 1;
}

my $tag_string;
my $verbose;
my %attr_by_key;
my $ForceArrayString;
my @paths;
my $addRoot;

GetOptions(
   'v|verbose'    => \$verbose,
   'ForceArray=s' => \$ForceArrayString,
   'KeyAttr=s'    => \%attr_by_key,
   'p|path=s'     => \@paths,
   'addRoot=s'    => \$addRoot,
) || usage ("cannot parse command line: $!");

usage("wrong number of args") if @ARGV != 1 ;

my $file = shift @ARGV;

my $rows = query_xml($file, {
   KeyAttr     =>\%attr_by_key,
   ForceArray  =>$ForceArrayString,
   verbose     =>$verbose,
   paths       =>\@paths,
   AddRootNode =>$addRoot,
});

$verbose && print Dumper($rows);

#my $type = ref $rows;
#if ($type eq 'ARRAY' || $type eq 'HASH') {

$Data::Dumper::Terse = 1;

for my $r (@$rows) {
   my $string = Dumper($r);
   print $string;
}

exit 0;
   
