#!/usr/bin/env perl

use strict;
use Data::Dumper;
use Getopt::Long;
use TPSUP::DATE qw(get_tradedays);

my $prog = $0; $prog =~ s:.*/::;
my $dir = $0; $dir =~ s:[^/]+$::;

sub usage {
   my ($msg) = @_;

   print STDERR "$msg\n" if $msg;

   print STDERR << "EOF";
usage:

   $prog count

description:
   get trade day

   -d yyyymmdd     use this as today, the reference day.
   -e exch         exclude this exchange's holidays, default to NYSE

   -OnWeekend next|previous 
                   if reference day is on weekend, default to move it to 'previous'
                   tradeday, eg, Friday.
                   if set 'next', then will change it to 'next' tradeday, eg, Monday

   If reference day is on weekend, we will change to use the coming tradeday, normally
   Monday; but if Monday is holiday, then it will become Tuesday.

examples:

   $prog   3  # next 3 tradedays
   $prog   0  # 0 day
   $prog  -3  # previous 3 tradedays

   - 20200905 is Saturday. 20200907 is Monday, labor day holiday.
     for 20200905/20200906/20200907,
         By default, current tradeday changes to Friday 20200904.  and the previous tradeday
         becomes Thursday, 20200903
         If '-OnWeekend next', current tradeday changes to Friday 20200908.
         and the previous tradeday becomes Friday, 20200904

   $prog -d 20200905   2  # you should see 20200908, 20200909
   $prog -d 20200908   2  # you should see 20200909, 20200910
   $prog -d 20200905  -2  # you should see 20200902, 20200903

   $prog -d 20200905 -OnWeekend next  2  # you should see 20200909, 20200910
   $prog -d 20200908 -OnWeekend next  2  # you should see 20200909, 20200910
   $prog -d 20200905 -OnWeekend next -2  # you should see 20200903, 20200904
                        
EOF
   exit 1;
}

my @leftover;
my $opt = {};

eval {
   for (my $i=0; $i<scalar(@ARGV); $i++) {
      if ($ARGV[$i] eq '-d') {
         $opt->{Begin} = $ARGV[$i+1];
         $i++;
      } elsif ($ARGV[$i] eq '-e') {
         $opt->{Exch} = $ARGV[$i+1];
         $i++;
      } elsif ($ARGV[$i] eq '-OnWeekend') {
         $opt->{OnWeekend} = $ARGV[$i+1];
         $i++;
      } else {
         push @leftover, $ARGV[$i];
      }
   }
};

usage("wrong command args") if $@; 

usage("wrong number of args") if @leftover != 1;

my ($offset) = @leftover;

print join("\n", @{get_tradedays($offset, $opt)}), "\n";

exit 0;
