#!/bin/bash

# get window size
# wmic path Win32_VideoController get CurrentHorizontalResolution,CurrentVerticalResolution
powershell -Command "Get-CimInstance Win32_VideoController | Select-Object CurrentHorizontalResolution, CurrentVerticalResolution"
