#!/bin/bash

prog=$(basename $0)

usage() {
   cat >&2 <<EOF
usage:

   $prog a[ll]|i[nternal]|e[xternal]

   get the current window size (horizontal and vertical resolution)

   -v       verbose output

examples:

   $prog a
   $prog i
   $prog e

EOF

   exit 1
}

# get window size
# wmic path Win32_VideoController get CurrentHorizontalResolution,CurrentVerticalResolution
# powershell -Command "Get-CimInstance Win32_VideoController | Select-Object CurrentHorizontalResolution, CurrentVerticalResolution"

verbose=0
while getopts "v" opt; do
   case $opt in
      v) verbose=1 ;;
      *) usage ;;
   esac
done
shift $((OPTIND - 1))

if [ $# -ne 1 ]; then
   echo "Error: wrong number of arguments" >&2
   usage
fi

mode=$1

if [ $verbose -eq 1 ]; then
   headers="CurrentHorizontalResolution, CurrentVerticalResolution, AdapterDACType, AdapterCompatibility, MaxRefreshRate, MinRefreshRate"
else
   headers="CurrentHorizontalResolution, CurrentVerticalResolution"
fi

if [[ ! $mode =~ ^(a|i|e)$ ]]; then
   echo "Error: invalid mode" >&2
   usage
elif [ $mode == "a" ]; then
   # handle all displays
   powershell -Command "Get-CimInstance Win32_VideoController | Select-Object $headers"
elif [ $mode == "i" ]; then
   # handle internal display
   # AdapterDACType               : Internal  # not a reliable indicator of internal display
   # PNPDeviceID                  : PCI\VEN_8086&DEV_5917&SUBSYS_081A1028&REV_07\3&11583659&0&10
   powershell -Command "Get-CimInstance Win32_VideoController | Where-Object { \$_.PNPDeviceID -notlike 'USB*' } | Select-Object $headers"
elif [ $mode == "e" ]; then
   # handle external display
   # AdapterDACType               : 
   # PNPDeviceID                  : USB\VID_17E9&PID_6006&MI_01\7&33B12E0A&0&0001   # reliable indicator of external display
   # PNPDeviceID                  : SWD\REMOTEDISPLAYNUM\RDPIDD_...   # another example of external display, cloud pc
   # AdapterCompatibility         : DisplayLink
   # MaxRefreshRate               : 75
   # MinRefreshRate               : 50
   # the inactive external display seems to have no MaxRefreshRate or MinRefreshRate
   powershell -Command "Get-CimInstance Win32_VideoController | Where-Object { (\$_.PNPDeviceID -like 'USB*' -or \$_.PNPDeviceID -like 'SWD*') -and \$_.MaxRefreshRate -ne \$null -and \$_.MinRefreshRate -ne \$null } | Select-Object $headers"
fi
